### PR TITLE
Enhance and clarify descriptions for relevant file and language fields across prompts

### PR DESCRIPTION
**Pull request by KennyDizi**
### **PR Type**
Documentation, Enhancement

___

### **Description**
- Improved the descriptions for various fields across multiple TOML configuration files to enhance clarity and consistency.
- Updated `relevant_file` and `language` field descriptions in `pr_add_docs.toml`, `pr_code_suggestions_prompts.toml`, `pr_description_prompts.toml`, and `pr_reviewer_prompts.toml`.

___

### **Changes walkthrough** 
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_add_docs.toml</strong><dd><code>Improve description for relevant file in add docs prompt</code>&nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_add_docs.toml

- Updated description for `relevant file` to improve clarity.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1039/files#diff-27056b83691901e90900a125d483a0197c53dfd81766e02582847551ed313169">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions_prompts.toml</strong><dd><code>Enhance descriptions for relevant file and language in code </code><br><code>suggestions prompt</code></dd></summary>
<hr>

pr_agent/settings/pr_code_suggestions_prompts.toml

<li>Updated descriptions for <code>relevant_file</code> and <code>language</code> fields to improve <br>clarity.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1039/files#diff-81979f64eddc8f93a5c6ea83ff1e7ba92e551acaecd310c606255161e914c2ea">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>pr_description_prompts.toml</strong><dd><code>Improve descriptions for filename and language in PR description </code><br><code>prompt</code></dd></summary>
<hr>

pr_agent/settings/pr_description_prompts.toml

<li>Updated descriptions for <code>filename</code> and <code>language</code> fields to improve <br>clarity.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1039/files#diff-a52546bc2f8a156d8ee786c403e44b1561a6e3f1d98fcfbe8a0120bcee59981b">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer_prompts.toml</strong><dd><code>Enhance descriptions for relevant file and language in reviewer prompt</code></dd></summary>
<hr>

pr_agent/settings/pr_reviewer_prompts.toml

<li>Updated descriptions for <code>relevant_file</code> and <code>language</code> fields to improve <br>clarity.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1039/files#diff-2e1ca45d2d8635b5f9cde801d9d210f6516e7f15d45dd9b0be134ac91e7a2e63">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by KennyDizi** [comment]
🏠 🌔 I've updated the **[PR description](https://github.com/Codium-ai/pr-agent/pull/1039)** to match the latest commit (https://github.com/Codium-ai/pr-agent/commit/20206af1bf41157d288024b682451a1fc14042d8).

**Comment by KennyDizi** [comment]
@mrT23 Would you take a look at this?

**Comment by mrT23** [comment]
The prompt here is not better than before.

"full path" is more accurate than "complete path"

image

**Comment by KennyDizi** [comment]
I see. thanks

**Comment by KennyDizi** [comment]
Would you share the prompt so we can compare the accuracy of the old and new prompts above?
It would be constructive. @mrT23

**Comment by KennyDizi** [comment]
I've changed it back to full path. Would you give feedback on the `language` property description?

**Comment by mrT23** [comment]
ok

**Review by mrT23 — APPROVED** [review]

**Comment by KennyDizi** [comment]
## PR Analysis 🌗

<table>
<tr><td><br>⏰ &nbsp;<strong>Estimated effort to review</strong>: 1, because this PR only involves minor documentation changes in configuration files. The changes are straightforward and easy to review, focusing on improving descriptions for specific fields.</td></tr>
<tr><td><br>🥇 &nbsp;<strong>Score</strong>: 95, because the changes are simple, clear, and improve the documentation without introducing any potential bugs or performance issues. The modifications enhance the clarity of field descriptions, which is beneficial for developers using these configuration files.
</td></tr>
<tr><td><br>🧪 &nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td><br>🔒 &nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td><br>🌄 &nbsp;<strong>No key issues to review</strong>: This PR focuses on enhancing and clarifying descriptions for the `relevant_file` and `language` fields across multiple TOML configuration files. The changes are minor but improve the overall clarity and consistency of the documentation. The modifications affect four files: `pr_add_docs.toml`, `pr_code_suggestions_prompts.toml`, `pr_description_prompts.toml`, and `pr_reviewer_prompts.toml`. The updates provide more precise and informative descriptions for these fields, which will help developers better understand their purpose and usage.
</td></tr>
</table>

**Pull request merged**
