### PR TITLE
[Enhancement] Disable pip cache in Dockerfiles to reduce image size


### PR DESCRIPTION
**Pull request by idubnori**
## **User description**
Remove the pip cache is created when pip install from the docker image layer. Currently, 80MB is being consumed needlessly and reduce it.

```bash
$ docker images | grep pr-agent                                         
pr-agent                                 no-pip-cache      3f43414e6ff8   About a minute ago   1.3GB
codiumai/pr-agent                        github_action     3b96010bd372   4 days ago           1.38GB
```

### Note
- `ARG PIP_NO_CACHE_DIR=1`
ref. https://stackoverflow.com/a/60270281/4252588
- `80MB is being consumed needlessly.`
You can see it using [dive](https://github.com/wagoodman/dive)
- More fundamental improvements might be using `shim` or `distroless` image and multi-stage build

___

## **Type**
enhancement

___

## **Description**
- Added `ARG PIP_NO_CACHE_DIR=1` to Dockerfiles to disable pip cache, reducing the image size across different Docker configurations.
- This change affects the GitHub Actions Dockerfile, the main Dockerfile, and the AWS Lambda Dockerfile.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Dockerfile.github_action</strong><dd><code>Disable pip cache in GitHub Actions Dockerfile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
Dockerfile.github_action

<li>Added <code>ARG PIP_NO_CACHE_DIR=1</code> to disable pip cache and reduce image <br>size.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/878/files#diff-e18b685370151a3e574de5890d93010fb040e118f57027f8ce2dc9f64756f365">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Dockerfile</strong><dd><code>Disable pip cache in main Dockerfile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
docker/Dockerfile

<li>Added <code>ARG PIP_NO_CACHE_DIR=1</code> to disable pip cache and reduce image <br>size.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/878/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Dockerfile.lambda</strong><dd><code>Disable pip cache in Lambda Dockerfile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
docker/Dockerfile.lambda

<li>Added <code>ARG PIP_NO_CACHE_DIR=1</code> to disable pip cache in AWS Lambda Docker <br>image.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/878/files#diff-058face14f24d59f3284132329639a9fe7b213bc2fab9bdd9210f236e0c55c71">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
@idubnori 
I am hesitant about this change.

What are the downside of adding this line ? why it is not enabled by default ?
will it take longer to re-build ?
won't this introduce versioning problems ?

**Comment by idubnori** [comment]
@mrT23 Thank you for your reply. 

> What are the downside of adding this line ? why it is not enabled by default ?

I think no downside as long as using inside dockerfile. The pip cache  should be intended to eliminate the need to re-download the same package file locally. There is no scenario cached packages are reused in the current dockerfile.

> will it take longer to re-build ?

If you are building docker in a local environment, the previous layer cache will not be reused, so pip install will be re-run only for the first time build after this changes. After that, unless the `pyproject.toml requirements.txt` is changed,  the docker layer cache will be used and pip install will not be executed. If building docker in an immutable environment (e.g. github actions hosted runner), pip install will be performed each time and the build time will not change.

> won't this introduce versioning problems ?

If building an other docker image based on the pr-agent docker image, it may be less risky to leave the cache in place, but I think it is the edge case. To minimize the version problem or risk, instead of disabling the pip cache, I think use cache purge after pip install, rather than disabling the pip cache. (use `&& pip cache purge` instead of `PIP_NO_CACHE_DIR=1`)

**Comment by idubnori** [comment]
If more concerns or questions, I would like to suggest wait for comments from other contributors or PR can be closed. This PR is not very effective, also not important for me at this time.

**Comment by hussam789** [comment]
/describe
--pr_description.extra_instructions="
For the title, use the format [type]: [summary]
"
--pr_description.generate_ai_title=true

**Comment by hussam789** [comment]
sss

**Comment by mrT23** [comment]
ok, thanks @idubnori 
i will close the PR for now, but the effort to reduce the docker size is welcomed.

**Pull request closed without merging**
