### PR TITLE
Tr/dynamic context

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement

___

### **Description**
- Implemented dynamic context handling in git patch processing to improve code understanding and review
- Added new settings `allow_dynamic_context` and `max_extra_lines_before_dynamic_context` to control the feature
- Refactored context limit calculations into a separate function for better code organization
- Introduced logic to dynamically adjust context based on section headers, improving patch readability
- Added logging for dynamic context adjustments and section header findings
- Updated configuration file with new options and explanatory comments

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>git_patch_processing.py</strong><dd><code>Implement dynamic context handling in patch processing</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/git_patch_processing.py

<li>Introduced dynamic context handling with new settings: <br><code>allow_dynamic_context</code> and <code>max_extra_lines_before_dynamic_context</code><br> <li> Added logic to adjust context limits dynamically based on section <br>headers<br> <li> Implemented logging for dynamic context adjustments and section header <br>findings<br> <li> Refactored the context calculation into a separate function <br><code>_calc_context_limits</code><br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1156/files#diff-c5a7f9db4adbcf394c7855f6da656c073d5a6bcc18bd6dede44a8207893174b8">+42/-10</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add configuration options for dynamic context</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

<li>Added new configuration options: <code>allow_dynamic_context</code> (default: <br>false) and <code>max_extra_lines_before_dynamic_context</code> (default: 10)<br> <li> Updated comments to explain the new dynamic context feature<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1156/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by KennyDizi** [comment]
This should be an excellent feature, enhancing context awareness. Looking forward to it.

**Comment by mrT23** [comment]
> This should be an excellent feature, enhancing context awareness. Looking forward to it.

yep

image
image

**Comment by KennyDizi** [comment]
@mrT23 I'm wondering if we add more lines to the context, do we need to adjust the review and code suggestion prompts?

**Comment by mrT23** [comment]
@KennyDizi 
Its an ongoing research. thinking about it.
currently by default its false, so do-no-harm

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
