### PR TITLE
Merge branch 'main' of https://github.com/ryanzll/pr-agent

### PR DESCRIPTION
**Pull request by ryanzll**
### **User description**
update openai api

___

### **PR Type**
enhancement, bug fix

___

### **Description**
- Updated the OpenAI API integration to use `AsyncOpenAI` for asynchronous operations.
- Changed the way API keys and base URLs are set, now using environment variables.
- Removed the `TryAgain` exception from the retry mechanism to streamline error handling.
- Enhanced logging for better traceability of system and user messages.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>openai_ai_handler.py</strong><dd><code>Update OpenAI API integration and error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/ai_handlers/openai_ai_handler.py

<li>Replaced direct OpenAI API key assignment with environment variable.<br> <li> Updated OpenAI API client to use <code>AsyncOpenAI</code>.<br> <li> Removed <code>TryAgain</code> exception from retry decorator.<br> <li> Improved error handling and logging.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1332/files#diff-b1102362ec51ffc9d9513f7a39cab5c62c1f188da389a2e9702160ebb26b1020">+12/-12</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by mrT23** [comment]
What is the goal of this PR ? What does it aim to improve ?

Changing key files without clear and undeniable motivation won't be approved

**Comment by ryanzll** [comment]
Old code in openai_ai_handler.py can not work in my computer, and after updating openai sdk and openai_ai_handler, it works.
This is key file, it may be dangerous without necessary and enough testing, it is acceptable that don't approve. 

BTW: The api of openai is changed, hope can be integrated soon.

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
Thanks @ryanzll 
Indeed the file was out of sync, and it works after your update.

A small tip for the future - share as much information as possible when you open a PR in an open source repo.
Without it, it's hard to understand, even with PR-Agent, the goal of the PR.

```
"update openai API" 
```

-> 

```
The current file seems out of date, and when running it I got the following error: {}
After the update in this PR, I was able to run it
```

**Comment by ryanzll** [comment]
Sorry for not provide enough information, i will improve next time.

**Pull request merged**
