### PR TITLE
tests

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Tests

___

### **Description**
- Enhanced `convert_to_markdown_v2` function to handle non-numeric values in the 'Estimated effort to review' section.
- Uncommented the check for empty `output_data` in `convert_to_markdown_v2`.
- Updated unit tests to use `convert_to_markdown_v2` and modified expected outputs accordingly.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Improve markdown conversion and error handling in </code><br><code><code>convert_to_markdown_v2</code></code></dd></summary>
<hr>
      
pr_agent/algo/utils.py

<li>Uncommented the check for empty <code>output_data</code> in <code>convert_to_markdown_v2</code>.<br> <li> Added handling for non-numeric values in the 'Estimated effort to <br>review' section.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1016/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+10/-4</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_convert_to_markdown.py</strong><dd><code>Update unit tests for `convert_to_markdown_v2` function</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
tests/unittest/test_convert_to_markdown.py

<li>Updated tests to use <code>convert_to_markdown_v2</code> instead of <br><code>convert_to_markdown</code>.<br> <li> Modified expected output to match changes in <code>convert_to_markdown_v2</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1016/files#diff-48e28c70a7fa0ad268cc0cd35739816da980187199079f2c78eeffff330ce450">+6/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1016#issuecomment-2205147828)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/57abf4ac625d8ee856ea21629931591bb57c2df7

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
