### PR TITLE
Fix markdown typos

### PR DESCRIPTION
**Pull request by KennyDizi**
### **PR Type**
documentation

___

### **Description**
- Fixed hyperlinks in the 'describe' section of the documentation.
- Removed `<figure>` tags around images to simplify the markdown.
- Adjusted image embedding by removing width specifications.
- Improved overall formatting and compliance with markdownlint.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Fix hyperlinks and improve image embedding in documentation</code></dd></summary>
<hr>
      
docs/docs/index.md

<li>Fixed hyperlinks in the 'describe' section.<br> <li> Removed <code><figure></code> tags around images.<br> <li> Adjusted image embedding to remove width specifications.<br> <li> Minor formatting improvements.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/982/files#diff-7dd3ba15306fb8ca0c3fa4a2e10b4d3b708c3a338bc2c4a028b4e1d0e565dc88">+10/-20</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by KennyDizi** [comment]
Before PR
CleanShot 2024-06-18 at 16 03 02

**Comment by KennyDizi** [comment]
After PR
CleanShot 2024-06-18 at 16 03 44

**Comment by mrT23** [comment]
These are template markdowns for **mkserve**. They should be viewed here:
https://pr-agent-docs.codium.ai/#pr-agent-features

Hence, the corrections are wrong

**Comment by KennyDizi** [comment]
> These are template markdowns for **mkserve** deployment. They should be viewed here: https://pr-agent-docs.codium.ai/#pr-agent-featuresv
> 
> image
> 
> Hence, there are no "markdown" errors

I see.

**Pull request closed without merging**
