### PR TITLE
Add new GPT-4o models and update tiktoken to 0.7.0

### PR DESCRIPTION
**Pull request by KennyDizi**
## **Type**
enhancement

___

## **Description**
- Added 'gpt-4o' and 'gpt-4o-2024-05-13' models to the list of available models
- Updated tiktoken to version 0.7.0

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add new GPT-4o models</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/__init__.py
<li>Added 'gpt-4o' and 'gpt-4o-2024-05-13' models to the list of available <br>models

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/901/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692b">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>

<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Update tiktoken to 0.7.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt
- Updated tiktoken to version 0.7.0

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/901/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
</table></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by KennyDizi** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/901)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/36ad8935ad47e2362ca1a4d498b8c31867457db9)

**Review by barnett-yuxiang — APPROVED** [review]

**Comment by KennyDizi** [comment]
> It is recommended to update the content of the doc synchronously?

Would you pls assist me with where I can update the doc for those new models? I can't find it out

**Comment by barnett-yuxiang** [comment]
> > It is recommended to update the content of the doc synchronously?
> 
> Would you pls assist me with where I can update the doc for those new models? I can't find it out

image

I understand that updating here is enough, but let's still listen to @mrT23 advice. 🤝

**Comment by KennyDizi** [comment]
> > > It is recommended to update the content of the doc synchronously?
> > 
> > 
> > Would you pls assist me with where I can update the doc for those new models? I can't find it out
> 
> image
> 
> I understand that updating here is enough, but let's still listen to @mrT23 advice. 🤝

cool!

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
Thanks @KennyDizi 

Currently, it's just an option, but it's definitely a strong candidate to become the default model in the near future.
(I am benchmarking it on alphaCodium, to get a sense of how good it really is on code. will be finished soon)

**Comment by KennyDizi** [comment]
> Thanks @KennyDizi
> 
> Currently, it's just an option, but it's definitely a strong candidate to become the default model in the near future. (I am benchmarking it on alphaCodium, to get a sense of how good it really is on code. will be finished soon)

Thanks, @mrT23 gpt-4o model made a new standard; we're looking for your benchmark.

**Comment by vKongv** [comment]
I tried to use gpt-4o as my model and I encountered this error. I am running it in Github Action

My github action yml file:

```yml
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && 
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/review'))
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on pull requests and respond to '/review' comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          CONFIG.MODEL: gpt-4o-2024-05-13
          PR_REVIEWER.INLINE_CODE_COMMENTS: true
          PR_REVIEWER.PERSISTENT_COMMENT: false
          PR_REVIEWER.NUM_CODE_SUGGESTIONS: 8
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```
{"text": "Applying repo settings\n", "record": {"elapsed": {"repr": "0:00:01.098014", "seconds": 1.098014}, "exception": null, "extra": {}, "file": {"name": "github_action_runner.py", "path": "/app/pr_agent/servers/github_action_runner.py"}, "function": "run_action", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 75, "message": "Applying repo settings", "module": "github_action_runner", "name": "__main__", "process": {"id": 6, "name": "MainProcess"}, "thread": {"id": 139708756859776, "name": "MainThread"}, "time": {"repr": "2024-05-14 10:44:11.476957+00:00", "timestamp": 1715683451.476957}}}
{"text": "Failed to clip tokens: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'\n", "record": {"elapsed": {"repr": "0:00:03.222232", "seconds": 3.222232}, "exception": null, "extra": {"command": "review"}, "file": {"name": "utils.py", "path": "/app/pr_agent/algo/utils.py"}, "function": "clip_tokens", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 582, "message": "Failed to clip tokens: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'", "module": "utils", "name": "pr_agent.algo.utils", "process": {"id": 6, "name": "MainProcess"}, "thread": {"id": 139708756859776, "name": "MainThread"}, "time": {"repr": "2024-05-14 10:44:13.60[11](https://github.com/dresstal-berhad/auito-be/actions/runs/9078012351/job/24944105248#step:3:12)75+00:00", "timestamp": 1715683453.601175}}}
{"text": "Failed to clip tokens: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'\n", "record": {"elapsed": {"repr": "0:00:03.511451", "seconds": 3.511451}, "exception": null, "extra": {"command": "review"}, "file": {"name": "utils.py", "path": "/app/pr_agent/algo/utils.py"}, "function": "clip_tokens", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 582, "message": "Failed to clip tokens: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'", "module": "utils", "name": "pr_agent.algo.utils", "process": {"id": 6, "name": "MainProcess"}, "thread": {"id": 139708756859776, "name": "MainThread"}, "time": {"repr": "2024-05-14 10:44:13.890394+00:00", "timestamp": 1715683453.890394}}}
Traceback (most recent call last):
  File "/app/pr_agent/servers/github_action_runner.py", line 148, in <module>
    asyncio.run(run_action())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/pr_agent/servers/github_action_runner.py", line 141, in run_action
    await PRAgent().handle_request(url, body,
  File "/app/pr_agent/agent/pr_agent.py", line 93, in handle_request
    await command2class[action](pr_url, ai_handler=self.ai_handler, args=args).run()
  File "/app/pr_agent/tools/pr_reviewer.py", line 75, in __init__
    self.token_handler = TokenHandler(
  File "/app/pr_agent/algo/token_handler.py", line 47, in __init__
    self.encoder = TokenEncoder.get_token_encoder()
  File "/app/pr_agent/algo/token_handler.py", line 19, in get_token_encoder
    cls._encoder_instance = encoding_for_model(cls._model) if "gpt" in cls._model else get_encoding(
  File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 97, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
  File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 84, in encoding_name_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-4o-2024-05-[13](https://github.com/dresstal-berhad/auito-be/actions/runs/9078012351/job/24944105248#step:3:14) to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
```

Am I missing anything?

**Comment by KennyDizi** [comment]
> I tried to use gpt-4o as my model and I encountered this error. I am running it in Github Action
> 
> 
> 
> My github action yml file:
> 
> 
> 
> ```yml
> 
> jobs:
> 
>   pr_agent_job:
> 
>     runs-on: ubuntu-latest
> 
>     if: |
> 
>       (github.event_name == 'pull_request') ||
> 
>       (github.event_name == 'issue_comment' && 
> 
>       github.event.issue.pull_request && 
> 
>       contains(github.event.comment.body, '/review'))
> 
>     permissions:
> 
>       issues: write
> 
>       pull-requests: write
> 
>       contents: write
> 
>     name: Run pr agent on pull requests and respond to '/review' comments
> 
>     steps:
> 
>       - name: PR Agent action step
> 
>         id: pragent
> 
>         uses: Codium-ai/pr-agent@main
> 
>         env:
> 
>           CONFIG.MODEL: gpt-4o-2024-05-13
> 
>           PR_REVIEWER.INLINE_CODE_COMMENTS: true
> 
>           PR_REVIEWER.PERSISTENT_COMMENT: false
> 
>           PR_REVIEWER.NUM_CODE_SUGGESTIONS: 8
> 
>           OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
> 
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> 
> ```
> 
> 
> 
> ```
> 
> {"text": "Applying repo settings\n", "record": {"elapsed": {"repr": "0:00:01.098014", "seconds": 1.098014}, "exception": null, "extra": {}, "file": {"name": "github_action_runner.py", "path": "/app/pr_agent/servers/github_action_runner.py"}, "function": "run_action", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 75, "message": "Applying repo settings", "module": "github_action_runner", "name": "__main__", "process": {"id": 6, "name": "MainProcess"}, "thread": {"id": 139708756859776, "name": "MainThread"}, "time": {"repr": "2024-05-14 10:44:11.476957+00:00", "timestamp": 1715683451.476957}}}
> 
> {"text": "Failed to clip tokens: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'\n", "record": {"elapsed": {"repr": "0:00:03.222232", "seconds": 3.222232}, "exception": null, "extra": {"command": "review"}, "file": {"name": "utils.py", "path": "/app/pr_agent/algo/utils.py"}, "function": "clip_tokens", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 582, "message": "Failed to clip tokens: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'", "module": "utils", "name": "pr_agent.algo.utils", "process": {"id": 6, "name": "MainProcess"}, "thread": {"id": 139708756859776, "name": "MainThread"}, "time": {"repr": "2024-05-14 10:44:13.60[11](https://github.com/dresstal-berhad/auito-be/actions/runs/9078012351/job/24944105248#step:3:12)75+00:00", "timestamp": 1715683453.601175}}}
> 
> {"text": "Failed to clip tokens: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'\n", "record": {"elapsed": {"repr": "0:00:03.511451", "seconds": 3.511451}, "exception": null, "extra": {"command": "review"}, "file": {"name": "utils.py", "path": "/app/pr_agent/algo/utils.py"}, "function": "clip_tokens", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 582, "message": "Failed to clip tokens: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'", "module": "utils", "name": "pr_agent.algo.utils", "process": {"id": 6, "name": "MainProcess"}, "thread": {"id": 139708756859776, "name": "MainThread"}, "time": {"repr": "2024-05-14 10:44:13.890394+00:00", "timestamp": 1715683453.890394}}}
> 
> Traceback (most recent call last):
> 
>   File "/app/pr_agent/servers/github_action_runner.py", line 148, in <module>
> 
>     asyncio.run(run_action())
> 
>   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
> 
>     return loop.run_until_complete(main)
> 
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
> 
>     return future.result()
> 
>   File "/app/pr_agent/servers/github_action_runner.py", line 141, in run_action
> 
>     await PRAgent().handle_request(url, body,
> 
>   File "/app/pr_agent/agent/pr_agent.py", line 93, in handle_request
> 
>     await command2class[action](pr_url, ai_handler=self.ai_handler, args=args).run()
> 
>   File "/app/pr_agent/tools/pr_reviewer.py", line 75, in __init__
> 
>     self.token_handler = TokenHandler(
> 
>   File "/app/pr_agent/algo/token_handler.py", line 47, in __init__
> 
>     self.encoder = TokenEncoder.get_token_encoder()
> 
>   File "/app/pr_agent/algo/token_handler.py", line 19, in get_token_encoder
> 
>     cls._encoder_instance = encoding_for_model(cls._model) if "gpt" in cls._model else get_encoding(
> 
>   File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 97, in encoding_for_model
> 
>     return get_encoding(encoding_name_for_model(model_name))
> 
>   File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 84, in encoding_name_for_model
> 
>     raise KeyError(
> 
> KeyError: 'Could not automatically map gpt-4o-2024-05-[13](https://github.com/dresstal-berhad/auito-be/actions/runs/9078012351/job/24944105248#step:3:14) to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
> 
> ```
> 
> 
> 
> Am I missing anything?
> 
> 
> 
> Edit: I also try using `gpt-4o` for `CONFIG.MODEL` but it still getting the same error

You have to install the tiktoken v0.7.0 to use new model.

**Comment by mrT23** [comment]
@vKongv 
i only now updated the dockers. try again

**Comment by vKongv** [comment]
works now

**Comment by mrT23** [comment]
@KennyDizi 
p.s.
https://twitter.com/talrid23/status/1790342268555079906

the model does look strong (and fast).
couple more days, and I think I will make it the default one

**Comment by barnett-yuxiang** [comment]
@mrT23 

The speed is 2x faster, and the price is only 50% of the original.

image

**Comment by mrT23** [comment]
@barnett-yuxiang i understand, and will probably use it as the default model in the near future.

But:
As a general strategy, I don't like to switch models the first day they come out:
1) usually there are availability issues, that are resolved along the way
2) I want to validate the quality, both from my inspection and from general internet feedback

ping me in a week or so if the base model was not switched :-)

**Comment by barnett-yuxiang** [comment]
Oh, @mrT23 , I understand your expression very well, and if it were me, I would also make decisions like you. Our thoughts are the same.

**Pull request merged**
