### PR TITLE
ignore bot

### PR DESCRIPTION
**Pull request by mrT23**
## **Type**
enhancement

___

## **Description**
- Centralized the logic to ignore PRs opened by bots into the `handle_request` function for better code organization and readability.
- Removed the `sender_type` parameter from the `handle_new_pr_opened` function as part of the refactor.
- Added explanatory comments to make the bot ignore logic clearer and more maintainable.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>github_app.py</strong><dd><code>Centralize Bot PR Ignore Logic and Refactor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/servers/github_app.py

<li>Refactored bot PR ignore logic to a more centralized location.<br> <li> Removed sender_type parameter from handle_new_pr_opened function.<br> <li> Added comments for clarity on bot ignore logic.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/817/files#diff-3fb3f174152732d1b69953c8bd81b8a0a30f0e42100dc626d932da8371851608">+6/-7</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by barnett-yuxiang — COMMENTED** [review]
cool

**Comment by mrT23** [comment]
## Generating code suggestions for 'handle_request'


Work in progress ...<br>

**Pull request merged**
