### PR TITLE
Tr/patch extra lines before and after

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Tests

___

### **Description**
- Implemented separate parameters for extending patches before and after changes (`patch_extra_lines_before` and `patch_extra_lines_after`)
- Updated `extend_patch` function and related PR processing logic to support the new patch extension parameters
- Added tests for the new patch extension functionality
- Updated configuration and documentation to reflect the new patch extension parameters
- Increased `max_context_tokens` for PR code suggestions from 10000 to 16000
- Added support for the 'claude-3-5-sonnet' model
- Enabled extra lines in code suggestions by default

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add new Claude model</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/__init__.py

- Added 'claude-3-5-sonnet' model with a token limit of 100000

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1114/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692b">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Update configuration for patch extension</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

<li>Changed <code>patch_extra_lines</code> to separate <code>patch_extra_lines_before</code> and <br><code>patch_extra_lines_after</code><br> <li> Increased <code>max_context_tokens</code> for PR code suggestions from 10000 to <br>16000<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1114/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>git_patch_processing.py</strong><dd><code>Refactor patch extension logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/git_patch_processing.py

<li>Modified <code>extend_patch</code> function to accept separate parameters for lines <br>before and after<br> <li> Updated logic to extend patches based on new parameters<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1114/files#diff-c5a7f9db4adbcf394c7855f6da656c073d5a6bcc18bd6dede44a8207893174b8">+8/-19</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_processing.py</strong><dd><code>Update PR diff generation with new patch extension</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/pr_processing.py

<li>Updated <code>get_pr_diff</code> and <code>pr_generate_extended_diff</code> functions to use <br>separate before and after line parameters<br> <li> Modified patch extension calls to use new parameters<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1114/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04e">+15/-17</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions.py</strong><dd><code>Enable extra lines in code suggestions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_code_suggestions.py

<li>Changed <code>disable_extra_lines</code> parameter to <code>False</code> in <code>_prepare_prediction</code> <br>method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1114/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_extend_patch.py</strong><dd><code>Update and add tests for patch extension</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/unittest/test_extend_patch.py

<li>Updated existing tests to use new patch extension parameters<br> <li> Added new test class <code>PRProcessingTest</code> with tests for extended patches<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1114/files#diff-48667553b73a52b1d2d29518bb39e100e999148c141a5045328e6a12cb17bb8e">+65/-45</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>additional_configurations.md</strong><dd><code>Update documentation for patch extension config</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/usage-guide/additional_configurations.md

<li>Updated configuration example to use separate <code>patch_extra_lines_before</code> <br>and <code>patch_extra_lines_after</code> parameters<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1114/files#diff-9290a3ad9a86690b31f0450b77acd37ef1914b41fabc8a08682d4da433a77f90">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
