### PR TITLE
sonnet-3.5

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Documentation

___

### **Description**
- Added support for the `bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0` model in the initialization file.
- Enhanced AWS and API key handling in `litellm_ai_handler.py` by adding AWS credentials from settings and removing `aws_bedrock_client` initialization and usage.
- Introduced conditional prompt selection for Claude model in `pr_code_suggestions.py`.
- Updated README with a news entry about the support for Claude 3.5 Sonnet model.
- Added a new prompt configuration for Claude model in `pr_code_suggestions_prompts.toml`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add support for Claude 3.5 Sonnet model in initialization</code></dd></summary>
<hr>

pr_agent/algo/__init__.py

<li>Added support for <code>bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0</code> <br>model.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1022/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692b">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>litellm_ai_handler.py</strong><dd><code>Enhance AWS and API key handling in LiteLLM AI handler</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/ai_handlers/litellm_ai_handler.py

<li>Added handling for AWS credentials from settings.<br> <li> Removed <code>aws_bedrock_client</code> initialization and usage.<br> <li> Added dummy key for <code>litellm</code> if <code>OPENAI_API_KEY</code> is not in environment.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1022/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfe">+6/-11</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions.py</strong><dd><code>Add conditional prompt selection for Claude model</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_code_suggestions.py

<li>Added conditional prompt selection for Claude model.<br> <li> Updated token handler initialization to use selected prompt.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1022/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117b">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions_prompts.toml</strong><dd><code>Add prompt configuration for Claude model</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_code_suggestions_prompts.toml

<li>Added new prompt configuration for Claude model under <br><code>pr_code_suggestions_prompt_claude</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1022/files#diff-81979f64eddc8f93a5c6ea83ff1e7ba92e551acaecd310c606255161e914c2ea">+99/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Update README with news about Claude 3.5 Sonnet support</code>&nbsp; &nbsp; </dd></summary>
<hr>

README.md

<li>Added news update for July 4, 2024, about Claude 3.5 Sonnet model <br>support.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1022/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5">+4/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
