### PR TITLE
Use lightweight base docker image

### PR DESCRIPTION
**Pull request by yu-iskw**
## Overview

According to my research, it takes about 35 seconds to pull and build the docker image of pr-agent in GitHub Actions. I assume that we can speed up by using a base docker image which is lighter than `python:3.10`. My assumption is to speed up the GitHub Actions' step to prepare for pr-agent using `python:3.10-slim`. If that works as expected, the elapsed time to run a GitHub Actions with pr-agent gets shorter. 

image

___

### **PR Type**
enhancement

___

### **Description**
- Changed the base Docker image from `python:3.10` to `python:3.10-slim` to reduce the image size and potentially speed up the build process.
- Added comments to improve the readability of the Dockerfile.
- Replaced `ADD` with `COPY` for copying files, which is more efficient and clearer in this context.
- Ensured that the entrypoint script is executable, which is crucial for the script to run properly.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Dockerfile.github_action</strong><dd><code>Optimize Dockerfile with a lightweight base image and refactoring</code></dd></summary>
<hr>

Dockerfile.github_action

<li>Changed base image from <code>python:3.10</code> to <code>python:3.10-slim</code> for a lighter <br>build.<br> <li> Added comments for environment variable and installation steps.<br> <li> Used <code>COPY</code> instead of <code>ADD</code> for better clarity and efficiency.<br> <li> Ensured the entrypoint script is executable.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1304/files#diff-e18b685370151a3e574de5890d93010fb040e118f57027f8ce2dc9f64756f365">+15/-6</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by yu-iskw** [comment]
@mrT23 I don't want to bother you, but I would appreciate if you could give your thoughts on the change. Thanks!

**Comment by mrT23** [comment]
Hi @yu-iskw , thanks for the PR

Reducing the docker size is a worthy goal.
Note that this PR: https://github.com/Codium-ai/pr-agent/pull/1306 should reduce 400MB from the docker.

We do get a meaningful reduction in size when moving from `python:3.12` to `python:3.12-slim` (800 MB).
However, I am highly worried that this removes packages that are needed, and that problems will arise for different tools.

On my first test, the slim docker (`current_docker_new`) seems to remove some needed package for Git:

so I tend not to switch to it. chasing after missing packages, only in a GitHub action environment, is not a path I want to go to.

image


image

**Comment by yu-iskw** [comment]
@mrT23 Thank you for the feedback. I totally understand that it would be a bit hassle to purse missing dependencies, though we can automate to check if a built docker image works as expected in GitHub Action. I will close the PR. Again, thanks!

**Comment by mrT23** [comment]
i do like the other changes. The docker looks better and cleaner with them

If you want to merge them in this PR, cool, or I would re-open them in another PR

**Pull request closed without merging**
