### PR TITLE
review with links

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Documentation

___

### **Description**
- Enhanced the `emphasize_header` function to support reference links for both markdown and HTML formats.
- Improved the `convert_to_markdown_v2` function to handle key issues with links, including processing referenced variables.
- Added logging and error handling for processing key issues in markdown conversion.
- Introduced a new configuration option `extra_issue_links` in `configuration.toml`.
- Updated PR reviewer prompts to include examples and support for `extra_issue_links`.
- Modified `_prepare_prediction` and `_prepare_pr_review` methods in `pr_reviewer.py` to support the new settings and enhance diff preparation.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Enhance markdown conversion and header emphasis with links</code></dd></summary>
<hr>

pr_agent/algo/utils.py

<li>Added <code>copy</code> import.<br> <li> Enhanced <code>emphasize_header</code> to support reference links.<br> <li> Improved <code>convert_to_markdown_v2</code> to handle key issues with links.<br> <li> Added logging and error handling for key issues processing.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1040/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+57/-18</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Add extra issue links setting and enhance diff preparation</code></dd></summary>
<hr>

pr_agent/tools/pr_reviewer.py

<li>Added <code>extra_issue_links</code> setting to the PR reviewer.<br> <li> Modified <code>_prepare_prediction</code> to include line numbers in diffs.<br> <li> Updated <code>_prepare_pr_review</code> to pass <code>git_provider</code> to markdown <br>conversion.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1040/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add extra issue links configuration option</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

- Added `extra_issue_links` configuration option.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1040/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer_prompts.toml</strong><dd><code>Update prompts and diff format for extra issue links</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_reviewer_prompts.toml

<li>Updated PR diff format example.<br> <li> Added support for <code>extra_issue_links</code> in prompts.<br> <li> Enhanced key issues to review structure.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1040/files#diff-2e1ca45d2d8635b5f9cde801d9d210f6516e7f15d45dd9b0be134ac91e7a2e63">+58/-14</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1040#issuecomment-2227206143)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/6151bfac25c092e809f779ef80c6477abe4dd8c7

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1040#issuecomment-2227206143)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/6151bfac25c092e809f779ef80c6477abe4dd8c7

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1040#issuecomment-2227206143)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/6151bfac25c092e809f779ef80c6477abe4dd8c7

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1040)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/6151bfac25c092e809f779ef80c6477abe4dd8c7)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1040/files) Tab

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by coditamar** [comment]
/improve
--config.model="claude-3-5-sonnet"

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
