### PR TITLE
Integration of OpenTelemetry for Tracing in PR Agent

### PR DESCRIPTION
**Pull request by nirga**
## PR Type:
Enhancement

___
## PR Description:
This PR integrates OpenTelemetry tracing into the PR Agent application. The integration is done using the Traceloop SDK. Tracing is added to various parts of the application, including the main agent, PR processing, and various tools. A configuration option is also added to enable or disable tracing.

___
## PR Main Files Walkthrough:
`pr_agent/agent/pr_agent.py`: Added initialization of Traceloop for tracing in the PRAgent class. Tracing is enabled based on a configuration setting.
`pr_agent/algo/pr_processing.py`: Added a task decorator from Traceloop to the get_pr_diff function for tracing.
`pr_agent/tools/pr_code_suggestions.py`: Added a workflow decorator from Traceloop to the PRCodeSuggestions class for tracing.
`pr_agent/tools/pr_description.py`: Added a workflow decorator from Traceloop to the PRDescription class for tracing.
`pr_agent/tools/pr_questions.py`: Added a workflow decorator from Traceloop to the PRQuestions class for tracing.
`pr_agent/tools/pr_reviewer.py`: Added a workflow decorator from Traceloop to the PRReviewer class for tracing.
`pr_agent/tools/pr_update_changelog.py`: Added a workflow decorator from Traceloop to the PRUpdateChangelog class for tracing.
`pr_agent/settings/configuration.toml`: Added a new configuration option for enabling or disabling tracing.
`requirements.txt`: Added the Traceloop SDK to the project dependencies.
`pr_agent/settings/.secrets_template.toml`: No significant changes, just a newline removed at the end of the file.

### CODE REVIEW

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
@nirga 
i am worried that traceloop is not suitable for pr-agent.

Users usually work on private data, and wouldn't want their data sent to the cloud.

in addition, the integration is aggressive, and requires adding a decorator above many classes, which would just increase worries for users who do not want their private data being observed.

**Comment by nirga** [comment]
Hey @mrT23 
Thanks for your quick comment! Let me explain first the motivation behind this. I've opened #214 as I wanted to connect traces from runs of PR-Agent to [Honeycomb](https://honeycomb.io). This is why I suggested in #214 that we instrument PR-Agent with [OpenTelemetry](https://opentelemetry.io], which is an open standard for reporting logs, metrics and traces from production systems. The great thing about this standard - the data can be piped to any observability system like Datadog, Sentry, Honeycomb, New Relic and others. 
We're releasing a new open source SDK next month called [OpenLLMetry](https://github.com/traceloop/openllmetry) that extends OpenTelemetry to support instrumentation for LLM calls. We've also built an SDK to make it easy for devs to instrument and use it in their apps - which is what I used here.
The annotations are only there to enrich the traces, and can potentially be removed (though this will reduce the overvall visibility IMO).
So I think the SDK can be super useful to anyone looking to use or develop PR-Agent, similar to other Gen-AI OSS projects that are also adopting OpenLLMetry these days.

I agree that we should turn off the default send-to-cloud option as data indeed may be sensitive, but tbh I thought it's ok as I've seen this is also happening automatically with litellm 😅

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Comment by nirga** [comment]
Preparing pr description...

**Pull request closed without merging**
