### PR TITLE
bitbucket server

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Enhanced the `BitbucketServerProvider` class with new methods like `publish_file_comments` and `get_pr_owner_id`.
- Improved error handling in methods such as `_parse_pr_url` and `_get_pr`.
- Added command processing and sequential execution in `bitbucket_server_webhook.py`.
- Implemented support for connection test in webhook handling.
- Improved logging and error handling in webhook processing.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>bitbucket_server_provider.py</strong><dd><code>Enhance Bitbucket Server Provider with new methods and error handling</code></dd></summary>
<hr>

pr_agent/git_providers/bitbucket_server_provider.py

<li>Added <code>publish_file_comments</code> method.<br> <li> Enhanced <code>_parse_pr_url</code> method with better error handling.<br> <li> Added <code>get_pr_owner_id</code> method.<br> <li> Improved error handling in <code>_get_pr</code> method.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1059/files#diff-c9ca96d14ab7a2935714944f8f377c4a9bb425efde19e66595bb58d33e9f5a40">+38/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>bitbucket_server_webhook.py</strong><dd><code>Enhance Bitbucket Server Webhook handling with command processing</code></dd></summary>
<hr>

pr_agent/servers/bitbucket_server_webhook.py

<li>Added new imports for <code>ast</code>, <code>List</code>, and <code>RedirectResponse</code>.<br> <li> Implemented command processing and sequential execution.<br> <li> Added support for connection test in webhook handling.<br> <li> Improved logging and error handling.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1059/files#diff-ba0834fc2337468d35345ca206434bc48a0894426929d63be442d0793c5d84ba">+77/-6</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by KennyDizi** [comment]
It's such great PR; I've been looking for it for a couple of weeks.

**Comment by mrT23** [comment]
> It's such great PR; I've been looking for it for a couple of weeks.

it pains my eyes to see the words "great" in relation to "bitbucket"
😄

**Comment by KennyDizi** [comment]
> > It's such great PR; I've been looking for it for a couple of weeks.
> 
> it pains my eyes to see the word "great" in relation to "bitbucket" 😄

It's true because Bitbucket is behind compared to GitHub. A lot of EURO companies are using Bitbucket and this PR is very important.

**Comment by mrT23** [comment]
> > > It's such great PR; I've been looking for it for a couple of weeks.
> > 
> > 
> > it pains my eyes to see the word "great" in relation to "bitbucket" 😄
> 
> It's true because Bitbucket is behind compared to GitHub. A lot of EURO companies are using Bitbucket and this PR is very important.

any company that uses Bitbucket will have a disadvantage over its competitors.

**Pull request merged**
