### PR TITLE
fix openai api_base config in litellm_ai_handler.py 

### PR DESCRIPTION
**Pull request by mofanke**
### **PR Type**
Bug fix

___

### **Description**
- Fixed the handling of the OpenAI API base configuration by assigning `api_base` to `self.api_base` in the `litellm_ai_handler.py` file.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>litellm_ai_handler.py</strong><dd><code>Fix OpenAI API base configuration handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/ai_handlers/litellm_ai_handler.py

- Added assignment of `api_base` to `self.api_base` from settings.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1297/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfe">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by mrT23** [comment]
A PR should not be opened without a thorough description explaining its goal.

Give significantly more details. Share examples, and use cases

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by pieapple** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
closing, as no respone to feedback

**Pull request closed without merging**
