### PR TITLE
Use commit messages in PR tools

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Enhancement

___
## PR Description:
This PR updates several tools in the `pr_agent` package to use the commit messages in their functionality. The commit messages are now retrieved and stored in the `vars` dictionary for each tool.

___
## PR Main Files Walkthrough:
- `pr_agent/tools/pr_code_suggestions.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_description.py`: Removed the `commit_messages_str` variable and added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_information_from_user.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_questions.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_reviewer.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_update_changelog.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/settings/pr_code_suggestions_prompts.toml`: Added a section to display the commit messages.
- `pr_agent/settings/pr_information_from_user_prompts.toml`: Added a section to display the commit messages.
- `pr_agent/settings/pr_questions_prompts.toml`: Added a section to display the commit messages.
- `pr_agent/settings/pr_reviewer_prompts.toml`: Added a section to display the commit messages.
- `pr_agent/settings/pr_update_changelog_prompts.toml`: Added a section to display the commit messages.

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing changelog updates...

**Comment by mrT23** [comment]
/update_changelog --pr_update_changelog.push_changelog_changes=true

**Review by okotek — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Analysis

- 🎯 **Main theme:** Enhancement of PR tools by incorporating commit messages
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ✨ **Focused PR:** Yes, the PR is focused as it has a clear and coherent title and description. All the changes in the PR are logically derived from the title and description, which is about enhancing PR tools by incorporating commit messages.
- 🔒 **Security concerns:** No, the PR does not introduce any apparent security concerns. The changes are mainly about retrieving and storing commit messages, which does not involve any sensitive data or operations that could lead to security issues.
## PR Feedback

-  **General suggestions:** The PR is well-structured and the changes are logically consistent with the PR's purpose. However, it would be beneficial to include tests to verify the new functionality. Additionally, consider handling potential exceptions that may occur when retrieving commit messages.

- 🤖 **Code feedback:**


  - **relevant file:** pr_agent/tools/pr_code_suggestions.py
   **suggestion content:** Consider handling potential exceptions that may occur when retrieving commit messages. This can be done by wrapping the `self.git_provider.get_commit_messages()` call in a try-except block and providing an appropriate error message if an exception is thrown. [important]
   **relevant line in file:** ["commit_messages_str": self.git_provider.get_commit_messages(),](https://github.com/Codium-ai/pr-agent/blob/eb143ec851642ae45286d3a1b9dea1fecc1aefe5/pr_agent/tools/pr_code_suggestions.py#L37)


  - **relevant file:** pr_agent/tools/pr_description.py
   **suggestion content:** It's a good practice to keep the initialization of variables close to their usage. In this case, the `commit_messages_str` variable was removed and its value was directly assigned in the `vars` dictionary. This is a good practice as it improves code readability and maintainability. [medium]
   **relevant line in file:** ["commit_messages_str": self.git_provider.get_commit_messages()](https://github.com/Codium-ai/pr-agent/blob/eb143ec851642ae45286d3a1b9dea1fecc1aefe5/pr_agent/tools/pr_description.py#L42)


  - **relevant file:** pr_agent/tools/pr_information_from_user.py
   **suggestion content:** Consider adding a comment explaining the purpose of the `commit_messages_str` key in the `vars` dictionary. This will improve code readability and maintainability. [medium]
   **relevant line in file:** ["commit_messages_str": self.git_provider.get_commit_messages(),](https://github.com/Codium-ai/pr-agent/blob/eb143ec851642ae45286d3a1b9dea1fecc1aefe5/pr_agent/tools/pr_information_from_user.py#L27)

**Pull request merged**
