### PR TITLE
Tr/large pr

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Bug fix, Other

___

### **Description**
- Enhanced the diff generation process to handle large PRs by generating multiple patches and improving token management.
- Improved the handling and logging of code suggestions, including validation and a new method to apply suggestions.
- Added support for large PRs in the description generation, including better token handling and clipping.
- Updated configuration settings to support new features and improve overall PR processing.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_processing.py</strong><dd><code>Enhance diff generation and handling for large PRs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/algo/pr_processing.py

<li>Added <code>large_pr_handling</code> parameter to <code>get_pr_diff</code> function.<br> <li> Implemented logic to handle large PRs by generating multiple patches.<br> <li> Refactored the diff generation logic to improve token handling and <br>patch management.<br> <li> Added a new function <code>get_pr_diff_multiple_patchs</code> for handling multiple <br>patches.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1004/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04e">+186/-94</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions.py</strong><dd><code>Improve code suggestions handling and logging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/tools/pr_code_suggestions.py

<li>Improved logging and error handling.<br> <li> Added validation for suggestion keys.<br> <li> Implemented a new method <code>handle_apply_suggestion</code> to process and apply <br>suggestions.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1004/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117b">+88/-30</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_description.py</strong><dd><code>Add support for large PR handling in descriptions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/tools/pr_description.py

<li>Added support for handling large PRs in the description generation.<br> <li> Implemented logic to generate predictions for multiple patches.<br> <li> Improved token handling and clipping for large PR descriptions.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1004/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb">+103/-23</a></td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Update configuration for large PR handling and suggestions</code></dd></summary>
<hr>
      
pr_agent/settings/configuration.toml

<li>Added new configuration options for handling large PRs.<br> <li> Updated various settings related to PR processing and suggestions.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1004/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+44/-6</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1004)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/11abce3ede5407a294a992f5bf4978ac6ffa0823)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1004/files) Tab

**Review by hussam789 — APPROVED** [review]

**Comment by mrT23** [comment]
/improve
--pr_code_suggestions.num_code_suggestions_per_chunk="5"
--pr_code_suggestions.focus_only_on_problems=false

**Comment by mrT23** [comment]
/improve
--pr_code_suggestions.num_code_suggestions_per_chunk="6"
--pr_code_suggestions.focus_only_on_problems=true

**Pull request merged**
