### PR TITLE
Handling CLI Arguments with Quotes in pr_agent

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Bug fix

___
## PR Description:
This PR introduces a fix for handling command line arguments that contain spaces in the pr_agent. The main changes include:
- Addition of a new function `handle_args_with_quotes` that processes the arguments and adds quotes around arguments that contain spaces.
- Modification of the `run` function to call the new `handle_args_with_quotes` function.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `pr_agent/cli.py`: Added a new function `handle_args_with_quotes` to handle command line arguments with spaces. The `run` function is also updated to use this new function.
</details>

___
## And here's a little programming joke for you:
Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing PR description...

**Review by okotek — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing PR labels...

**Comment by mrT23** [comment]
Preparing PR labels...

**Comment by mrT23** [comment]
Preparing PR labels...

**Pull request merged**
