### PR TITLE
Refactor the function run and _prepare_pr_review of class PRReviewer

### PR DESCRIPTION
**Pull request by ryanzll**
### **User description**
1. split function _prepare_pr_review to several independent functions
2. caching dictionary and markdown style result of pr review, for caller can get and using it in custom way

___

### **PR Type**
Enhancement

___

### **Description**
- Refactored the `_prepare_pr_review` method into two separate methods: `prepare_prediction` and `generate_markdown`.
- Added caching of PR review results (`pr_review_data` and `pr_review_markdown`) for custom usage by the caller.
- Reset `pr_review_data` and `pr_review_markdown` variables at the start of the `run` method.
- Improved logging by adding debug statements for PR review output.
- Enhanced error handling in the `run` method.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Refactor and enhance PR review preparation and execution.</code></dd></summary>
<hr>
      
pr_agent/tools/pr_reviewer.py

<li>Added reset of <code>pr_review_data</code> and <code>pr_review_markdown</code> variables in <code>run</code> <br>method.<br> <li> Refactored <code>_prepare_pr_review</code> into <code>prepare_prediction</code> and <br><code>generate_markdown</code> methods.<br> <li> Cached PR review results for custom usage.<br> <li> Improved logging and error handling.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/956/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+62/-51</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
This is a key function of pr-agent.

"re-ordering" of such a key function is not something we want.

If you have more _specific_, _actionable_ and _limited_ code contributions, feel free to suggestion

**Comment by ryanzll** [comment]
Thanks for your information, and your concern is reasonable.

Is it acceptable to cache data and markdown in PRReviewer, and then get them from caller?
just code in the red box.


if it is ok, I will create a new pr to do this.

**Comment by mrT23** [comment]
> @mrT23 Thanks for your information, and your concern is reasonable.
> 
> Is it acceptable to cache data and markdown in PRReviewer, and then get them from caller? just code in the red box. code
> 
> if it is ok, I will create a new pr to do this.

cache to where ? who should be able to use it ?

**Comment by ryanzll** [comment]
1. it means adding two member variables to class PRReviewer.
2. the scenario is that someone don't want submit comments to git server, will get and use pr result in other ways. So it need to get pr result from PRReviewer.
3. the Caller can get pr result via member variables.

**Comment by mrT23** [comment]
The scenario is too ambiguous, and tailor-made to the `review` tool alone.

It is also unsuited to the way the app works, where we don't have a specific instance of the tool.

The correct way to return a value is via the get_settings() method. It should be done for any tool
Its on my to-do list, but not on high priority

**Comment by ryanzll** [comment]
Great！Look forward to your work.

**Pull request closed without merging**
