### PR TITLE
Tr/show config

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
enhancement

___

### **Description**
- Added a new function `show_relevant_configurations` in `utils.py` to generate markdown text for relevant configurations.
- Integrated this function across multiple tools (`pr_code_suggestions.py`, `pr_description.py`, `pr_reviewer.py`, `pr_update_changelog.py`) to output configurations if the setting is enabled.
- Updated the documentation in `configuration_options.md` to include a tip about how to use the new configuration output feature.
- Added a new configuration option `output_relevant_configurations` in `configuration.toml` to toggle the output of configurations.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Add function to show relevant configurations in markdown</code>&nbsp; </dd></summary>
<hr>
      
pr_agent/algo/utils.py

<li>Added <code>show_relevant_configurations</code> function to generate markdown text <br>with relevant configurations.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/910/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+23/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions.py</strong><dd><code>Integrate configuration output in PR code suggestions tool</code></dd></summary>
<hr>
      
pr_agent/tools/pr_code_suggestions.py

<li>Integrated <code>show_relevant_configurations</code> to output configurations if <br>enabled.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/910/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117b">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_description.py</strong><dd><code>Integrate configuration output in PR description tool</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/tools/pr_description.py

<li>Integrated <code>show_relevant_configurations</code> to output configurations if <br>enabled.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/910/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Integrate configuration output in PR reviewer tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/tools/pr_reviewer.py

<li>Integrated <code>show_relevant_configurations</code> to output configurations if <br>enabled.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/910/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+6/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_update_changelog.py</strong><dd><code>Integrate configuration output in PR update changelog tool</code></dd></summary>
<hr>
      
pr_agent/tools/pr_update_changelog.py

<li>Integrated <code>show_relevant_configurations</code> to output configurations if <br>enabled.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/910/files#diff-76d8133da16132fa69d308bf1e5edb4fc7de18343a4d99760960416c54c79087">+6/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration_options.md</strong><dd><code>Update configuration options documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
docs/docs/usage-guide/configuration_options.md

<li>Updated documentation to include a tip about showing relevant <br>configurations.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/910/files#diff-5b3d743def9f77f0b3ac72c61a3eec1418f87313b285ca3926b196828d8ecc2d">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add setting to toggle relevant configurations output</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/settings/configuration.toml

<li>Added <code>output_relevant_configurations</code> setting to enable/disable <br>configuration output.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/910/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
/custom_prompt
--pr_custom_prompt.prompt="
The suggestions should focus only on the following:
- code smells
- major bugs
- typos
"

**Comment by mrT23** [comment]
## Generating custom prompt suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
/custom_prompt
--pr_custom_prompt.prompt="
The suggestions should focus only on the following:
- code smells
- major bugs
- typos
"

**Comment by mrT23** [comment]
/custom_prompt --pr_custom_prompt.prompt="
The suggestions should focus only on the following:
- code smells
- major bugs
- typos

"

**Comment by mrT23** [comment]
/custom_prompt
--pr_custom_prompt.prompt="The suggestions should focus only on the following:- code smells"

**Comment by mrT23** [comment]
/custom_prompt
--pr_custom_prompt.prompt="The suggestions should focus only on the following:
- code smells
- typos
"

**Comment by mrT23** [comment]
/improve
--pr_code_suggestions.extra_instructions="
Emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
"

**Comment by mrT23** [comment]
/custom_prompt
--pr_custom_prompt.prompt=The suggestions should focus only on the following:
- code smells
- typos

**Comment by mrT23** [comment]
/custom_prompt
--pr_custom_prompt.prompt="The suggestions should focus only on the following:
- code smells
- typos
"

**Comment by mrT23** [comment]
## Generating custom prompt suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
