### PR TITLE
patch and prompt improvements

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Documentation

___

### **Description**
- Enhanced the logic for processing new and old hunks in `convert_to_hunks_with_lines_numbers` function in `git_patch_processing.py`.
- Updated the Docker base image from Python 3.10 to Python 3.12 in `Dockerfile`.
- Improved clarity and added detailed instructions in code suggestion prompts, reflection prompts, and reviewer prompts in respective TOML files.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>git_patch_processing.py</strong><dd><code>Enhance hunk processing logic and code readability</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/git_patch_processing.py

<li>Improved handling of new and old hunks in patch processing.<br> <li> Added checks for presence of '+' and '-' lines before appending hunks.<br> <li> Fixed formatting issues and improved code readability.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1091/files#diff-c5a7f9db4adbcf394c7855f6da656c073d5a6bcc18bd6dede44a8207893174b8">+26/-19</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Dockerfile</strong><dd><code>Update Docker base image to Python 3.12</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docker/Dockerfile

- Updated base image from Python 3.10 to Python 3.12.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1091/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions_prompts.toml</strong><dd><code>Improve code suggestion prompts and field descriptions</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_code_suggestions_prompts.toml

<li>Improved clarity of code suggestion prompts.<br> <li> Added instructions for handling hunks with no new or removed code.<br> <li> Enhanced field descriptions for better understanding.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1091/files#diff-81979f64eddc8f93a5c6ea83ff1e7ba92e551acaecd310c606255161e914c2ea">+13/-11</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions_reflect_prompts.toml</strong><dd><code>Enhance code suggestion reflection prompts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_code_suggestions_reflect_prompts.toml

<li>Improved clarity of code suggestion reflection prompts.<br> <li> Added instructions for handling hunks with no new or removed code.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1091/files#diff-aeee2207a4afb3ea3368c3e0140629bb3da8858b6d2315db5778661c9390d144">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer_prompts.toml</strong><dd><code>Improve PR reviewer prompts and instructions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_reviewer_prompts.toml

<li>Improved clarity of PR reviewer prompts.<br> <li> Added instructions for handling hunks with no new or removed code.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1091/files#diff-2e1ca45d2d8635b5f9cde801d9d210f6516e7f15d45dd9b0be134ac91e7a2e63">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by pc-bob** [comment]
@mrT23 can we get a new docker image published with these changes? this would address https://github.com/Codium-ai/pr-agent/issues/1086

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Pull request merged**
