### PR TITLE
Enhancements and Bug Fixes in Code Suggestions and Line Link Generation

### PR DESCRIPTION
**Pull request by mrT23**
## type:
enhancement, bug_fix

___
## description:
This PR introduces several enhancements and bug fixes:
- A new feature to summarize code suggestions for better readability and compactness.
- Line link generation for GitHub and GitLab to directly link to the relevant lines in the PR.
- Improved markdown formatting for code feedback sections.
- Fixed GitLab capability check for gfm_markdown support.
- Updated temporary comment text from "Preparing review..." to "Preparing suggestions..." for clarity.
- Added a new configuration option `summarize` in `pr_code_suggestions` to toggle summary view of code suggestions.

___
## main_files_walkthrough:
<details> <summary>files:</summary>

- `pr_agent/algo/utils.py`: Refactored the markdown generation for code feedback to support GitHub Flavored Markdown (GFM). Adjusted the markdown formatting for 'relevant file' and 'sub_key' entries to ensure proper display.
- `pr_agent/git_providers/git_provider.py`: Added an abstract method `get_line_link` to generate a URL to the relevant lines in the PR.
- `pr_agent/git_providers/github_provider.py`: Implemented the `get_line_link` method to generate GitHub-specific links to code diffs in PRs.
- `pr_agent/git_providers/gitlab_provider.py`: Corrected the capability check for GitLab to reflect that it does support GFM. Implemented the `get_line_link` method to generate GitLab-specific links to code diffs in PRs.
- `pr_agent/tools/pr_code_suggestions.py`: Changed the temporary comment text to better reflect the action being performed. Added logic to publish a summary of code suggestions if the `summarize` configuration is set to true.
- `pr_agent/tools/pr_reviewer.py`: Fixed markdown formatting for the instructions summary in PR reviews.
- `pr_agent/settings/configuration.toml`: Introduced a new configuration option `summarize` to toggle the summary view of code suggestions.
</details>

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/476#issuecomment-1826802723)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/8f615e17a3fe0146ea4502d9b1ecf111dc09036d

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
## Code Suggestions

📌 File:

[pr_agent/algo/utils.py (61-62)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53R61-R62)

Suggestion:

**Combine consecutive string concatenations into a single statement to improve readability.**

<details> <summary> Example code:</summary>

___

Existing code:
```python
markdown_text += f"\n\n- "
markdown_text += f"<details><summary> { emoji } Code feedback:</summary>\n\n"
```
Improved code:
```python
markdown_text += f"\n\n- <details><summary> { emoji } Code feedback:</summary>\n\n"
```
</details>

___

📌 File:

[pr_agent/git_providers/github_provider.py (507-510)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11R507-R510)

Suggestion:

**Use string interpolation only once by combining the URL into a single f-string to improve performance.**

<details> <summary> Example code:</summary>

___

Existing code:
```python
if relevant_line_end:
    link = f"https://github.com/{self.repo}/pull/{self.pr_num}/files#diff-{sha_file}R{relevant_line_start}-R{relevant_line_end}"
else:
    link = f"https://github.com/{self.repo}/pull/{self.pr_num}/files#diff-{sha_file}R{relevant_line_start}"
```
Improved code:
```python
link = f"https://github.com/{self.repo}/pull/{self.pr_num}/files#diff-{sha_file}R{relevant_line_start}" + (f"-R{relevant_line_end}" if relevant_line_end else "")
```
</details>

___

📌 File:

[pr_agent/git_providers/gitlab_provider.py (46-46)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-35acba7a2829983fcf3c3c6a69b135988227e503ccdfa94366d1b48fcbbb0a31R46-R46)

Suggestion:

**Correct the capability list to include 'gfm_markdown' as it is supported in GitLab.**

<details> <summary> Example code:</summary>

___

Existing code:
```python
if capability in ['get_issue_comments', 'create_inline_comment', 'publish_inline_comments']: # gfm_markdown is supported in gitlab !
    return False
```
Improved code:
```python
if capability in ['get_issue_comments', 'create_inline_comment', 'publish_inline_comments', 'gfm_markdown']:
    return False
```
</details>

___

📌 File:

[pr_agent/tools/pr_code_suggestions.py (271-272)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117bR271-R272)

Suggestion:

**Refactor the exception handling to log the exception message and stack trace for better debugging.**

<details> <summary> Example code:</summary>

___

Existing code:
```python
except Exception as e:
    get_logger().info(f"Failed to publish summarized code suggestions, error: {e}")
```
Improved code:
```python
except Exception as e:
    get_logger().error("Failed to publish summarized code suggestions", exc_info=True)
```
</details>

___

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
## Code Suggestions


📌 Suggestion:

**Correct the capability check to return True for 'gfm_markdown' as it is supported in GitLab.**

 File: [pr_agent/git_providers/gitlab_provider.py (46-47)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-35acba7a2829983fcf3c3c6a69b135988227e503ccdfa94366d1b48fcbbb0a31R46-R47)
<details> <summary> Example code:</summary>

___

Existing code:
```python
if capability in ['get_issue_comments', 'create_inline_comment', 'publish_inline_comments']: # gfm_markdown is supported in gitlab !
    return False
```
Improved code:
```python
if capability in ['get_issue_comments', 'create_inline_comment', 'publish_inline_comments']:
    return True
```
</details>

___


📌 Suggestion:

**Use a more specific exception handling instead of a general one.**

 File: [pr_agent/tools/pr_code_suggestions.py (271-272)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117bR271-R272)
<details> <summary> Example code:</summary>

___

Existing code:
```python
except Exception as e:
    get_logger().info(f"Failed to publish summarized code suggestions, error: {e}")
```
Improved code:
```python
except SpecificException as e:  # Replace SpecificException with the specific exception you expect
    get_logger().info(f"Failed to publish summarized code suggestions, error: {e}")
```
</details>

___


📌 Suggestion:

**Use a more descriptive variable name instead of `sha_file` for clarity.**

 File: [pr_agent/git_providers/github_provider.py (506-506)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11R506-R506)
<details> <summary> Example code:</summary>

___

Existing code:
```python
sha_file = hashlib.sha256(relevant_file.encode('utf-8')).hexdigest()
```
Improved code:
```python
file_hash = hashlib.sha256(relevant_file.encode('utf-8')).hexdigest()
```
</details>

___


📌 Suggestion:

**Correct the markdown for the details tag to properly format the summary.**

 File: [pr_agent/tools/pr_reviewer.py (253-253)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dcR253-R253)
<details> <summary> Example code:</summary>

___

Existing code:
```python
markdown_text += "\n <details> <summary> Instructions</summary>\n\n"
```
Improved code:
```python
markdown_text += "\n<details><summary>Instructions</summary>\n\n"
```
</details>

___


📌 Suggestion:

**Remove unnecessary import of `difflib` if it's not used in the file.**

 File: [pr_agent/tools/pr_code_suggestions.py (4-4)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117bR4-R4)
<details> <summary> Example code:</summary>

___

Existing code:
```python
import difflib
```
Improved code:
```python
# import difflib (removed because it's not used)
```
</details>

___


📌 Suggestion:

**Update the log message to match the action being performed.**

 File: [pr_agent/tools/pr_code_suggestions.py (60-60)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117bR60-R60)
<details> <summary> Example code:</summary>

___

Existing code:
```python
get_logger().info('Preparing PR code suggestions...')
```
Improved code:
```python
get_logger().info('Preparing code suggestions for PR...')
```
</details>

___


📌 Suggestion:

**Ensure consistent indentation for markdown generation.**

 File: [pr_agent/algo/utils.py (103-105)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53R103-R105)
<details> <summary> Example code:</summary>

___

Existing code:
```python
if "relevant file" in sub_key.lower():
    markdown_text += f"\n  - **{sub_key}:** {sub_value}  \n"
else:
    markdown_text += f"   **{sub_key}:** {sub_value}  \n"
```
Improved code:
```python
if "relevant file" in sub_key.lower():
    markdown_text += f"\n  - **{sub_key}:** {sub_value}\n"
else:
    markdown_text += f"    **{sub_key}:** {sub_value}\n"
```
</details>

___

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
## PR Code Suggestions


💡 Suggestion:

**Ensure consistent markdown formatting by adding a space after the hyphen for list items.**

 File: [pr_agent/algo/utils.py (61-62)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53R61-R62)

<details> <summary> Example code:</summary>

___

Existing code:
```python
markdown_text += f"\n\n- "
markdown_text += f"<details><summary> { emoji } Code feedback:</summary>\n\n"
```
Improved code:
```python
markdown_text += f"\n\n- <details><summary> { emoji } Code feedback:</summary>\n\n"
```
</details>

___


💡 Suggestion:

**The `get_line_link` method in Bitbucket provider should handle the case when `relevant_line_end` is provided.**

 File: [pr_agent/git_providers/bitbucket_provider.py (231-233)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-3f47323db85f534fa282b2d48c6cf542f00a5e791b62379253ef3d3e8c6bb3b2R231-R233)

<details> <summary> Example code:</summary>

___

Existing code:
```python
def get_line_link(self, relevant_file: str, relevant_line_start: int, relevant_line_end: int = None) -> str:
    link = f"{self.pr_url}/#L{relevant_file}T{relevant_line_start}"
    return link
```
Improved code:
```python
def get_line_link(self, relevant_file: str, relevant_line_start: int, relevant_line_end: int = None) -> str:
    link = f"{self.pr_url}/#L{relevant_file}T{relevant_line_start}"
    if relevant_line_end:
        link += f"-L{relevant_line_end}"
    return link
```
</details>

___


💡 Suggestion:

**Correct the capability check for GitLab to include 'gfm_markdown' as a supported feature.**

 File: [pr_agent/git_providers/gitlab_provider.py (46-47)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-35acba7a2829983fcf3c3c6a69b135988227e503ccdfa94366d1b48fcbbb0a31R46-R47)

<details> <summary> Example code:</summary>

___

Existing code:
```python
if capability in ['get_issue_comments', 'create_inline_comment', 'publish_inline_comments']: # gfm_markdown is supported in gitlab !
    return False
```
Improved code:
```python
if capability in ['get_issue_comments', 'create_inline_comment', 'publish_inline_comments', 'gfm_markdown']:
    return True
return False
```
</details>

___


💡 Suggestion:

**Add error logging for the `publish_summarizes_suggestions` method to provide more detailed information about exceptions.**

 File: [pr_agent/tools/pr_code_suggestions.py (271-271)](https://github.com/Codium-ai/pr-agent/pull/476/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117bR271-R271)

<details> <summary> Example code:</summary>

___

Existing code:
```python
except Exception as e:
    get_logger().info(f"Failed to publish summarized code suggestions, error: {e}")
```
Improved code:
```python
except Exception as e:
    get_logger().error(f"Failed to publish summarized code suggestions, error: {e}", exc_info=True)
```
</details>

___

**Comment by mrT23** [comment]
Preparing PR description...

**Review by okotek — APPROVED** [review]

**Comment by okotek** [comment]
/ask where should the images in this PR be stored?

**Pull request merged**
