### PR TITLE
Fix `get_user_description` in case `pr_description.enable_pr_type=false`

### PR DESCRIPTION
**Pull request by zmeir**
Fixes an issue when getting the user description after a PR-Agent description was already generated, in case the configuration setting `pr_description.enable_pr_type` was `false`.

### CODE REVIEW

**Review by barnett-yuxiang — COMMENTED** [review]
No Unit Test code submitted?

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Analysis

- 🎯 **Main theme:** Fixing the method `get_user_description` to correctly handle cases when `pr_description.enable_pr_type` is set to `false`.
- 📝 **PR summary:** This PR addresses a bug in the `get_user_description` method of the `git_provider.py` file. The bug caused incorrect behavior when the configuration setting `pr_description.enable_pr_type` was set to `false`. The fix involves changing the condition that checks the start of the description.
- 📌 **Type of PR:** Bug fix
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 1, because the PR is small and the change is straightforward.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** The change seems to be addressing the issue correctly. However, it would be beneficial to add tests to verify the correct behavior of the `get_user_description` method in different scenarios.


- **<details><summary> 🤖 Code feedback:**</summary>


  - **relevant file:** ``pr_agent/git_providers/git_provider.py``
   **suggestion:** Consider using a constant to store the headers ("## PR Type", "## PR Description") instead of hardcoding them in the condition. This would make the code more maintainable and less prone to errors. [medium]
   **relevant line:** [if not any(description.startswith(header) for header in ("## PR Type", "## PR Description")):](https://github.com/Codium-ai/pr-agent/pull/449/files#diff-52d45f12b836f77ed1aef86e972e65404634ea4e2a6083fb71a9b0f9bb9e062fR110)

</details>

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/449#issuecomment-1812453074)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/7d89b829670a5667e90b1061bf1925ede2fd6427

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Pull request merged**
