### PR TITLE
feat: add support for O1 model by combining system and user prompt

### PR DESCRIPTION
**Pull request by mrT23**
fixes https://github.com/Codium-ai/pr-agent/issues/1278

### **PR Type**
enhancement

___

### **Description**
- Added support for the O1 model in the `litellm_ai_handler` by combining system and user prompts into a single user prompt.
- Implemented conditional logic to adjust the message structure when using the O1 model, which does not support separate system and user prompts.
- Updated the `kwargs` dictionary to accommodate the new message structure for the O1 model.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>litellm_ai_handler.py</strong><dd><code>Add support for O1 model in chat completion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/ai_handlers/litellm_ai_handler.py

<li>Added support for O1 model by combining system and user prompts.<br> <li> Adjusted message structure for O1 model compatibility.<br> <li> Introduced conditional logic to handle O1 model specifics.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1279/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfe">+23/-8</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by hussam789 — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Reviewer Guide 🔍

Here are some key observations to aid the review process:

<table>
<tr><td>

**🎫 Ticket compliance analysis ✅**



**[1278](https://github.com/Codium-ai/pr-agent/issues/1278) - Fully compliant**

Fully compliant requirements:
- Support new OpenAI models (o1-mini/o1-preview)
- Fix the error related to unsupported 'system' role in messages for these models



</td></tr>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 2 🔵🔵⚪⚪⚪</td></tr>
<tr><td>🏅&nbsp;<strong>Score</strong>: 95</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>🔀 <strong>No multiple PR themes</strong>

</td></tr>
<tr><td>⚡&nbsp;<strong>Recommended focus areas for review</strong><br><br>

<a href='https://github.com/Codium-ai/pr-agent/pull/1279/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfeR189-R195'><strong>Error Handling</strong></a><br>The PR adds new logic for O1 models but doesn't include specific error handling for potential issues that might arise from this change.

</td></tr>
</table>

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1279#issuecomment-2404042130)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/e6c56c7355acd5ad64fc97d80ecd2d9d8f4f6f3d

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1279)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/e6c56c7355acd5ad64fc97d80ecd2d9d8f4f6f3d)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1279/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1279)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/e6c56c7355acd5ad64fc97d80ecd2d9d8f4f6f3d)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1279/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1279)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/e6c56c7355acd5ad64fc97d80ecd2d9d8f4f6f3d)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/1279/files) Tab

**Pull request merged**
