### PR TITLE
Automatically enable `/improve --extended` mode for large PRs

### PR DESCRIPTION
**Pull request by zmeir**
## Type
Enhancement

___

## Description
- Introduced a feature that automatically enables extended mode for large PRs. This is determined by the number of files, additions, and deletions in the PR.
- Modified the logic for reducing the number of suggestions, ensuring it doesn't go below a certain threshold.
- Updated the documentation and configuration file to include the new parameters for automatically enabling extended mode for large PRs and their default values.

___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/tools/pr_code_suggestions.py<br><br>

**The PR introduces a new feature that automatically enables <br>extended mode for large PRs. This is determined by the <br>number of files, additions, and deletions in the PR. The PR <br>also modifies the logic for reducing the number of <br>suggestions, ensuring it doesn't go below a certain <br>threshold.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/564/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117b"> +24/-3</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>IMPROVE.md&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        docs/IMPROVE.md<br><br>

**The PR updates the documentation to include the new <br>parameters for automatically enabling extended mode for <br>large PRs. It also provides default values for these <br>parameters.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/564/files#diff-c5fc63e45a597a7f6a34800dfff364ab2a4052648308fe63e070f3e5befda275"> +4/-0</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/settings/configuration.toml<br><br>

**The PR updates the configuration file to include the new <br>parameters for automatically enabling extended mode for <br>large PRs and their default values.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/564/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78"> +4/-0</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

## User description
Thought it could be nice to add an option to allow the `/improve` command to automatically run with `--extended` mode based on the size of the PR (number of files/additions/deletions)

### CODE REVIEW

**Comment by mrT23** [comment]
@zmeir i am not sure about the need specific PR.
I recommend always using '/improve --extended'.
If the PR is below 8000 tokens, it will make a single call. Only if needed, it will make extra calls, and they will be according the extra tokens needed.

So the command itself is already "automatic", according to the correct input - the number of tokens

Can you elaborate why do we need extra logic beyond the original one ?
Or maybe the correct question is - should 'extended' mode be the default ?

**Comment by zmeir** [comment]
> @zmeir i am not sure about the need of this specific PR.
> 
> I recommend always using '/improve --extended'. If the PR is below 8000 tokens, it will make a single call. Only if needed, it will make extra calls, and they will be according the extra tokens needed.
> 
> So the command itself is already "automatic", according to the correct input - the number of tokens
> 
> Can you elaborate why do we need extra logic beyond the original one ? Or maybe the correct question is - why is the 'extended' mode not the default ?

I think it comes down to usability and cost.

From manager's perspective, you might not want to control the cost of using the `/improve` command. If you disable the extended mode (or set a very high threshold to activate it), you know it's just 1 API call. You might even want for even large PRs to only incur 1 API call "by default", and only use the extended mode for specific cases.

However, from a user's perspective, I don't really want to care about the difference, I just want to best results and the simplest usage. So ideally I only want to run `/improve` and have it use the best strategy according to whatever the algorithmic and monetary constraints may be.

So to your question why the extended mode is not the default, I think this what I was aiming for with this PR - if this is what you want you can set the thresholds to 0 and it will always run with extended mode. But I wanted to still leave some wiggle room in case you're concerned about the extra calls.

I hope that answers your questions.

I should also note that in the extended mode you have some extra logic for clipping some percentage of the suggestions that will result in fewer suggestions than the normal mode, if there was only one call and it produced fewer than the max number of suggestions. This is another part of this PR - I can separate it if you'd like.

**Comment by zmeir** [comment]
To simplify my previous response: I'm a lazy user that wants to type fewer characters, so I want to type `/improve` instead of `/improve --extended`. There was no configuration to allow that so I added the `auto_extended_mode`. The rest of the thresholds are just added because I could and I wanted to give more control if anyone wants it, but as you said they can all just be 0 and the extended mode will always be the default.

**Comment by mrT23** [comment]
@zmeir
I am not at peace with this specific PR.

It contains a lot of magic numbers, that are hard to tune or understand their meaning, and how they will impact the results.
In contrast,  the 'extended' mode as-is already uses the optimal tradeof parameter - number of tokens, which strikes the correct balance between the number of calls (I.e. cost) to quality.

Also notice you can always lower the number of possible tokens per model call, and it will give you a similar effect what you talked about, yet in a more controlled, manner and still using a single parameter.

Maybe the default option should just be to enable the 'extended' mode.
(with or without clipping, with or without ranking). But i want to avoid magic numbers, hard to understand their impact.

**Comment by zmeir** [comment]
@mrT23 that makes perfect sense, thanks for the explanation.

I made a simpler version of this PR with just the `auto_extended_mode` toggle and what I believe is a fix for the clipping logic - let me know what you think: https://github.com/Codium-ai/pr-agent/pull/569

**Pull request merged**
