### PR TITLE
Making the 'Review' Feature Great Again

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Refactoring

___
## PR Description:
This PR introduces changes to the PR review process. It adds a new function to find the line number of a relevant line in a file, and refactors the code to use this function. It also changes the term 'Code suggestions' to 'Code feedback' and adjusts the handling of code feedback in the review process. Additionally, it includes minor changes to the configuration and prompt files.

___
## PR Main Files Walkthrough:
-`pr_agent/algo/pr_processing.py`: Added a new function `find_line_number_of_relevant_line_in_file` to find the line number of a relevant line in a file. This function is used in the review process to provide more specific feedback.
-`pr_agent/algo/utils.py`: Changed the term 'Code suggestions' to 'Code feedback' and adjusted the handling of code feedback in the markdown conversion and JSON fixing functions.
-`pr_agent/git_providers/github_provider.py`: Refactored the code to use the new `find_line_number_of_relevant_line_in_file` function. Also added a new function `generate_link_to_relevant_line_number` to generate a link to a specific line number in the PR.
-`pr_agent/tools/pr_reviewer.py`: Adjusted the preparation of the PR review and the publishing of inline code comments to handle the changes in the term 'Code suggestions' to 'Code feedback'.
-`pr_agent/settings/configuration.toml`: Changed the number of code suggestions and the setting for inline code comments.
-`pr_agent/settings/pr_reviewer_prompts.toml`: Adjusted the prompts for the PR reviewer to reflect the changes in the term 'Code suggestions' to 'Code feedback'.

## Human feedback:
see example in
https://github.com/Codium-ai/pr-agent/pull/175#issuecomment-1666726162

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Analysis

- 🎯 **Main theme:** Refactoring the PR review process
- 📌 **Type of PR:** Refactoring
- 🧪 **Relevant tests added:** No
- ✨ **Focused PR:** Yes, because all changes are related to improving the PR review process, including changes in terminology, handling of code feedback, and addition of new functions to enhance the review process.
- 🔒 **Security concerns:** No, because the changes made in this PR do not involve any operations that could potentially introduce security vulnerabilities, such as handling user input, database operations, or network communications.
## PR Feedback

-  **General suggestions:** The PR is well-structured and the changes made are relevant to the PR's theme. However, it would be beneficial to add tests to ensure the new functions work as expected. Additionally, consider handling exceptions more specifically rather than catching all exceptions, which can make debugging more difficult.

- 🤖 **Code feedback:**


  - **relevant file:** pr_agent/algo/pr_processing.py
   **suggestion:** Consider handling exceptions more specifically in the `retry_with_fallback_models` function. Catching all exceptions can make debugging more difficult and may hide underlying issues. [important]
   **relevant line:** except Exception as e:


  - **relevant file:** pr_agent/algo/pr_processing.py
   **suggestion:** In the `find_line_number_of_relevant_line_in_file` function, there is a repeated block of code for finding the position of a line in the patch. This could be refactored into a separate function to avoid code duplication. [important]
   **relevant line:** [for i, line in enumerate(patch_lines):](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04eR233)


  - **relevant file:** pr_agent/algo/utils.py
   **suggestion:** In the `try_fix_json` function, the `closing_bracket` variable is only used if `code_suggestions` is true. Consider moving the declaration of `closing_bracket` inside the if statement to limit its scope. [medium]
   **relevant line:** closing_bracket = ']}'

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Analysis

- 🎯 **Main theme:** Refactoring the PR review process
- 📌 **Type of PR:** Refactoring
- 🧪 **Relevant tests added:** No
- ✨ **Focused PR:** Yes, because all changes are related to improving the PR review process, including changes in function naming, handling of code feedback, and adjustments in configuration and prompt files.
- 🔒 **Security concerns:** No, because the PR does not introduce changes that would affect the security of the application, such as handling user input, database operations, or network requests.
## PR Feedback

-  **General suggestions:** The refactoring changes in this PR are well-structured and seem to improve the PR review process. However, it would be beneficial to add tests for the new functions and changes to ensure they work as expected.

- 🤖 **Code feedback:**


  - **relevant file:** pr_agent/algo/pr_processing.py
   **suggestion:** Consider using a more efficient method to find the line number of a relevant line in a file. The current implementation uses a nested for loop which can be costly in terms of performance for large files. A more efficient approach could be to use a data structure like a dictionary to map line numbers to lines, which would allow for constant time lookups [important].
   **relevant line:** [def find_line_number_of_relevant_line_in_file(diff_files: list[FilePatchInfo], relevant_file: str,](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04eR222)


  - **relevant file:** pr_agent/algo/utils.py
   **suggestion:** The `try_fix_json` function seems to be complex and might be simplified. Consider breaking it down into smaller, more manageable functions [medium].
   **relevant line:** [def try_fix_json(review, max_iter=10, code_suggestions=False):](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53R99)


  - **relevant file:** pr_agent/git_providers/github_provider.py
   **suggestion:** The `generate_link_to_relevant_line_number` function could benefit from error handling for the case where the `find_line_number_of_relevant_line_in_file` function returns -1 for `absolute_position`. Currently, it seems that the function would still attempt to generate a link in this case, which could lead to incorrect results [important].
   **relevant line:** [def generate_link_to_relevant_line_number(self, suggestion) -> str:](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11R376)

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Analysis

- 🎯 **Main theme:** Refactoring the PR review process
- 📌 **Type of PR:** Refactoring
- 🧪 **Relevant tests added:** No
- ✨ **Focused PR:** Yes, because all the changes are related to improving the PR review process
- 🔒 **Security concerns:** No, because the changes in this PR do not seem to introduce any new interactions with external systems or handle any sensitive data
## PR Feedback

-  **General suggestions:** The PR makes several improvements to the PR review process, including better handling of code feedback and more precise line number identification. However, it would be beneficial to add tests for the new functions to ensure they work as expected.

- 🤖 **Code feedback:**


  - **relevant file:** pr_agent/algo/pr_processing.py
   **suggestion:** Consider refactoring the `find_line_number_of_relevant_line_in_file` function to reduce its complexity and improve readability. This function is quite long and does a lot of things, which can make it hard to understand and maintain. You could break it down into smaller, more manageable functions. [important]
   **relevant line:** [def find_line_number_of_relevant_line_in_file(diff_files: list[FilePatchInfo], relevant_file: str,](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04eR223)


  - **relevant file:** pr_agent/algo/utils.py
   **suggestion:** The `try_fix_json` function seems to be handling multiple responsibilities. It might be beneficial to split this function into smaller ones, each handling a specific task. This would improve the readability and maintainability of the code. [medium]
   **relevant line:** [def try_fix_json(review, max_iter=10, code_suggestions=False):](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53R99)


  - **relevant file:** pr_agent/git_providers/github_provider.py
   **suggestion:** The `generate_link_to_relevant_line_number` function could benefit from error handling. Currently, if an exception is thrown, it's logged and the function returns an empty string. It might be better to handle specific exceptions and provide more informative error messages. [medium]
   **relevant line:** [def generate_link_to_relevant_line_number(self, suggestion) -> str:](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11R376)

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Analysis

- 🎯 **Main theme:** Refactoring the PR review process
- 📌 **Type of PR:** Refactoring
- 🧪 **Relevant tests added:** Yes
- ✨ **Focused PR:** Yes, the PR is focused as it primarily deals with refactoring the PR review process, introducing a new function to find the line number of a relevant line in a file, and changing the term 'Code suggestions' to 'Code feedback'. All changes are related to this theme.
- 🔒 **Security concerns:** No, the PR does not introduce any obvious security concerns.
## PR Feedback

-  **General suggestions:** The PR is well-structured and the changes are well-documented. The new function `find_line_number_of_relevant_line_in_file` is a good addition and the renaming of 'Code suggestions' to 'Code feedback' is more appropriate. However, there are a few areas that could be improved for better code quality and readability.

- 🤖 **Code feedback:**


  - **relevant file:** pr_agent/algo/pr_processing.py
   **suggestion:** The function `find_line_number_of_relevant_line_in_file` is quite long and complex. Consider breaking it down into smaller, more manageable functions. This will improve readability and maintainability. [important]
   **relevant line:** [def find_line_number_of_relevant_line_in_file(diff_files: List[FilePatchInfo],](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04eR223)


  - **relevant file:** pr_agent/tools/pr_reviewer.py
   **suggestion:** The `if` condition in line 179 is quite complex and hard to read. Consider simplifying it or breaking it down for better readability. [medium]
   **relevant line:** [if 'Code feedback' in pr_feedback:](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dcR178)


  - **relevant file:** pr_agent/git_providers/github_provider.py
   **suggestion:** The function `generate_link_to_relevant_line_number` could benefit from error handling. Consider adding a try-except block to handle potential exceptions that might occur when generating the link. [medium]
   **relevant line:** [def generate_link_to_relevant_line_number(self, suggestion) -> str:](https://github.com/Codium-ai/pr-agent/pull/175/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11R376)

**Review by okotek — APPROVED** [review]

**Pull request merged**
