### PR TITLE
Tr/claude3

### PR DESCRIPTION
**Pull request by mrT23**
image

## **Type**
enhancement, bug_fix

___

## **Description**
- Added support for the `anthropic/claude-3-opus-20240229` model in the AI model configuration.
- Implemented command execution functionality for the Bitbucket app, allowing for dynamic command execution based on PR events.
- Refactored error handling in `litellm_ai_handler.py` by removing `TryAgain` exception usage.
- Updated documentation to include instructions for configuring Anthropic models and the new `pr_commands` feature for Bitbucket app.
- Updated `configuration.toml` to demonstrate the use of `pr_commands` for Bitbucket app.
- Upgraded `litellm` and `openai` dependencies to newer versions.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add Support for Anthropic Claude-3 Model</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/algo/__init__.py

<li>Added support for the <code>anthropic/claude-3-opus-20240229</code> model with a <br>token limit of 100000.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/746/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692b">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>bitbucket_app.py</strong><dd><code>Implement Command Execution Functionality for Bitbucket App</code></dd></summary>
<hr>
      
pr_agent/servers/bitbucket_app.py

<li>Added <code>update_settings_from_args</code> function call to update settings based <br>on command arguments.<br> <li> Implemented <code>_perform_commands_bitbucket</code> to execute configured commands <br>for Bitbucket PRs.<br> <li> Modified webhook handler to support new command execution logic based <br>on <code>pr_commands</code> configuration.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/746/files#diff-963a9de391ff22ad3083c3a28c1d5736d68a6e1e40b0bedb52d4bfd124325bad">+32/-12</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Bug_fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>litellm_ai_handler.py</strong><dd><code>Refactor Error Handling and Remove Detailed Docstring</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/algo/ai_handlers/litellm_ai_handler.py

<li>Commented out import statement for <code>TryAgain</code> from <code>openai.error</code>.<br> <li> Removed the <code>TryAgain</code> exception from the retry decorator and the <br>exception handling.<br> <li> Removed detailed docstring for <code>chat_completion</code> method.<br> <li> Changed the exception raised from <code>TryAgain</code> to <code>APIError</code> when the <br>response is None or empty.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/746/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfe">+6/-24</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Usage.md</strong><dd><code>Update Documentation for Bitbucket App Configuration and Anthropic </code><br><code>Models Support</code></dd></summary>
<hr>
      
Usage.md

<li>Updated documentation to reflect new <code>pr_commands</code> configuration for <br>Bitbucket app.<br> <li> Added documentation for configuring Anthropic models.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/746/files#diff-98bbb2166f184dd69bb689271547bf3414ce37f682b1f51bd0efdb8b565ce99d">+21/-12</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Update Configuration for Bitbucket App Command Execution</code>&nbsp; </dd></summary>
<hr>
      
pr_agent/settings/configuration.toml

- Added `pr_commands` configuration for Bitbucket app.

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/746/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+4/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Upgrade Dependencies `litellm` and `openai`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
requirements.txt

<li>Upgraded <code>litellm</code> to version 1.29.1.<br> <li> Upgraded <code>openai</code> to version 1.13.3.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/746/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by okotek — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/746#issuecomment-1980165011)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/26fb2a416448e9b7ee8b8077ddc268ad12d9fb7c

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Review

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

4, due to the complexity and variety of changes across multiple files, including model support addition, error handling refactoring, dynamic command execution, and dependency upgrades. Understanding the impact of these changes requires a deep understanding of the existing codebase and the functionalities being modified or added.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> 🔍&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The removal of `TryAgain` exception handling in `litellm_ai_handler.py` without a clear replacement might lead to unhandled error scenarios that were previously retried. This could affect the robustness of the error handling mechanism.</td></tr>
<tr>
<td>

<strong>Performance Concern:</strong> The dynamic command execution feature in `bitbucket_app.py` introduces additional complexity and potential performance overhead, especially if the commands list grows or if the commands themselves are resource-intensive.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
<tr><td rowspan=5> 🔀&nbsp;<strong>Can this PR be split?</strong></td>
<td><details><summary>
Sub PR theme: <strong>Add Support for Anthropic Claude-3 Model</strong></summary>

<hr>
Relevant files:
<ul>
<li>pr_agent/algo/__init__.py</li>
<li>Usage.md</li>
</ul>

</details></td></tr>
<tr>
<td><details><summary>
Sub PR theme: <strong>Refactor Error Handling in litellm_ai_handler</strong></summary>

<hr>
Relevant files:
<ul>
<li>pr_agent/algo/ai_handlers/litellm_ai_handler.py</li>
</ul>

</details></td></tr>
<tr>
<td><details><summary>
Sub PR theme: <strong>Implement Dynamic Command Execution for Bitbucket App</strong></summary>

<hr>
Relevant files:
<ul>
<li>pr_agent/servers/bitbucket_app.py</li>
</ul>

</details></td></tr>
<tr>
<td><details><summary>
Sub PR theme: <strong>Update Documentation and Configuration Examples</strong></summary>

<hr>
Relevant files:
<ul>
<li>Usage.md</li>
<li>pr_agent/settings/configuration.toml</li>
</ul>

</details></td></tr>
<tr>
<td><details><summary>
Sub PR theme: <strong>Upgrade Dependencies</strong></summary>

<hr>
Relevant files:
<ul>
<li>requirements.txt</li>
</ul>

</details></td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>pr_agent/algo/ai_handlers/litellm_ai_handler.py</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider reintroducing a retry mechanism or a more specific error handling strategy for cases where the API call fails in a manner that was previously retried with `TryAgain`. This ensures robustness and reliability of the AI handler. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Codium-ai/pr-agent/pull/746/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfeR8'>from openai import APIError, RateLimitError, Timeout</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>pr_agent/servers/bitbucket_app.py</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Validate and sanitize the `commands` and `args` extracted from the configuration to prevent potential security risks or errors due to malformed commands. This is crucial when dynamically executing commands based on external input. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Codium-ai/pr-agent/pull/746/files#diff-963a9de391ff22ad3083c3a28c1d5736d68a6e1e40b0bedb52d4bfd124325badR82'>split_command = command.split(" ")</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>pr_agent/servers/bitbucket_app.py</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Implement error handling for the new dynamic command execution feature to ensure that failures in one command do not halt the execution of subsequent commands. This could include logging the error and continuing with the next command. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Codium-ai/pr-agent/pull/746/files#diff-963a9de391ff22ad3083c3a28c1d5736d68a6e1e40b0bedb52d4bfd124325badR91'>get_logger().error(f"Failed to perform command {command}: {e}")</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>pr_agent/algo/__init__.py</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Ensure that the token limit for the newly added `anthropic/claude-3-opus-20240229` model aligns with the actual capabilities and limitations of the model to prevent unexpected behavior. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Codium-ai/pr-agent/pull/746/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692bR25'>'anthropic/claude-3-opus-20240229': 100000,</a></td></tr></table><hr>

</details><hr>

<details> <summary><strong>✨ Review tool usage guide:</strong></summary><hr> 

**Overview:**
The `review` tool scans the PR code changes, and generates a PR review. The tool can be triggered [automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) every time a new PR is opened, or can be invoked manually by commenting on any PR.
When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L19) related to the review tool (`pr_reviewer` section), use the following template:
```
/review --pr_reviewer.some_config1=... --pr_reviewer.some_config2=...
```
With a [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app), use the following template:
```
[pr_reviewer]
some_config1=...
some_config2=...
```
    

<table><tr><td><details> <summary><strong> Utilizing extra instructions</strong></summary><hr>

The `review` tool can be configured with extra instructions, which can be used to guide the model to a feedback tailored to the needs of your project.

Be specific, clear, and concise in the instructions. With extra instructions, you are the prompter. Specify the relevant sub-tool, and the relevant aspects of the PR that you want to emphasize.

Examples for extra instructions:
```
[pr_reviewer] # /review #
extra_instructions="""
In the 'possible issues' section, emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
...
"""
```
Use triple quotes to write multi-line instructions. Use bullet points to make the instructions more readable.
        

</details></td></tr>

<tr><td><details> <summary><strong> How to enable\disable automation</strong></summary><hr>

- When you first install PR-Agent app, the [default mode](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) for the `review` tool is:
```
pr_commands = ["/review", ...]
```
meaning the `review` tool will run automatically on every PR, with the default configuration.
Edit this field to enable/disable the tool, or to change the used configurations
        

</details></td></tr>

<tr><td><details> <summary><strong> Auto-labels</strong></summary><hr>

The `review` tool can auto-generate two specific types of labels for a PR:
- a `possible security issue` label, that detects possible [security issues](https://github.com/Codium-ai/pr-agent/blob/tr/user_description/pr_agent/settings/pr_reviewer_prompts.toml#L136) (`enable_review_labels_security` flag)
- a `Review effort [1-5]: x` label, where x is the estimated effort to review the PR (`enable_review_labels_effort` flag)


</details></td></tr>

<tr><td><details> <summary><strong> Extra sub-tools</strong></summary><hr>

The `review` tool provides a collection of possible feedbacks about a PR.
It is recommended to review the [possible options](https://github.com/Codium-ai/pr-agent/blob/main/docs/REVIEW.md#enabledisable-features), and choose the ones relevant for your use case.
Some of the feature that are disabled by default are quite useful, and should be considered for enabling. For example: 
`require_score_review`, `require_soc2_ticket`, and more.


</details></td></tr>

<tr><td><details> <summary><strong> Auto-approve PRs</strong></summary><hr>

By invoking:
```
/review auto_approve
```
The tool will automatically approve the PR, and add a comment with the approval.


To ensure safety, the auto-approval feature is disabled by default. To enable auto-approval, you need to actively set in a pre-defined configuration file the following:
```
[pr_reviewer]
enable_auto_approval = true
```
(this specific flag cannot be set with a command line argument, only in the configuration file, committed to the repository)


You can also enable auto-approval only if the PR meets certain requirements, such as that the `estimated_review_effort` is equal or below a certain threshold, by adjusting the flag:
```
[pr_reviewer]
maximal_review_effort = 5
```


</details></td></tr>



<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 


</details></td></tr>

</table>

See the [review usage](https://github.com/Codium-ai/pr-agent/blob/main/docs/REVIEW.md) page for a comprehensive guide on using this tool.


</details>

**Pull request merged**
