### PR TITLE
Disable final update message when auto_describe is enabled in GitHub …

### PR DESCRIPTION
**Pull request by mrT23**
### **User description**
…Action Runner

___

### **PR Type**
enhancement, documentation

___

### **Description**
- Disabled the final update message in the GitHub Action Runner when `auto_describe` is enabled by setting `final_update_message` to `False`.
- Updated the usage guide documentation to remove the `enable_output` configuration line.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>github_action_runner.py</strong><dd><code>Disable final update message for auto_describe in GitHub Action Runner</code></dd></summary>
<hr>
      
pr_agent/servers/github_action_runner.py

<li>Disabled final update message when <code>auto_describe</code> is enabled.<br> <li> Added a line to set <code>final_update_message</code> to <code>False</code> in settings.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/939/files#diff-15f9c11da031449998128bdbba057d768853e836eedf44563be71b3847be80e0">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>automations_and_usage.md</strong><dd><code>Update usage guide to remove enable_output configuration</code>&nbsp; </dd></summary>
<hr>
      
docs/docs/usage-guide/automations_and_usage.md

- Removed documentation line for `enable_output` configuration.

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/939/files#diff-878bb0ecba4567cf6a5fa750521c6822078e4da41864153ab50a2e236e8e9451">+0/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/939#issuecomment-2144298944)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/4f130072679ec0249af3c8b6a9f5c2b4821fdc9d

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/939#issuecomment-2144298944)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/4f130072679ec0249af3c8b6a9f5c2b4821fdc9d

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
