### PR TITLE
adjustments to pypi

### PR DESCRIPTION
**Pull request by mrT23**
## **Type**
enhancement

___

## **Description**
- Introduced a new `run_command` function in `cli.py` for streamlined command execution.
- Refactored `cli_pip.py` to utilize the new `run_command` function, removing redundant code.
- Updated documentation in `locally.md` to reflect the new command execution process.
- Updated the project version to `0.2.1` in `pyproject.toml`.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>cli.py</strong><dd><code>Add run_command Function for Command Execution</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/cli.py

<li>Introduced a new function <code>run_command</code> to prepare and execute commands.<br> <li> This function parses the command using <code>set_parser</code> and executes it, <br>allowing feedback to appear in GitHub PR comments.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/815/files#diff-88577a9bac5c261b52dcec31fdf5e525cef5c6ddffdcb6bde0e9ba183fa05996">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>cli_pip.py</strong><dd><code>Refactor main Function to Use run_command</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/cli_pip.py

<li>Removed redundant logging setup and command preparation code.<br> <li> Refactored <code>main</code> function to use the new <code>run_command</code> function from <br><code>cli.py</code> for executing commands.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/815/files#diff-763fe6f9b69f1fb2c2740736bdadf5b2dff43f4021c193802444c97050f283fe">+1/-8</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>locally.md</strong><dd><code>Update Documentation for Command Execution</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
docs/docs/installation/locally.md

<li>Updated documentation to reflect changes in command execution process.<br> <li> Replaced detailed command preparation steps with a simplified call to <br><code>run_command</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/815/files#diff-eb5faafeb31ee35a5ac52ada7f6449d0bd142b3be46df74262c0490190b43481">+1/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pyproject.toml</strong><dd><code>Bump Project Version to 0.2.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pyproject.toml

- Updated the project version from `0.2.0` to `0.2.1`.

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/815/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/815#issuecomment-2016507906)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/ee4798accaf1f8050410ba3634d278d765e41b5e

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/815#issuecomment-2016507906)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/ee4798accaf1f8050410ba3634d278d765e41b5e

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/815#issuecomment-2016507906)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/ee4798accaf1f8050410ba3634d278d765e41b5e

**Comment by mrT23** [comment]
## PR Review

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

2, because the changes are straightforward and primarily involve refactoring and version bumping. The logic is not complex, but careful attention should be paid to the refactoring to ensure it doesn't introduce any functional regressions.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td> 🔍&nbsp;<strong>Possible issues</strong></td><td>

<strong>Possible Bug:</strong> The `run_command` function in `cli.py` directly parses and executes commands without any validation or error handling. This could lead to unexpected behavior or security issues if the input is not properly sanitized or validated.

</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>pr_agent/cli.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider adding input validation or sanitization in the `run_command` function to ensure that only expected and safe command patterns are executed. This can help prevent potential security issues or unexpected behavior. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Codium-ai/pr-agent/pull/815/files#diff-88577a9bac5c261b52dcec31fdf5e525cef5c6ddffdcb6bde0e9ba183fa05996R55'>run_command = f"--pr_url={pr_url} {command.lstrip('/')}"</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>pr_agent/cli.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

It's recommended to handle potential exceptions that may arise from `run(args=args)` to ensure the application can gracefully handle errors and provide meaningful feedback to the user. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Codium-ai/pr-agent/pull/815/files#diff-88577a9bac5c261b52dcec31fdf5e525cef5c6ddffdcb6bde0e9ba183fa05996R59'>run(args=args)</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>pr_agent/cli_pip.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Since `setup_logger()` was removed from `cli_pip.py`, ensure that logging is initialized elsewhere in the application or in the `run_command` function to maintain logging capabilities. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td>-setup_logger()</td></tr></table><hr>

<table><tr><td>relevant file</td><td>pyproject.toml
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

After updating the version to `0.2.1`, ensure that any dependencies that might have been affected by the changes in this PR are also reviewed and updated if necessary. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Codium-ai/pr-agent/pull/815/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R7'>version = "0.2.1"</a></td></tr></table><hr>

</details><hr>

<details> <summary><strong>✨ Review tool usage guide:</strong></summary><hr> 

**Overview:**
The `review` tool scans the PR code changes, and generates a PR review which includes several types of feedbacks, such as possible PR issues, security threats and relevant test in the PR. More feedbacks can be [added](https://pr-agent-docs.codium.ai/tools/review/#general-configurations) by configuring the tool.

The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on any PR.
- When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L23) related to the review tool (`pr_reviewer` section), use the following template:
```
/review --pr_reviewer.some_config1=... --pr_reviewer.some_config2=...
```
- With a [configuration file](https://pr-agent-docs.codium.ai/usage-guide/configuration_options/), use the following template:
```
[pr_reviewer]
some_config1=...
some_config2=...
```
    

See the review [usage page](https://pr-agent-docs.codium.ai/tools/review/) for a comprehensive guide on using this tool.


</details>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## PR Code Suggestions

<table><thead><tr><td>Category</td><td align=left>Suggestions&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </td></tr></thead><tbody><tr><td rowspan=1><strong>Maintainability</strong></td>
<td>



<details><summary>Rename the variable to avoid shadowing the function name.</summary>

___


**The <code>run_command</code> variable is being redefined as a string which could lead to confusion and <br>bugs. Consider renaming the variable used to construct the command string to avoid <br>shadowing the <code>run_command</code> function name.**
    
[pr_agent/cli.py [55]](https://github.com/Codium-ai/pr-agent/pull/815/files#diff-88577a9bac5c261b52dcec31fdf5e525cef5c6ddffdcb6bde0e9ba183fa05996R55-R55)

```diff
-run_command = f"--pr_url={pr_url} {command.lstrip('/')}"
+command_str = f"--pr_url={pr_url} {command.lstrip('/')}"
 
```
                   
</details></td></tr><tr><td rowspan=2><strong>Best practice</strong></td>
<td>



<details><summary>Add error handling for argument parsing.</summary>

___


**It's recommended to handle potential exceptions that could be raised by <code>parse_args</code> method, <br>especially when dealing with dynamic command strings. Consider wrapping the <code>parse_args</code> <br>call in a try-except block to catch and handle <code>argparse.ArgumentError</code>.**
    
[pr_agent/cli.py [56]](https://github.com/Codium-ai/pr-agent/pull/815/files#diff-88577a9bac5c261b52dcec31fdf5e525cef5c6ddffdcb6bde0e9ba183fa05996R56-R56)

```diff
-args = set_parser().parse_args(run_command.split())
+try:
+    args = set_parser().parse_args(run_command.split())
+except argparse.ArgumentError as e:
+    # Handle or log the error appropriately
+    print(f"Error parsing arguments: {e}")
 
```
                   
</details></td></tr><tr><td>



<details><summary>Update documentation and references for the new version.</summary>

___


**When updating the version number, it's a good practice to also update the documentation <br>and any references to the version number in the codebase to ensure consistency.**
    
[pyproject.toml [7]](https://github.com/Codium-ai/pr-agent/pull/815/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R7-R7)

```diff
 version = "0.2.1"
+# Ensure all references to the version in the codebase and documentation are updated accordingly.
 
```
                   
</details></td></tr><tr><td rowspan=1><strong>Possible issue</strong></td>
<td>



<details><summary>Ensure logging is properly configured.</summary>

___


**Removing the logger setup from the main script could lead to missing log configurations <br>and unexpected behavior. Ensure that logging is appropriately configured either in this <br>script or before this script is executed.**
    
[pr_agent/cli_pip.py [1]](https://github.com/Codium-ai/pr-agent/pull/815/files#diff-763fe6f9b69f1fb2c2740736bdadf5b2dff43f4021c193802444c97050f283feR1-R1)

```diff
 from pr_agent import cli
+# Ensure logging is set up here or before this point
 
```
                   
</details></td></tr><tr><td rowspan=1><strong>Enhancement</strong></td>
<td>



<details><summary>Add logging for command execution feedback.</summary>

___


**Consider adding logging or print statements within the <code>run_command</code> function to provide <br>feedback about the command execution status, especially useful for debugging purposes.**
    
[pr_agent/cli.py [59]](https://github.com/Codium-ai/pr-agent/pull/815/files#diff-88577a9bac5c261b52dcec31fdf5e525cef5c6ddffdcb6bde0e9ba183fa05996R59-R59)

```diff
+print(f"Executing command: {command_str}")
 run(args=args)
 
```
                   
</details></td></tr></tr></tbody></table><hr>

<details> <summary><strong>✨ Improve tool usage guide:</strong></summary><hr> 

**Overview:**
The `improve` tool scans the PR code changes, and automatically generates suggestions for improving the PR code. The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on a PR.
- When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L78) related to the improve tool (`pr_code_suggestions` section), use the following template:

```
/improve --pr_code_suggestions.some_config1=... --pr_code_suggestions.some_config2=...
```

- With a [configuration file](https://pr-agent-docs.codium.ai/usage-guide/configuration_options/), use the following template:

```
[pr_code_suggestions]
some_config1=...
some_config2=...
```
    


See the improve [usage page](https://pr-agent-docs.codium.ai/tools/improve/) for a comprehensive guide on using this tool.


</details>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Review by barnett-yuxiang — COMMENTED** [review]
cool

**Pull request merged**
