### PR TITLE
Block scalar format

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Refactoring

___
## PR Description:
This PR includes changes that refactor the way YAML is parsed in the codebase. It replaces the 'lstrip' method with 'removeprefix' for more precise string manipulation. Additionally, it updates the format of the prompt descriptions in the settings files to use block scalar format for better readability and consistency.

___
## PR Main Files Walkthrough:
`pr_agent/algo/utils.py`: Replaced the 'lstrip' method with 'removeprefix' for removing the '```yaml' prefix from the review text.
`pr_agent/tools/pr_reviewer.py`: Replaced the 'lstrip' method with 'removeprefix' for removing the '```yaml' prefix from the review text.
`pr_agent/settings/pr_description_prompts.toml`: Updated the format of the prompt descriptions to use block scalar format ('|-') for better readability.
`pr_agent/settings/pr_reviewer_prompts.toml`: Updated the format of the prompt descriptions to use block scalar format ('|-') for better readability.

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Analysis

- 🎯 **Main theme:** Refactoring the way YAML is parsed and updating the format of prompt descriptions
- 📌 **Type of PR:** Refactoring
- ✨ **Focused PR:** Yes, the PR is focused on refactoring YAML parsing and updating prompt descriptions.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

-  **General suggestions:** The PR is well-structured and the changes are clearly explained. However, it would be beneficial to add tests to ensure the refactored code works as expected.

- 🤖 **Code feedback:**


  - **relevant file:** ``pr_agent/algo/utils.py``
   **suggestion:** Consider handling the specific exceptions that yaml.load() might raise instead of catching all exceptions. This would make the error handling more precise and informative. [important]
   **relevant line:** [review_text = review_text.removeprefix('```yaml').rstrip('`')](https://github.com/Codium-ai/pr-agent/pull/200/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53R264)


  - **relevant file:** ``pr_agent/tools/pr_reviewer.py``
   **suggestion:** Similar to the previous suggestion, consider handling the specific exceptions that yaml.load() might raise instead of catching all exceptions. This would make the error handling more precise and informative. [important]
   **relevant line:** [review_text = review_text.removeprefix('```yaml').rstrip('`')](https://github.com/Codium-ai/pr-agent/pull/200/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dcR240)


  - **relevant file:** ``pr_agent/settings/pr_description_prompts.toml``
   **suggestion:** The change from '>' to '|-' in the block scalar format is a good improvement for readability. However, ensure that all other parts of the code that interact with these settings files are updated to handle this change. [medium]
   **relevant line:** [description: |-](https://github.com/Codium-ai/pr-agent/pull/200/files#diff-a52546bc2f8a156d8ee786c403e44b1561a6e3f1d98fcfbe8a0120bcee59981bR36)

**Comment by mrT23** [comment]
Preparing pr description...

**Review by okotek — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Pull request merged**
