### PR TITLE
Combine all modified and deleted files that been compressed to the prompt

### PR DESCRIPTION
**Pull request by hussam789**
## Description
Add two sections to the the prompt:
1. More Modified files: all modified file that been compressed into one list
2. Deleted file: all deleted files into one list

The final PR will have this format :
```
[PATCH 1]
[PATCH 2]


More modified files:
file_path_3
file_path_5

Deleted files:
file_path_4
```
instead of:
```
[PATCH 1]
## file_path_3

File was modified

[PATCH 2]

## file_path_4

File was deleted

## file_path_5

File was modified
```

All tests pass

### CODE REVIEW

**Review by okotek — APPROVED** [review]

**Comment by okotek** [comment]
@CodiumAI-Agent

**Comment by mrT23** [comment]
@CodiumAI-Agent summerize me the PR, in 4 bullet points

**Comment by mrT23** [comment]
@CodiumAI-Agent  summerize the PR, in 3 bullet points. add small code snippet to explain each one

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/3)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/ff720d32fe0a6bc1422de27162f9b5ca5d90cd97)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/3/files) Tab

**Pull request merged**
