### PR TITLE
Refactoring Question Handling in CLI

### PR DESCRIPTION
**Pull request by hussam789**

### CODE REVIEW

**Comment by hussam789** [comment]
@CodiumAI-Agent /describe

**Comment by hussam789** [comment]
@CodiumAI-Agent /describe

**Comment by hussam789** [comment]
Preparing pr description...

**Comment by hussam789** [comment]
@CodiumAI-Agent /describe

**Comment by hussam789** [comment]
@CodiumAI-Agent /review

**Review by mrT23 — APPROVED** [review]

**Comment by hussam789** [comment]
@CodiumAI-Agent /describe

**Comment by hussam789** [comment]
@CodiumAI-Agent /describe

**Pull request merged**
