### PR TITLE
Update atlassian-connect.json

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
enhancement, configuration changes

___

### **Description**
- Enhanced the scopes in `atlassian-connect.json` to provide additional permissions.
- Updated scopes to include `repository:write`, `pullrequest:write`, and `wiki` for improved functionality.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>atlassian-connect.json</strong><dd><code>Update scopes and permissions in atlassian-connect.json</code>&nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/servers/atlassian-connect.json

<li>Updated scopes to include <code>repository:write</code>, <code>pullrequest:write</code>, and <br><code>wiki</code>.<br> <li> Enhanced permissions for repository and pull request operations.<br> <li> Added new scope for wiki access.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1303/files#diff-7d20b40b3c44828ced91e4d8dcfcc9843f20dc6dc65a8886b21df8bf3bd4d8f3">+4/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by okotek — APPROVED** [review]

**Comment by mrT23** [comment]
### Question: 
how to prevent from any labels being published from automatic tools ?

### Answer:
To prevent any labels from being published by automatic tools in Qodo Merge, you can configure the `publish_labels` option to `false` in the relevant tool's configuration section. For example, for the `describe` tool, you can add the following to your configuration file:

```toml
[pr_description]
publish_labels = false
```

This setting ensures that no labels are automatically published to the PR when the `describe` tool is executed.

#### Relevant Sources:

> - https://qodo-merge-docs.qodo.ai/tools/describe#configuration-options
> - https://qodo-merge-docs.qodo.ai/overview/index#qodo-merge-features
> - https://qodo-merge-docs.qodo.ai/usage-guide/configuration_options#local-configuration-file

**Comment by mrT23** [comment]
### Question: 
how to turn off all automatic tools ?

### Answer:
To turn off all automatic tools in Qodo Merge, you can set the `pr_commands` parameter to an empty list in the configuration file. This will prevent any tools from running automatically when a new PR is opened. Here's how you can set it:

```toml
[github_app]
pr_commands = []
```

This configuration needs to be placed in a `.pr_agent.toml` file at the root of your repository.

#### Relevant Sources:

> - https://qodo-merge-docs.qodo.ai//usage-guide/automations_and_usage#github-app-automatic-tools-when-a-new-pr-is-opened

**Comment by mrT23** [comment]
### Question: 
how to turn off all automatic tools on gitlab ?

### Answer:
To turn off all automatic tools on GitLab for Qodo Merge, you need to modify the configuration file. Specifically, you can set the `pr_commands` parameter to an empty list in the configuration file. This will prevent any tools from running automatically when a new merge request is opened. Here's how you can set it in your configuration file:

```toml
[gitlab]
pr_commands = []
```

Make sure to upload this configuration to the root of your repository or apply it globally if you are using Qodo Merge Pro.

#### Relevant Sources:

> - https://qodo-merge-docs.qodo.ai/usage-guide/automations_and_usage#gitlab-webhook
> - https://qodo-merge-docs.qodo.ai/usage-guide/configuration_options#local-configuration-file

**Comment by mrT23** [comment]
### Question: 
how to turn off all automatic tools on gitlab ?

### Answer:
To turn off all automatic tools on GitLab, you need to set the `pr_commands` parameter to an empty list in the configuration file. This will cancel the automatic run of all tools when a new PR is opened.

#### Relevant Sources:

> - https://qodo-merge-docs.qodo.ai/usage-guide/automations_and_usage#gitlab-webhook
> - https://qodo-merge-docs.qodo.ai/usage-guide/configuration_options#local-configuration-file

**Comment by mrT23** [comment]
### Question: 
how to turn off all automatic tools on gitlab ?

### Answer:
To turn off all automatic tools on GitLab, you need to set the `pr_commands` parameter to an empty list in the configuration file. This will cancel the automatic run of all tools when a new PR is opened.

#### Relevant Sources:

> - https://qodo-merge-docs.qodo.ai/usage-guide/automations_and_usage#gitlab-webhook
> - https://qodo-merge-docs.qodo.ai/usage-guide/automations_and_usage#github-app

**Comment by mrT23** [comment]
### Question: 
how to get more customized code suggestions ?

### Answer:
To get more customized code suggestions, you can use the `extra_instructions` configuration option to provide specific guidance to the AI model. Additionally, creating a `best_practices.md` wiki page with tailored coding standards and guidelines for your repo can help the AI model generate suggestions that adhere to your organization's best practices.

Here are examples of how to use these features:

1. **Extra Instructions**:
   You can add specific instructions for the AI model in the `improve` tool's configuration:
   ```toml
   [pr_code_suggestions]
   extra_instructions="""\
   (1) Focus on memory optimization
   (2) Avoid using global variables
   """
   ```

2. **Best Practices**:
   Create a `best_practices.md` wiki page in your repository with detailed coding standards and guidelines. The AI model will reference this page to ensure the suggestions comply with your organization's best practices.

For more details on setting these configurations, refer to the documentation sections on extra instructions and best practices.

#### Relevant Sources:

> - https://qodo-merge-docs.qodo.ai/tools/improve#extra-instructions-and-best-practices
> - https://qodo-merge-docs.qodo.ai/usage-guide/configuration_options#wiki-configuration-file-💎

**Comment by mrT23** [comment]
### Question: 
how to get more customized code suggestions ?

### Answer:
To get more customized code suggestions, you can use the `extra_instructions` and `best_practices` configuration options with the `improve` tool. These options allow you to guide the AI model to generate more tailored suggestions based on specific instructions or coding standards relevant to your project.

For `extra_instructions`, you can specify detailed guidance directly in the command or configuration file. For example:
```toml
[pr_code_suggestions]
extra_instructions="""\
(1) Focus on security improvements
(2) Avoid suggestions to refactor large functions unless necessary
(3) Prioritize performance optimizations
"""
```

For `best_practices`, you can create a dedicated wiki page called `best_practices.md` in your repository, which contains a list of coding standards and guidelines. The AI model will use this page as a reference to generate suggestions that align with your project's best practices.

Additionally, you can use the `custom_prompt` tool to generate suggestions based on custom prompts that define specific guidelines or focus areas for the suggestions.

#### Relevant Sources:

> - https://qodo-merge-docs.qodo.ai/tools/improve#extra-instructions-and-best-practices
> - https://qodo-merge-docs.qodo.ai/tools/custom_prompt#overview

**Pull request merged**
