### PR TITLE
Add 'original_suggestion' parameter to publish_inline_comment methods…

### PR DESCRIPTION
**Pull request by mrT23**
### **User description**
… across git providers for enhanced inline comment handling

___

### **PR Type**
Enhancement

___

### **Description**
- Added `original_suggestion` parameter to `publish_inline_comment` methods across all git providers (Azure DevOps, Bitbucket, Bitbucket Server, CodeCommit, Gerrit, GitHub, GitLab, and Local Git)
- Enhanced GitLab provider to handle `original_suggestion` in `publish_code_suggestions` method
- Updated PR reviewer tool to pass `suggestion` as `original_suggestion` when publishing inline comments
- Updated `model_turbo` in configuration to use "gpt-4o-2024-08-06"

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>10 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>azuredevops_provider.py</strong><dd><code>Update Azure DevOps inline comment method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/azuredevops_provider.py

<li>Added <code>original_suggestion</code> parameter to <code>publish_inline_comment</code> method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-1a90ea92bcfba3cf9f1dbc298d2e570566f4c439cb3650ee746cebdb02ca4a0b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>bitbucket_provider.py</strong><dd><code>Update Bitbucket inline comment method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/bitbucket_provider.py

<li>Added <code>original_suggestion</code> parameter to <code>publish_inline_comment</code> method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-3f47323db85f534fa282b2d48c6cf542f00a5e791b62379253ef3d3e8c6bb3b2">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>bitbucket_server_provider.py</strong><dd><code>Update Bitbucket Server inline comment method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/bitbucket_server_provider.py

<li>Added <code>original_suggestion</code> parameter to <code>publish_inline_comment</code> method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-c9ca96d14ab7a2935714944f8f377c4a9bb425efde19e66595bb58d33e9f5a40">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>codecommit_provider.py</strong><dd><code>Update CodeCommit inline comment method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/codecommit_provider.py

<li>Added <code>original_suggestion</code> parameter to <code>publish_inline_comment</code> method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-a9a511824ea21a1f042997baae6216d47bddc232be7186ff97d6b6868d7a37b7">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>gerrit_provider.py</strong><dd><code>Update Gerrit inline comment method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/gerrit_provider.py

<li>Added <code>original_suggestion</code> parameter to <code>publish_inline_comment</code> method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-dae01da2d08399333945749d252be6d4f6b071e1add4e3079f58636b83c217d5">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>git_provider.py</strong><dd><code>Update abstract Git provider inline comment method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/git_provider.py

<li>Added <code>original_suggestion</code> parameter to abstract <code>publish_inline_comment</code> <br>method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-52d45f12b836f77ed1aef86e972e65404634ea4e2a6083fb71a9b0f9bb9e062f">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Update GitHub inline comment method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/github_provider.py

<li>Added <code>original_suggestion</code> parameter to <code>publish_inline_comment</code> method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>gitlab_provider.py</strong><dd><code>Enhance GitLab provider with original suggestion support</code>&nbsp; </dd></summary>
<hr>

pr_agent/git_providers/gitlab_provider.py

<li>Added <code>original_suggestion</code> parameter to <code>publish_inline_comment</code> and <br><code>send_inline_comment</code> methods<br> <li> Updated <code>publish_code_suggestions</code> to handle cases with and without <br><code>original_suggestion</code><br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-35acba7a2829983fcf3c3c6a69b135988227e503ccdfa94366d1b48fcbbb0a31">+8/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>local_git_provider.py</strong><dd><code>Update Local Git provider inline comment method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/local_git_provider.py

<li>Added <code>original_suggestion</code> parameter to <code>publish_inline_comment</code> method<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-d0638489e89a05817651792a46e3ba56033a9c21ad09f1fd2cc2c3ab71463269">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Update PR reviewer to use original suggestion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_reviewer.py

<li>Updated <code>_publish_inline_code_comments</code> to pass <code>suggestion</code> as <br><code>original_suggestion</code> parameter<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Update model configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

- Updated `model_turbo` to "gpt-4o-2024-08-06"

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1151/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
