### PR TITLE
Handling Large Files in Pull Requests

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Enhancement

___
## PR Description:
This PR introduces enhancements to handle large files in pull requests more efficiently. The main changes include:
- Added handling for added files that exceed the token budget.
- Modified the message for additional modified files that exceed the token budget.
- Added a new constant for added files.
- Updated the return type of `pr_generate_compressed_diff` function to include added files list.
- Updated the `handle_patch_deletions` function to handle added files.
- Added handling for the 'added' status in the Bitbucket provider.
- Updated the `get_pr_description` function in the GitProvider class to use a more descriptive variable name.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `pr_agent/algo/pr_processing.py`: Updated several functions to handle added files that exceed the token budget. Added a new constant for added files. Updated the return type of `pr_generate_compressed_diff` function to include added files list.
- `pr_agent/algo/git_patch_processing.py`: Updated the `handle_patch_deletions` function to handle added files.
- `pr_agent/git_providers/bitbucket_provider.py`: Added handling for the 'added' status in the Bitbucket provider.
- `pr_agent/git_providers/git_provider.py`: Updated the `get_pr_description` function in the GitProvider class to use a more descriptive variable name.
</details>

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Review by barnett-yuxiang — COMMENTED** [review]
check CI error?

**Comment by mrT23** [comment]
> check CI error?

this was a test repo, used for testing
https://github.com/Codium-ai/pr-agent/pull/439

**Pull request closed without merging**
