### PR TITLE
Add Support for GPT-4o November 2024 Model and Update Configurations

### PR DESCRIPTION
**Pull request by KennyDizi**
### **PR Type**
Dependencies, Configuration

___

### **PR Description**
- Added support for the new `gpt-4o-2024-11-20` model across configuration files
- Updated model configurations to use the latest GPT-4o model variants
- Upgraded `litellm` dependency to version `1.52.12` to ensure compatibility

___

### **Changes Walkthrough** 
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add GPT-4o November 2024 Model Token Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/__init__.py

<li>Added new model <code>gpt-4o-2024-11-20</code> to the model token configuration<br> <li> Specified token limit of 128,000 for the new model<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1374/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692b">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Upgrade LiteLLM Dependency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt

- Upgraded `litellm` from version `1.52.0` to `1.52.12`

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1374/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Configuration</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Update Default and Fallback Model Configurations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

<li>Updated <code>model_turbo</code> to <code>gpt-4o-2024-11-20</code><br> <li> Updated <code>fallback_models</code> to use <code>gpt-4o-2024-08-06</code><br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1374/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by KennyDizi** [comment]
## PR Analysis 🌴

🌈 🌴 These observations could help streamline our PR review:

<table>
<tr><td><br>⏰ &nbsp;<strong>Estimated effort to review</strong> 2, because the changes are straightforward, focusing on adding support for a new model, updating configurations, and bumping a dependency version. The changes are well-contained and do not introduce complex logic.</td></tr><tr><td><br>🥇 &nbsp;<strong>Score</strong> 95, because the PR is well-structured, introduces minimal risk, and aligns with the stated purpose of adding support for a new model and updating configurations. However, there is a slight lack of clarity in testing coverage for the new model.</td></tr><tr><td><br>🐳&nbsp;<strong> Recommended focus areas for review</strong><br>

<a href='https://github.com/Codium-ai/pr-agent/pull/1374/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692bR9-R23'><strong>Code Smell</strong></a><br>The growing list of model configurations in the dictionary may become harder to maintain over time. Consider refactoring this into a more scalable structure, such as loading configurations from a file or database.

<a href='https://github.com/Codium-ai/pr-agent/pull/1374/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78R1-R12'><strong>Configuration Consistency</strong></a><br>Ensure that the new `model_turbo` and `fallback_models` configurations are tested and validated for compatibility with the rest of the system.

<a href='https://github.com/Codium-ai/pr-agent/pull/1374/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R12-R15'><strong>Dependency Update</strong></a><br>Verify that the updated `litellm` dependency (version 1.52.12) does not introduce breaking changes or incompatibilities with existing functionality.

</td></tr></table>

**Comment by mrT23** [comment]
Thanks for the PR @KennyDizi 

We might want to further change the model usage, but let's save it for a new PR

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
Note that this PR actually broke the publishing.
Unfurtantly upgrading litellm tends to be problematic 

(in this case, openai should also have been upgraded:
https://github.com/microsoft/sample-app-aoai-chatGPT/issues/1190)

**Comment by KennyDizi** [comment]
@mrT23 that's a good catch. The libs change frequently, and we need to adapt to it.

**Pull request merged**
