### PR TITLE
Fixed `pr_description.enable_file_walkthrough`

### PR DESCRIPTION
**Pull request by zmeir**
## Type
bug_fix

___

## Description
This PR restores the functionality of the `pr_description.enable_file_walkthrough` feature which was affected by the introduction of the `pr_description.enable_semantic_files_types` feature. The changes include:
- Adjustments to the handling of the 'pr_files' key and its associated values in the `_prepare_pr_answer_with_markers` and `_prepare_pr_answer` methods in `pr_description.py`.
- Updates to the `_prepare_file_labels` method to handle the 'label' key within the 'pr_files' data.
- Changes to the `process_pr_files_prediction` method to correctly process the 'pr_files' prediction based on the settings of `pr_description.enable_semantic_files_types` and `pr_description.enable_file_walkthrough`.
- Updates to the `pr_description_prompts.toml` file to reflect the changes in the `pr_description.py` file.

___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Bug_fix</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_description.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/tools/pr_description.py<br><br>

**The file has undergone significant changes to restore the <br>functionality of the <br>`pr_description.enable_file_walkthrough` feature. This <br>includes adjustments to the <br>`_prepare_pr_answer_with_markers` and `_prepare_pr_answer` <br>methods to correctly handle the 'pr_files' key and its <br>associated values. The `_prepare_file_labels` method has <br>also been updated to handle the 'label' key within the <br>'pr_files' data. The `process_pr_files_prediction` method <br>has been updated to correctly process the 'pr_files' <br>prediction based on the settings of <br>`pr_description.enable_semantic_files_types` and <br>`pr_description.enable_file_walkthrough`.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/562/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb"> +18/-16</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration_changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_description_prompts.toml&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/settings/pr_description_prompts.toml<br><br>

**The file has been updated to reflect the changes in the <br>`pr_description.py` file. The `FileDescription` class now <br>includes the 'label' field only if <br>`enable_semantic_files_types` is enabled. The <br>`PRDescription` class now includes the 'pr_files' field if <br>either `enable_semantic_files_types` or <br>`enable_file_walkthrough` is enabled.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/562/files#diff-a52546bc2f8a156d8ee786c403e44b1561a6e3f1d98fcfbe8a0120bcee59981b"> +7/-10</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

## User description
The new (and very cool) feature `pr_description.enable_sematic_files_types` changed some of the prompts and handling of the description pr_file list. This PR restores the ability to choose between the 2 possible configurations (default still remains the new semantic files feature).

### CODE REVIEW

**Comment by mrT23** [comment]
Thanks for the PR.
I think i will do something simpler - just remove the old mode. Will open a PR.

i wanted to change things gradually, but it seems that the new mode works well, and I don't think there is a use-case for the old mode.

also notice that bitbucket doesn't support collapsible (😠 😠 ), so for every new feature we need to think if It can be presented reasonably well with bitbucket, or not. but i think the old mode was also too verbose for bitbucket

**Comment by zmeir** [comment]
> Thanks for the PR. I think i will do something simpler - just remove the old mode. Will open a PR.
> 
> i wanted to change things gradually, but it seems that the new mode works well, and I don't think there is still a use-case for the old mode.
> 
> also notice that bitbucket doesn't support collapsible (😠 😠 ), so for every new feature we need to think if It can be presented reasonably well with bitbucket, or not. but i think the old mode was also too verbose for bitbucket, so no need there to keep it

Haha yeah that's much simpler 😅

I actually liked the previous mode better in some cases, that's why I wanted to restore its functionality. When I review PRs I like that I have a simple list of all the files and a short summary of what happened in each one. The new mode had a much better high-level view, but I find it more cumbersome when I what to start drilling down on each file.

But of course it's ultimately your decision, just wanted to give my 2 cents.

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/pull/565

**Comment by mrT23** [comment]
At least for markers, i want to switch to the new mode. It's getting messy to handle several modes.

I got several feedbacks about the old walkthrough that said: "it looks nice. but actually not really useful".

Maybe for the new mode we can add a parameter to remove the first layer of collapsible, so you don't have to click that much

**Comment by zmeir** [comment]
Also, if I may add a small suggestion:

The header for other sections is `## Type` and `## Description` (instead of `## PR type` and `## PR description` so maybe change the header for this header to `## Changes walkthrough` instead of `## PR changes walkthrough`?

**Comment by mrT23** [comment]
image

Now i am debating with myself if that should be the new default (remove one layer of collapsibles) :-)

**Comment by zmeir** [comment]
> image
> 
> Now i am debating with myself if that should be the new default (remove one layer of collapsibles) :-)

That does look cleaner to me :)

**Comment by zmeir** [comment]
Maybe add some threshold for the number of files? Like if there are more than 5 files in a section add the extra level, but if there are only a few files remove the extra level.

**Comment by mrT23** [comment]
yep, already did that.
will add first layer of collapsible only if num_of_files>X=8

**Comment by mrT23** [comment]
https://github.com/Codium-ai/pr-agent/pull/565
covers this

thanks for the insights in the PR

**Pull request closed without merging**
