### PR TITLE
Enhancement of PR Description and Labeling Features

### PR DESCRIPTION
**Pull request by mrT23**
## Type
Enhancement

___
## Description
This PR introduces several enhancements and changes to the PR description and labeling features:
- Removed 'Refactoring' from the list of default labels.
- Enhanced link generation for relevant lines in Bitbucket, GitHub, and GitLab providers.
- Added the ability to count the number of lines added and removed in a file patch.
- Improved the formatting of help command descriptions.
- Added the ability to include a file walkthrough and semantic file types in the PR description.
- Updated the prompts in 'pr_description_prompts.toml' for clarity and to reflect the new features.
- Updated the 'configuration.toml' settings to enable or disable the new PR description features.

___
## PR changes summary

| | Relevant Files &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |
|-----------|-------------|
| **configuration changes** | <details><summary>files:</summary><ul><details><summary>**utils.py** <sup>[ ( +2/-2 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53)</sup></summary><ul>Change summary:<br>**Removed 'Refactoring' from the list of default labels and the <br>condition to check for user labels.**</ul></details><details><summary>**configuration.toml** <sup>[ ( +4/-1 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78)</sup></summary><ul>Change summary:<br>**Added 'enable_file_walkthrough' and 'enable_semantic_files_types' to <br>the PR description settings. Also, commented out the 'custom_labels' <br>setting.**</ul></details><details><summary>**custom_labels.toml** <sup>[ ( +1/-3 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-9d8a028839b2d05b1ad28b11e4253577bc5b021a48b9957a49686e49a076bbbf)</sup></summary><ul>Change summary:<br>**Removed 'Refactoring' from the list of custom labels.**</ul></details><details><summary>**pr_custom_labels.toml** <sup>[ ( +0/-1 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-b3402f995845be3362b029d0069c70ea982a8f19bd78357b97f4ed58ce0d062e)</sup></summary><ul>Change summary:<br>**Removed 'Refactoring' from the list of PR types.**</ul></details><details><summary>**pr_description_prompts.toml** <sup>[ ( +27/-2 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-a52546bc2f8a156d8ee786c403e44b1561a6e3f1d98fcfbe8a0120bcee59981b)</sup></summary><ul>Change summary:<br>**Updated the prompts to reflect the new features of PR description. <br>Also, removed 'Refactoring' from the list of PR types.**</ul></details><details><summary>**pr_reviewer_prompts.toml** <sup>[ ( +0/-1 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-2e1ca45d2d8635b5f9cde801d9d210f6516e7f15d45dd9b0be134ac91e7a2e63)</sup></summary><ul>Change summary:<br>**Removed 'Refactoring' from the list of PR types.**</ul></details></ul></details>|
| **enhancement** | <details><summary>files:</summary><ul><details><summary>**bitbucket_provider.py** <sup>[ ( +4/-1 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-3f47323db85f534fa282b2d48c6cf542f00a5e791b62379253ef3d3e8c6bb3b2)</sup></summary><ul>Change summary:<br>**Enhanced the link generation for relevant lines to handle the case <br>when the relevant line start is -1.**</ul></details><details><summary>**git_provider.py** <sup>[ ( +2/-0 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-52d45f12b836f77ed1aef86e972e65404634ea4e2a6083fb71a9b0f9bb9e062f)</sup></summary><ul>Change summary:<br>**Added 'num_plus_lines' and 'num_minus_lines' to the 'FilePatchInfo' <br>class to count the number of lines added and removed in a file patch.**</ul></details><details><summary>**github_provider.py** <sup>[ ( +12/-3 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11)</sup></summary><ul>Change summary:<br>**Counted the number of lines added and removed in a file patch and <br>stored them in 'num_plus_lines' and 'num_minus_lines'. Also, removed <br>'Refactoring' from the label color map.**</ul></details><details><summary>**gitlab_provider.py** <sup>[ ( +3/-1 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-35acba7a2829983fcf3c3c6a69b135988227e503ccdfa94366d1b48fcbbb0a31)</sup></summary><ul>Change summary:<br>**Enhanced the link generation for relevant lines to handle the case <br>when the relevant line start is -1.**</ul></details><details><summary>**pr_description.py** <sup>[ ( +68/-4 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb)</sup></summary><ul>Change summary:<br>**Added the ability to include a file walkthrough and semantic file <br>types in the PR description. Also, prepared a file label dictionary if <br>semantic file types are enabled.**</ul></details></ul></details>|
| **formating** | <details><summary>files:</summary><ul><details><summary>**help.py** <sup>[ ( +12/-12 )](https://github.com/Codium-ai/pr-agent/pull/509/files#diff-aa5878a57c5e6e9436d73b8c8d1e78a443f2f09d829303040b463f7fba89f1d8)</sup></summary><ul>Change summary:<br>**Improved the formatting of help command descriptions by adding extra <br>spaces at the end of each command.**</ul></details></ul></details>|

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/509)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/eeb20b055af2eca315af147b7a2eb18120b1b6f7)

**Review by hussam789 — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/509)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/a61e492fe1a401c1a2e4963b34c4721215964a5b)

**Pull request merged**
