### PR TITLE
ai_metadat_injection

### PR DESCRIPTION
**Pull request by mrT23**
### **User description**
aaa

___

### **PR Type**
Enhancement

___

### **Description**
* Implemented AI metadata injection functionality for PR processing and review
* Added conditional AI summary addition to patches in various tools and providers
* Updated git providers to handle split changes walkthrough in PR descriptions
* Implemented process_description function to handle AI-generated summaries
* Added auto-command flags for various server webhooks (Azure DevOps, Bitbucket, GitHub, GitLab)
* Removed extra_issue_links functionality
* Updated FilePatchInfo class to include ai_file_summary attribute
* Restructured and expanded core abilities documentation
* Minor formatting and string updates across multiple files

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>git_patch_processing.py</strong><dd><code>Patch string formatting updates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/git_patch_processing.py

<li>Changed 'file:' to 'File:' in patch string formatting<br> <li> Minor formatting adjustments<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-c5a7f9db4adbcf394c7855f6da656c073d5a6bcc18bd6dede44a8207893174b8">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Enhancement</strong></td><td><details><summary>11 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_processing.py</strong><dd><code>AI metadata integration for PR processing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/pr_processing.py

<li>Added AI metadata injection functionality<br> <li> Introduced new parameter for PR description files<br> <li> Implemented conditional AI summary addition to patches<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04e">+44/-2</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>types.py</strong><dd><code>FilePatchInfo class extension</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/types.py

* Added 'ai_file_summary' attribute to FilePatchInfo class

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-0c3039b74ad9c9d420e814993ecd2f0454c3683157be0e7da32a2a90027b3f9b">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>PR description processing enhancements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/utils.py

<li>Implemented process_description function to handle AI-generated <br>summaries<br> <li> Removed extra_issue_links functionality<br> <li> Added HTML to text conversion for summaries<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+63/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>azuredevops_provider.py</strong><dd><code>Azure DevOps provider update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/azuredevops_provider.py

<li>Updated get_pr_description method signature to include <br>split_changes_walkthrough parameter<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-1a90ea92bcfba3cf9f1dbc298d2e570566f4c439cb3650ee746cebdb02ca4a0b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>git_provider.py</strong><dd><code>Git provider description handling update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/git_provider.py

<li>Modified get_pr_description method to handle split_changes_walkthrough<br> <li> Implemented logic to process and return AI-generated summaries<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-52d45f12b836f77ed1aef86e972e65404634ea4e2a6083fb71a9b0f9bb9e062f">+11/-5</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>azuredevops_server_webhook.py</strong><dd><code>Azure DevOps webhook auto-command flag</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/servers/azuredevops_server_webhook.py

<li>Added setting for is_auto_command in _perform_commands_azure function<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-4525cb1c9c5ffe691dee1db5501c614ab50388fdf711220ee18db18cf64a7358">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>bitbucket_app.py</strong><dd><code>Bitbucket app auto-command flag</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/servers/bitbucket_app.py

<li>Added setting for is_auto_command in _perform_commands_bitbucket <br>function<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-963a9de391ff22ad3083c3a28c1d5736d68a6e1e40b0bedb52d4bfd124325bad">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>github_app.py</strong><dd><code>GitHub app auto-command handling update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/servers/github_app.py

<li>Removed is_auto_command setting from handle_new_pr_opened<br> <li> Added is_auto_command setting in _perform_auto_commands_github<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-3fb3f174152732d1b69953c8bd81b8a0a30f0e42100dc626d932da8371851608">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>gitlab_webhook.py</strong><dd><code>GitLab webhook auto-command flag</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/servers/gitlab_webhook.py

<li>Added setting for is_auto_command in _perform_commands_gitlab function<br> <br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-c3ea1ba460930c6e6e6a2c36a7dc729d79730a96e872d40ffb246f80bc7c0880">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions.py</strong><dd><code>PR code suggestions tool AI metadata integration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_code_suggestions.py

<li>Added logic to handle AI metadata in PR description<br> <li> Implemented conditional AI metadata addition to patches<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117b">+16/-3</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>PR reviewer tool AI metadata integration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_reviewer.py

<li>Added logic to handle AI metadata in PR description<br> <li> Implemented conditional AI metadata addition to patches<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+13/-5</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>compression_strategy.md</strong><dd><code>PR compression strategy documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/core-abilities/compression_strategy.md

* Added new file with content explaining PR compression strategy

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-7633da27ac78e3beabf98cf772c2ee061a6453e83191f361f5dbddcf4b343c9d">+47/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Core abilities documentation restructure</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/core-abilities/index.md

<li>Replaced content with an overview of core abilities<br> <li> Added links to individual core ability pages<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-a227d8509d77d7fbf58c4223c4eb3dc609cc4598877d4f2361960128bb00172c">+10/-52</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>mkdocs.yml</strong><dd><code>Documentation navigation update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/mkdocs.yml

<li>Updated navigation structure for core abilities section<br> <li> Added new pages for individual core abilities<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1206/files#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2df">+10/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1206)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/552e249e2702cc620d5b2127c8506644cebde9f4)

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1206)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/552e249e2702cc620d5b2127c8506644cebde9f4)

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
