### PR TITLE
fix: handle deleted files in git patch processing and update section header logic

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Improved section header logic:
  - Now updates both start and size in a single operation for better efficiency
  - Adjusts `extended_start2` and `extended_size2` along with their counterparts
- Added handling for deleted files:
  - Checks if the file has an `edit_type` attribute set to `DELETED`
  - Returns a message indicating file deletion instead of processing the patch
- Enhanced context limits calculation:
  - Ensures more accurate representation of changes in the patch
- These changes improve the overall robustness and accuracy of git patch processing

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>git_patch_processing.py</strong><dd><code>Enhance git patch processing and file handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/git_patch_processing.py

<li>Updated section header logic to adjust both start and size in one <br>operation<br> <li> Added handling for deleted files in git patch processing<br> <li> Improved context limits calculation for better patch representation<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1179/files#diff-c5a7f9db4adbcf394c7855f6da656c073d5a6bcc18bd6dede44a8207893174b8">+7/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1179#issuecomment-2311681234)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/c2f52539aa0b34dd15de3d0e5be41c27767c8795

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1179#issuecomment-2311681234)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/c2f52539aa0b34dd15de3d0e5be41c27767c8795

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
