### PR TITLE
Refactor markdown generation logic to eliminate redundancy

### PR DESCRIPTION
**Pull request by KennyDizi**
### **PR Type**
Refactoring

___

### **Description**
- Removed redundant conditional checks for GitHub Flavored Markdown (GFM) support.
- Simplified the logic for adding markdown text based on the presence of tests.
- Consolidated the conditional branches to reduce code duplication.

___

### **Changes walkthrough** 
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Refactoring</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Refactor markdown generation logic to eliminate redundancy</code></dd></summary>
<hr>

pr_agent/algo/utils.py

<li>Removed redundant conditional checks for GFM support.<br> <li> Simplified the logic for adding markdown text based on test presence.<br> <li> Consolidated the conditional branches to reduce code duplication.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1043/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+3/-10</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by KennyDizi** [comment]
💥 🏠 The **[PR description](https://github.com/Codium-ai/pr-agent/pull/1043)** has been updated to align with the latest commit (https://github.com/Codium-ai/pr-agent/commit/8a7f3501ea0c3fff266750b59c8c3cf3812d4d77).

**Comment by mrT23** [comment]
The code there may be simplified, but not like this.

When 'gfm_supported' is True (GitHub, GitLab, Azure), we want this section to be "HTML" (or to be exact, what is called 'extended markdown'). There are good reasons for that - the entire table is like that, and it looks better, and gives more options

When  'gfm_supported' is False (crappy bitbucket), we must use plain markdown, which is worse.

Even if, technically these specific lines give similar results, I still want to keep the HTML format, to be compatible with previous ones. extended markdown is better than plain markdown

**Comment by KennyDizi** [comment]
Thanks for your feedback @mrT23 .
In this case, the GitHub code diff needs to be more smart. I only remove unreachable code
CleanShot 2024-07-17 at 08 16 46
You can see the code was repeated making it redundancy.
CleanShot 2024-07-17 at 08 16 46
Pls, correct me if I'm getting wrong.

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
ok, i see now

image

**Pull request merged**
