### PR TITLE
Tr/ignore

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
enhancement, documentation

___

### **Description**
- Enhanced file ignore functionality to support multiple platforms (GitHub, Bitbucket, GitLab, Azure DevOps).
- Fixed markdown formatting issues in `utils.py`.
- Updated documentation to include examples for ignoring files using `glob` and `regex` patterns.
- Logged filtered and invalid files in various git providers.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>7 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>file_filter.py</strong><dd><code>Enhance file ignore functionality for multiple platforms</code>&nbsp; </dd></summary>
<hr>
      
pr_agent/algo/file_filter.py

<li>Added support for multiple platforms (GitHub, Bitbucket, GitLab, Azure <br>DevOps) in file ignore functionality.<br> <li> Enhanced the <code>filter_ignored</code> function to handle different file <br>attribute structures.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-69253bbdc5eb87fd84c5890160f09b23ee55e5ba958c4f1c8914df9f7d0f7fb4">+13/-2</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>language_handler.py</strong><dd><code>Add type annotation to is_valid_file function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/algo/language_handler.py

- Added type annotation to `is_valid_file` function.

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-23434de851547d0e53ae2cc599b254a2a129c99ecfa9cd5d5b8e1373c58dc354">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Fix markdown formatting and handle code tags</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/algo/utils.py

<li>Fixed markdown formatting issues by removing extra newlines.<br> <li> Added <code>replace_code_tags</code> function to handle code tags in markdown.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+8/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>azuredevops_provider.py</strong><dd><code>Integrate file ignore functionality and log filtered files</code></dd></summary>
<hr>
      
pr_agent/git_providers/azuredevops_provider.py

<li>Integrated file ignore functionality.<br> <li> Logged filtered and invalid files.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-1a90ea92bcfba3cf9f1dbc298d2e570566f4c439cb3650ee746cebdb02ca4a0b">+15/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>bitbucket_provider.py</strong><dd><code>Integrate file ignore functionality and log filtered files</code></dd></summary>
<hr>
      
pr_agent/git_providers/bitbucket_provider.py

<li>Integrated file ignore functionality.<br> <li> Logged filtered and invalid files.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-3f47323db85f534fa282b2d48c6cf542f00a5e791b62379253ef3d3e8c6bb3b2">+23/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Integrate file ignore functionality and log filtered files</code></dd></summary>
<hr>
      
pr_agent/git_providers/github_provider.py

<li>Integrated file ignore functionality.<br> <li> Logged filtered and invalid files.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+25/-7</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>gitlab_provider.py</strong><dd><code>Integrate file ignore functionality and log filtered files</code></dd></summary>
<hr>
      
pr_agent/git_providers/gitlab_provider.py

<li>Integrated file ignore functionality.<br> <li> Logged filtered and invalid files.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-35acba7a2829983fcf3c3c6a69b135988227e503ccdfa94366d1b48fcbbb0a31">+60/-41</a>&nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation
</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>additional_configurations.md</strong><dd><code>Update documentation for file ignore patterns</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
docs/docs/usage-guide/additional_configurations.md

<li>Updated documentation to include examples for ignoring files using <br><code>glob</code> and <code>regex</code> patterns.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-9290a3ad9a86690b31f0450b77acd37ef1914b41fabc8a08682d4da433a77f90">+6/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ignore.toml</strong><dd><code>Add regex pattern example in ignore settings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/settings/ignore.toml

- Added example for regex pattern in ignore settings.

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/966/files#diff-21f9a5508090b480828110f80f256a0120c35a195b21bf1794b3cc4f84145994">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by barnett-yuxiang — APPROVED** [review]
good

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## Incremental PR Reviewer Guide 🔍

⏮️ Review for commits since previous PR-Agent review Starting from commit https://github.com/Codium-ai/pr-agent/pull/966/commits/1070f9583fe99b61ab687026f44135bfecb50120.

<table>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>
3


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>
No


</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>
No

</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Key issues to review</strong></td>
<td>
<strong>Possible Bug:</strong><br> The <code>filter_ignored</code> function in <code>file_filter.py</code> has been modified to include a platform parameter, but the default value is 'github'. This might not be clear or expected behavior for all use cases. Consider handling the default case more explicitly or documenting this behavior.</td></tr>
<tr>
<td>
<strong>Refactoring Concern:</strong><br> The <code>filter_ignored</code> function now includes conditional logic for different platforms. This approach might lead to difficulties in maintaining and extending this function in the future as more platforms or special cases are added. Consider using a strategy pattern or similar design pattern to handle platform-specific differences more cleanly.</td></tr>
</table>

**Comment by mrT23** [comment]
Incremental Review Skipped
No files were changed since the [previous PR Review](https://github.com/Codium-ai/pr-agent/pull/966#issuecomment-2177865949)

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/966#issuecomment-2165191329)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/e083841d968098ded6349d2f6cac0b4273e0316c

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/966#issuecomment-2165191329)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/e083841d968098ded6349d2f6cac0b4273e0316c

**Pull request merged**
