### PR TITLE
Tr/help fixes

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Documentation

___

### **Description**
- Improved the PR Help tool functionality:
  - Fixed snippet indexing to start from 1 for better user experience
  - Enhanced logging for clearer answer output display
- Updated Doc-helper AI instructions in pr_help_prompts.toml:
  - Added more detailed guidelines for generating concise answers
  - Clarified priority of main PR-Agent tools (describe, review, improve)
  - Improved Pydantic model definition and naming
- These changes aim to enhance the overall user experience and clarity of the PR Help feature

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_help_message.py</strong><dd><code>Improve snippet indexing and logging in PR Help tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_help_message.py

<li>Fixed indexing in snippet display, now starting from 1 instead of 0<br> <li> Updated logging to improve readability of the answer output<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1247/files#diff-6f30977025b20a27640fc33cfe2db79160753bd30c7879f60f2b5894d86f78de">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_help_prompts.toml</strong><dd><code>Enhance Doc-helper AI instructions and model definition</code>&nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_help_prompts.toml

<li>Added more detailed instructions for the Doc-helper AI<br> <li> Clarified the priority of main PR-Agent tools<br> <li> Updated the Pydantic model name from 'doc_help' to 'DocHelper'<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1247/files#diff-f57c5aa2dd64b54b0ab0eca942be5017fadda145a400b2b15ab442d4c04edd47">+9/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by mrT23** [comment]
/help "My team often creates pull requests (PRs) from a combined branch that has already reviewed branches for production deployment. In these cases, executing auto-triggered tasks on such PRs is often unnecessary, as they may involve extensive code changes and place significant load on the pr-agent service.
So, I suggest adding an option to selectively disable auto-triggered tasks on specific pull requests. This feature would allow teams to optimize their workflow and reduce unnecessary processing load. I have implemented and utilized this feature in our pr-agent codebase.

For example, this can be implemented by adding a flag to the PR title or at the end of the PR description. When this flag is present, pr-agent will not automatically perform a review. However, if needed, users can still trigger a review manually by entering a command in a comment after the PR is created.
"

**Comment by mrT23** [comment]
/help "i want to add a flag to the PR title or at the end of the PR description. When this flag is present, pr-agent will not automatically perform a review. However, if needed, users can still trigger a review manually by entering a command in a comment after the PR is created."

**Comment by mrT23** [comment]
/help
"add a flag to the PR title or at the end of the PR description. When this flag is present, pr-agent will not run automatically"

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
