### PR TITLE
Improve pr_code_suggestions_reflect_prompts.toml

### PR DESCRIPTION
**Pull request by KennyDizi**
### **PR Type**
enhancement, documentation

___

### **Description**
- Fixed an invalid property name from `suggestion_content` to `suggestion_summary`.
- Added more examples for n-short prompting, including detailed suggestions for code improvements.
- Used backticks to quote variable names in the `why` section for better readability.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions_reflect_prompts.toml</strong><dd><code>Update suggestion examples and fix property names</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/settings/pr_code_suggestions_reflect_prompts.toml

<li>Fixed invalid property name from <code>suggestion_content</code> to <br><code>suggestion_summary</code>.<br> <li> Added examples for n-short prompting with detailed suggestions.<br> <li> Used backticks to quote variable names in the <code>why</code> section.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/992/files#diff-aeee2207a4afb3ea3368c3e0140629bb3da8858b6d2315db5778661c9390d144">+14/-2</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
@KennyDizi thanks for the feedback. basically the prompt field has a bug, this should fix it:
https://github.com/Codium-ai/pr-agent/pull/995/files

As a rule of thumb, examples should be as short as possible. their main purpose is to demonstrate the **YAML structure**
Hence, I wont accept this PR as-is. but I will fix the bug you pointed out

**Comment by kenny-cxingularity** [comment]
Should I remove the additional examples? Thus we don’t need to open another PR.

**Comment by mrT23** [comment]
> Should I remove the additional examples? Thus we don’t need to open another PR.

i already merged. but thanks for the PR, it did identify a problem

**Comment by KennyDizi** [comment]
That's good to know! However, I think you can guide the community in updating the PR in this situation or similar situations. You can totally open a new PR to fix that but that increasingly loses the community's motivation.

**Comment by mrT23** [comment]
i understand. it was a bug, and I wanted to fix it quickly.
Next time, I will give the original PR author a couple of hours to make the adjustments himself

**Comment by KennyDizi** [comment]
I'm the author of this PR, and that would be great @mrT23

**Pull request closed without merging**
