### PR TITLE
GitHub Hostname Variable.

### PR DESCRIPTION
**Pull request by tjohnson-bfunds**
## **Type**
enhancement

___

## **Description**
- Introduced dynamic GitHub URLs configuration to support different GitHub instances.
- Added `github_instance_url` and `github_base_url` in `github_provider.py` to replace hardcoded URLs.
- Updated `_parse_pr_url` and `_parse_issue_url` methods to utilize the new dynamic URL variables.
- Added `instance_url` in `configuration.toml` to allow configuration of the GitHub instance URL.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Support Dynamic GitHub URLs in GitHubProvider</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/git_providers/github_provider.py

<li>Introduced <code>github_instance_url</code> and <code>github_base_url</code> variables to <br>dynamically set GitHub URLs.<br> <li> Modified <code>_parse_pr_url</code> and <code>_parse_issue_url</code> methods to use these new <br>variables instead of hardcoded URLs.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/852/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+8/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add GitHub Instance URL Configuration Option</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/settings/configuration.toml

<li>Added <code>instance_url</code> configuration option to specify the GitHub instance <br>URL.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/852/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
@tjohnson-bfunds 
what is the motivation for this PR ? 

why does: https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/git_providers/github_provider.py#L27
is not enough ?

**Comment by mrT23** [comment]
@tjohnson-bfunds
is this PR still relevant, or should I close it ?

you have not responded to my questions

**Comment by hussam789** [comment]
/review
--pr_reviewer.require_score_review=true
--pr_reviewer.num_code_suggestions="1"
--pr_reviewer.require_can_be_split_review=true
--pr_reviewer.require_soc2_ticket=true

**Comment by hussam789** [comment]
/review
--pr_reviewer.require_score_review=true
--pr_reviewer.num_code_suggestions="1"
--pr_reviewer.require_can_be_split_review=true
--pr_reviewer.require_soc2_ticket=true

**Comment by oranshiner** [comment]
/improve
--pr_reviewer.extra_instructions="
Emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
- 
"
--pr_code_suggestions.num_code_suggestions_per_chunk="4"
--pr_code_suggestions.summarize=false

**Comment by mrT23** [comment]
@tjohnson-bfunds i am closing this PR as inactive.
you can re-open it after reviewing and answering the comments I gave

**Pull request closed without merging**
