### PR TITLE
Fix bitbucket publish description

### PR DESCRIPTION
**Pull request by sarbjitsinghgrewal**
To resolve this issue, I've implemented a regular expression (regex) to extract the description from the entire body sent by the pr_description. As a result, both the description and title for pull requests are now being updated correctly.
here is the screenshot:
image

### CODE REVIEW

**Comment by coditamar** [comment]
/improve --pr_code_suggestions.extra_instructions="focus on improving the robustness of the changes and managing with edge cases"

**Comment by Emsh1379** [comment]
@CodiumAI-Agent /review

**Pull request closed without merging**
