### PR TITLE
gitlab push_commands

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
documentation, enhancement

___

### **Description**
- Updated GitLab webhook documentation to use "MR" instead of "PR".
- Added new configuration options for handling push events in GitLab:
  - `handle_push_trigger` to enable the feature.
  - `push_commands` to define tools that run automatically on new code push.
- Included a note about the necessity of the "Push events" scope for the GitLab webhook.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>automations_and_usage.md</strong><dd><code>Update GitLab webhook documentation with push command configurations</code></dd></summary>
<hr>
      
docs/docs/usage-guide/automations_and_usage.md

<li>Updated terminology from "PR" to "MR" for GitLab.<br> <li> Added documentation for <code>handle_push_trigger</code> configuration.<br> <li> Added documentation for <code>push_commands</code> configuration.<br> <li> Included note on required "Push events" scope for GitLab webhook.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/947/files#diff-878bb0ecba4567cf6a5fa750521c6822078e4da41864153ab50a2e236e8e9451">+15/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
