### PR TITLE
feat: allows ollama usage

### PR DESCRIPTION
**Pull request by gregoryboue**
## **User description**
Fix https://github.com/Codium-ai/pr-agent/issues/657

___

## **Type**
enhancement

___

## **Description**
- **OLLAMA API Support**: The PR introduces support for configuring the OLLAMA API base, allowing for expanded AI model usage within the application. This enhancement aligns with the initial goal of enabling OLLAMA usage, as indicated in the PR title and the linked issue.
- **Configuration Flexibility**: By adding a conditional check for the `OLLAMA.API_BASE` setting, the application now supports more flexible configuration options, catering to different AI model APIs.
- **Code Consistency**: Minor adjustments were made to maintain code consistency, such as ensuring a newline at the end of the `chat_completion` method.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>litellm_ai_handler.py</strong><dd><code>Add OLLAMA API Base Configuration Support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/algo/ai_handlers/litellm_ai_handler.py

<li>Added support for OLLAMA API base configuration.<br> <li> Ensured the API base is set for both Huggingface and OLLAMA <br>configurations.<br> <li> Maintained the return statement format at the end of the <br><code>chat_completion</code> method.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/836/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfe">+4/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
@gregoryboue 
looks good

is the guide here still accurate:
https://pr-agent-docs.codium.ai/usage-guide/additional_configurations/#huggingface
?

**Comment by gregoryboue** [comment]
> @gregoryboue looks good
> 
> is the guide here still accurate: https://pr-agent-docs.codium.ai/usage-guide/additional_configurations/#huggingface ?

Yes the guide still accurate

**Review by mrT23 — APPROVED** [review]

**Comment by gregoryboue** [comment]
@mrT23 , I did a mistake in my previous answer.

With my PR change, if i do a /review command, then [here](https://github.com/Codium-ai/pr-agent/blob/877aeffbb3cfaebe923a86c916f9f0b12c1d8156/pr_agent/tools/pr_reviewer.py#L127) it's writed : `model_type=ModelType.TURBO` so in [`pr_processing._get_all_models`](https://github.com/Codium-ai/pr-agent/blob/877aeffbb3cfaebe923a86c916f9f0b12c1d8156/pr_agent/algo/pr_processing.py#L269) the model used is `get_settings().config.model_turbo` and not `get_settings().config.model`

So the right configuration to use ollama model locally hosted is : 

```yaml
[config] # in configuration.toml
model = "ollama/llama2"
model_turbo = "ollama/llama2"
```

If i didn't do that the command uses fallback model and never try with `config.model` settings.

So is it normal to you ? Is the code must be changed or only documentation ?

**Comment by hussam789** [comment]
/describe
--pr_description.extra_instructions="
For the title, use the format: [type]: [summary]
"
--pr_description.keep_original_user_title=false
--pr_description.final_update_message=false

**Pull request merged**
