### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Other

___

### **Description**
- Added logic to count the number of lines added and removed in a patch in `azuredevops_provider.py`.
- Included `num_plus_lines` and `num_minus_lines` in the `FilePatchInfo` object.
- Removed the `handle_apply_suggestion` method from `pr_code_suggestions.py`.
- Updated imports in `pr_code_suggestions.py` to include `GithubProvider` and `GitLabProvider`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>azuredevops_provider.py</strong><dd><code>Add line count for additions and deletions in patch</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/git_providers/azuredevops_provider.py

<li>Added logic to count the number of lines added and removed in a patch.<br> <li> Included <code>num_plus_lines</code> and <code>num_minus_lines</code> in the <code>FilePatchInfo</code> <br>object.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1009/files#diff-1a90ea92bcfba3cf9f1dbc298d2e570566f4c439cb3650ee746cebdb02ca4a0b">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Other</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions.py</strong><dd><code>Remove handle_apply_suggestion method and update imports</code>&nbsp; </dd></summary>
<hr>
      
pr_agent/tools/pr_code_suggestions.py

<li>Removed the <code>handle_apply_suggestion</code> method.<br> <li> Updated imports to include <code>GithubProvider</code> and <code>GitLabProvider</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1009/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117b">+1/-38</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1009#issuecomment-2196153462)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/4c444f5c9acf7eac2403f06a5994a9f9a63d98e6

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 2 🔵🔵⚪⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Key issues to review</strong>**Possible Bug:**
 The counting of lines added and removed in `azuredevops_provider.py` includes the line that starts with a '+' or '-' from the diff format itself, which might not be intended. Consider excluding these lines if they are not meant to be counted.

</td></tr>
</table>

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## PR Reviewer Guide 🔍

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 2 🔵🔵⚪⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Key issues to review</strong>

**Possible Bug:**
 The logic for counting lines added and removed in `azuredevops_provider.py` might include the line starting with '+' from the diff header, which is not an actual line of code but part of the diff formatting. This could lead to inaccurate counts.

</td></tr>
</table>

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1009#issuecomment-2205112845)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/4c444f5c9acf7eac2403f06a5994a9f9a63d98e6

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
