### PR TITLE
Implement the ability to have small PR's not get sent to the LLM

### LINKED ISSUE #1144: Minimum context / size of changes
We've found that the LLM is more likely to hallucinate or provide "noise" suggestions on small changes (such as one line changes). We suspect it is because the bot has less context to work with so is more likely to "reach for straws". 

I suggest configuration option(s) to set the "minimum diff/context/PR" size.

It could be:
* A global minimum that is the minimum number of tokens of the entire PR diff (not of the prompt). This would be more precise because it would capture the "size of a line" or
* A global minimum that is the minimum number of lines that need to change in the PR. The number of lines may be easier to configure and understand than number of tokens but won't take into effect how big a line is

When the bot skips processing it should provide some kind of feedback to that effect so the end user knows it ran (and didn't crash).

I could also see:
* A minimum number of tokens before the pr agent will comment on a specific hunk and offer suggestions or
* A minimum number of lines before the pr agent will comment on a specific hunk and offer suggestions

The defaults would be set to 0 for backwards compatibility.

### PR DESCRIPTION
**Pull request by AHancher2022**
### **User description**
Resolves #1144 

This PR allows for users to set a minimum number of tokens in a PR that they would not like to be sent to the LLM. Defaults to 0 but can be configurable per user basis.

___

### **PR Type**
Enhancement

___

### **Description**
- Implemented a minimum token threshold for processing PRs in both code suggestions and review tools
- Added token count checks to prevent processing small PRs that may lead to hallucinations or unnecessary LLM calls
- Introduced new configuration options in `configuration.toml` for setting minimum token thresholds
- Modified prediction logic in `pr_code_suggestions.py` to handle cases below the token threshold
- Updated `pr_reviewer.py` to include a token count check before processing PR reviews
- Improved logging to provide information about token counts and decision-making process

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_code_suggestions.py</strong><dd><code>Implement minimum token threshold for code suggestions</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_code_suggestions.py

<li>Added token count check to prevent processing small PRs<br> <li> Implemented minimum token threshold for LLM processing<br> <li> Modified prediction logic to handle cases below the token threshold<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1168/files#diff-b57ba775e741d6f80bc4f8154b71330c011dae0ac43f3d0197e785b3e6b7117b">+40/-19</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Add minimum token check for PR review</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_reviewer.py

<li>Added token count check for PR review<br> <li> Implemented minimum token threshold to prevent hallucinations<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1168/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+9/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add minimum token configuration options</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

<li>Added configuration options for minimum tokens for suggestions and <br>review<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1168/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+3/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
see my answer here:
https://github.com/Codium-ai/pr-agent/issues/1144#issuecomment-2305420678

i want to explore this direction first, as it is more general, and far less intrusive

**Comment by AHancher2022** [comment]
@mrT23 Could this be a short term solution for the long term problem?

**Comment by mrT23** [comment]
The code changes are very big here.

i do appreciate the effort, and until I have a better solution, I will keep this PR live.
But it cannot be merged currently, as the possible alternative is 1-2 lines of code

**Comment by mrT23** [comment]
closing, as this was fixed in a significantly less intrusive way in
https://github.com/Codium-ai/pr-agent/pull/1170/files

**Pull request closed without merging**
