### PR TITLE
docs pr help

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Documentation

___

### **Description**
- Introduced a new `/help` feature allowing users to ask questions in natural language within pull requests
- Updated PR description to include a more informative help message about the new feature
- Enhanced PR help message tool with improved error handling and Docker environment support
- Updated README and documentation to reflect the new `/help` feature and its usage
- Added an image demonstrating the PR help chat functionality in the README

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_description.py</strong><dd><code>Update PR description help message</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_description.py

<li>Updated the help comment message in PR description to be more <br>informative and user-friendly<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1245/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_help_message.py</strong><dd><code>Enhance PR help message tool robustness</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_help_message.py

<li>Added fallback path for local database in Docker environment<br> <li> Improved error handling for failed similar snippet retrieval<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1245/files#diff-6f30977025b20a27640fc33cfe2db79160753bd30c7879f60f2b5894d86f78de">+7/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Update README with new help feature</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

README.md

<li>Added new section about the <code>/help</code> feature in the News and Updates<br> <li> Included an image demonstrating the PR help chat functionality<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1245/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5">+6/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Add documentation for new help feature</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/index.md

<li>Added information about using the <code>/help</code> command for natural language <br>documentation search<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1245/files#diff-7dd3ba15306fb8ca0c3fa4a2e10b4d3b708c3a338bc2c4a028b4e1d0e565dc88">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
/help "In CLI, can i do a dry run and just print locally without publishing? "

**Comment by mrT23** [comment]
/help "In CLI, can i do a dry run and just print locally without publishing? "

**Comment by mrT23** [comment]
/help "Any way we can help customers exclude repos when configuring repos or the only option is choose which repos to include?"

**Comment by mrT23** [comment]
/help "is there a way to disable the emails or notifications from the PR-Agent?"

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
