### PR TITLE
Fix deployment of GitHub app to GCP Cloud Run.

### PR DESCRIPTION
**Pull request by tifrel**
### **User description**
I have followed [the official docs regarding cloud deployment of the GitHub app](https://pr-agent-docs.codium.ai/installation/github/#run-as-a-github-app), and have run into multiple issues. Most of these are docs-related (the secrets need to be passed as environment variables, not inside the secrets file, as per proper DevSecOps practice).

However if the service does not respect the `PORT` environment variable, deployment fails. This PR fixes that. It is in draft for now to possibly address the documentation problems as well.

___

### **PR Type**
Bug fix

___

### **Description**
- Updated Gunicorn configuration to respect the `PORT` environment variable for binding.
- Default to port 3000 if the `PORT` environment variable is not set.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>gunicorn_config.py</strong><dd><code>Use `PORT` environment variable for binding in Gunicorn config</code></dd></summary>
<hr>

pr_agent/servers/gunicorn_config.py

<li>Changed the <code>bind</code> variable to use the <code>PORT</code> environment variable if <br>available.<br> <li> Default to port 3000 if <code>PORT</code> is not set.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1049/files#diff-aa57135d532088b55c798696d920373167b854afceac1f809b15847a5c8b5934">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
@tifrel i suggest you do this change in a fork
When finished, open a PR, and we will review.

ongoing draft PRs are not something suitable for an open-source repo like pr-agnet

**Comment by tifrel** [comment]
@mrT23 Unfortunately, I cannot recall the exact order of steps, and it will consume far too much time to go through it again. I know I couldn't just create the app and the CR Deployment later as suggested in your docs, but had to do CR deployment, then create GH app, then redo CR deployment to update some environment variable. Also it was unclear that environment variables were required instead of changing the secrets.toml file as suggested in the docs. I will mark this as ready for review since the contribution will still allow anyone to deploy this to GCP CR, which would have failed previously.

**Comment by mrT23** [comment]
@tifrel 
you said the documentation is not clear, but don't want to update it.

Just updating the port is not enough for a PR. i am also not sure that this suits AWS or Azure, for example, and is not just something tailored for GCP

In general, PRs should be accompanied by documentation update

**Comment by mrT23** [comment]
Closing this PR, as it is not accompanied by meaningful documentation update.
welcome to re-open it when they are relevant.

**Pull request closed without merging**
