### PR TITLE
Fix Syntax Error in f-string Expression

### PR DESCRIPTION
**Pull request by KennyDizi**
## PR Type:
Bug fix

___
## PR Description:
This PR fixes a syntax error in an f-string expression in the `pr_reviewer.py` file. The error was caused by the inclusion of a backslash in the expression part of the f-string. The fix involves replacing the backslash with a suitable replacement.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

`pr_agent/tools/pr_reviewer.py`: The f-string expression that was causing a SyntaxError has been fixed. The backslash in the expression part of the f-string has been replaced with a suitable replacement. The modified f-string is used to append a commit message to the `incremental_review_markdown_text` string.
</details>

### CODE REVIEW

**Comment by KennyDizi** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
@hussam789

**Comment by KennyDizi** [comment]
@hussam789 @mrT23 Fix the issue when running `review -i` command
CleanShot 2023-11-01 at 20 11 01@2x

**Comment by hussam789** [comment]
Tested:
image

**Review by hussam789 — APPROVED** [review]

**Comment by zmeir** [comment]
Sorry about this, I tested the original code (with the f-string) only in python 3.10 where this syntax is legal.

**Pull request merged**
