### PR TITLE
Add and document abilty to use LiteLLM Logging Observability tools

### PR DESCRIPTION
**Pull request by MarkRx**
### **User description**
Adds out-of-the-box support for setting up a logging and observability tool using LiteLLM by setting up callbacks. Should work with any of the documented [callbacks](https://litellm.vercel.app/docs/observability/callbacks).

Code uses the starlette context to track PR information to avoid complexity of passing it around everywhere. It will use a basic context when running with the CLI. Doing so allows for code simplification.

Sample LangSmith run:
image

#1105

See also https://github.com/BerriAI/litellm/issues/5179

___

### **PR Type**
Enhancement, Documentation

___

### **Description**
- Implemented LiteLLM logging and observability support:
  - Added success, failure, and service callbacks configuration
  - Included metadata in chat completions for various observability platforms (e.g., LangFuse, LangSmith)
- Enhanced context management throughout the application:
  - Added Starlette context for tracking PR information
  - Simplified git provider and repo settings context handling
- Improved CLI functionality with request cycle context
- Added documentation for integrating with logging observability platforms, including example configuration for LangSmith
- Updated configuration.toml with new LiteLLM callback options (commented out by default)

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_agent.py</strong><dd><code>Add context information to PR handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/agent/pr_agent.py

<li>Imported <code>context</code> from <code>starlette_context</code><br> <li> Added context information for action, provider_id, and pr_url<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1145/files#diff-db2b038f914c88e292869242ae3c293765511994a83d72459642e81b5b741f47">+6/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>litellm_ai_handler.py</strong><dd><code>Implement LiteLLM logging and observability</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/ai_handlers/litellm_ai_handler.py

<li>Added support for LiteLLM callbacks (success, failure, service)<br> <li> Included metadata in chat completion for various observability <br>platforms<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1145/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfe">+29/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>cli.py</strong><dd><code>Enhance CLI with request cycle context</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/cli.py

- Added `request_cycle_context` to handle CLI mode

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1145/files#diff-88577a9bac5c261b52dcec31fdf5e525cef5c6ddffdcb6bde0e9ba183fa05996">+9/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Streamline git provider context management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/__init__.py

<li>Simplified git provider context handling<br> <li> Removed try-except blocks for context operations<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1145/files#diff-91af7b74c12181fd8aac8cd7ec8af9a01aed1adfb67eff4748e8f6a6ca3cc660">+7/-17</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Simplify repo settings context management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/utils.py

- Simplified repo settings context handling

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1145/files#diff-314199df3610cf35a472e952294faf0f5fbb516a2bd217e891a510fd1a698bca">+1/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Document logging observability integration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/installation/index.md

<li>Added documentation for integrating with logging observability <br>platforms<br> <li> Provided example configuration for LangSmith integration<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1145/files#diff-db2dd63439c555e50f5fe6eea191af347e9da8653ef1c9b12c49f335df03a52a">+24/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add LiteLLM callback configuration options</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

- Added commented-out configuration options for LiteLLM callbacks

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1145/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by hussam789** [comment]
@CodiumAI-Agent /analyze

**Comment by mrT23** [comment]
@MarkRx 
This PR cannot be merged as is.
These are the needed changes:

(1) Remove any modification whatsoever to the `context`, or things related to it. It should not be a part of this PR.
This is a complicated var, that is used b applications. don't change it.

(2) the instructions should move to:
https://pr-agent-docs.codium.ai/usage-guide/additional_configurations/

**Comment by MarkRx** [comment]
I need place to get contextual traceability information about the request without having to pass it around everywhere that also works for the CLI. If I don't put it in the middleware request context where could I put it? It could be pulled off of the logger context but that seems awkward. I could maintain some kind of command context with `ContextVar` but that may be intrusive.

I don't have a clean way of handling the different Observability platforms. For example,[LangFuse](https://langfuse.com/docs/integrations/litellm/tracing), [Helicone](https://litellm.vercel.app/docs/observability/helicone_integration), and [LangSmith](https://litellm.vercel.app/docs/observability/langsmith_integration) use different fields and others are either not documented or not mature in LiteLLM. I figured I could just send them all. It's important to set these fields though as without them observability records don't provide enough information to be useful. I suppose I could build the metadata dictionary based on which callbacks are being used?

**Comment by mrT23** [comment]
@MarkRx 
under no circumstance will I approve doing these changes in the default mode, without an `if` that turns them on if a flag is on. They are also too versboe, and should be exported to a function (when a flag is on)

I also don't like the context changes that you made. They are fragile, and require hacks for cli.

you could have passed parameters using `get_settings()`,  or use, just in `pr_agent.py` use the existing methodology.

But **all** my concerns above need to be addressed. If you prefer your way, then its suitable for a fork

image

**Comment by MarkRx** [comment]
Updated with a different approach. Metadata is a dictionary to allow for different metadata per command.

Metadata won't be passed to LiteLLM unless a callback is defined.

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
@MarkRx 
- This PR is still _way_ too intrusive.
- You are editing every tool, just for a specific ultra-tailored option that won't be used by 99.95% of pr-agent users

- You are also ignoring the existing logger mechanism, which already conveys all the PR and flow data
- In addition, it does not contain a _single_ control parameter, turned off by default: `litellm.enable_callbacks`

To address all the issues, you can start from this template, merge it, and edit the `add_litellm_callbacks` function to accommodate more things:
https://github.com/Codium-ai/pr-agent/pull/1152/files#diff-ea1acaa0907f3410665530fbc4cda2ab524de2772e0bbe10bad4648b8be35dfeR113

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
looks good

And you can now easily edit `add_litellm_callbacks` function and add update its content if you think its necessariy

**Pull request merged**
