### PR TITLE
Initial implementation of CodeCommit

### PR DESCRIPTION
**Pull request by pzarfos**
## Description

This PR adds an initial implementation of AWS CodeCommit.  (see issue https://github.com/Codium-ai/pr-agent/issues/138)

This will run the pr-agent CLI in "review" mode, and it posts the AI generated comment to your CodeCommit PR.  (see the setup instructions at the bottom of `INSTALL.md` file)

This implementation adds PR review capabilities as a first step... more features can be added based on usage and demand.

## Changes

- added `boto3` to the `requirements.txt` file
- added `CodeCommitProvider` to the `pr_agent/git_providers/__init__.py` file
- 2 files added in `pr_agent/git_providers`
    - `codecommit_provider.py`
        - class derived from `GitProvider` interface, which implements the bulk of the provider functionality for CodeCommit
        - I based this on parts of the `git_provider.py`, `bitbucket_provider.py`, and `local_git_provider.py`, with customizations specific for CodeCommit
        - CodeCommit does not have as many features as GitHub... for example the percentages of languages used, so I had to calculate the languages manually... and there are some static methods at the bottom of the file to do that, which we could move into common util methods
    - `codecommit_client.py`
        - This class is a wrapper around the AWS boto3 SDK, to keep the `codecommit_provider.py` cleaner
        - Technically this is not a provider class, but I left it in with the `git_providers` so as not start building out new directory structures to hold one extra file... this can be moved later
- 2 files added in `tests/unittest`, for testing the above classes
    - `test_codecommit_client.py`
    - `test_codecommit_provider.py`
- added a "CodeCommit" column to the functionality table in `README.md`
- added a "AWS CodeCommit Setup" section to `INSTALL.md`

### CODE REVIEW

**Comment by mrT23** [comment]
@okotek

**Comment by okotek** [comment]
@pzarfos I added boto3 to pyproject.toml.
It's a good idea to merge requirements.txt and pyproject.toml, but we didn't do it yet :/

**Review by okotek — APPROVED** [review]

**Comment by okotek** [comment]
I'm going to merge without extensive testing from our side, and monitor for errors and issues

**Comment by okotek** [comment]
@pzarfos we have failed unit tests, can you take a look? I'll revert the merge for now

**Comment by okotek** [comment]
(and reopen a PR)

**Pull request merged**
