### PR TITLE
Markers

### PR DESCRIPTION
**Pull request by mrT23**
Initial header 

### 🤖 Generated by PR Agent at bba22667f14a3606b7daacaab76914b6bc8c5ad7

This PR introduces several enhancements in the process of generating and publishing PR descriptions. It adds support for markers in the description, allowing for more dynamic and context-aware descriptions. It also introduces the option to publish the description as a comment, and to include labels in the PR. Additionally, it improves logging by including the PR ID in log messages. The PR also includes some minor code refactoring and cleanup.

### 🤖 Generated by PR Agent at bba22667f14a3606b7daacaab76914b6bc8c5ad7

- `pr_agent/tools/pr_description.py`: Added support for markers in the PR description. Introduced the option to publish the description as a comment. Improved logging by including the PR ID in log messages. Added the option to include labels in the PR. Refactored the code to improve readability and maintainability.
- `pr_agent/settings/configuration.toml`: Added new configuration options related to PR description publishing. These include the option to publish labels, to use description markers, and to include a generated by header.

### CODE REVIEW

**Review by okotek — APPROVED** [review]

**Review by tjwp — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
Preparing pr description...

**Comment by mrT23** [comment]
@tjwp merged your chang here

**Pull request merged**
