### PR TITLE
Fixes 404 error on gitlab file provider happening in case a MR introduced a new file.

### PR DESCRIPTION
**Pull request by patryk-kowalski-ds**
In case of new file creation by the MR there is a 404 error on file retrieval by gitlab provider.

It was handled by catching the error and replacing the file string with an empty string. Type checking was added before byte decoding - necessary in case of the empty string.

### CODE REVIEW

**Comment by AndyHafell** [comment]
@CodiumAI-Agent /review

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
thanks @patryk-kowalski-ds 
We personally use GithHub, so QA and PRs about other git providers is welcomed

**Pull request merged**
