### PR TITLE
Tr/readme

### PR DESCRIPTION
**Pull request by mrT23**
## **Type**
enhancement, bug_fix

___

## **Description**
- Enhanced the `clip_tokens` function in `pr_agent/algo/utils.py` for better readability by adding a newline before the truncation indicator.
- Simplified the `calc_pr_statistics` method in `pr_agent/git_providers/github_provider.py` to return an empty dictionary, removing the previous complex logic.
- Added a new condition in `pr_agent/tools/pr_reviewer.py` to check the `publish_output` setting before proceeding with setting review labels, enhancing configuration flexibility.
- Updated the unit test in `tests/unittest/test_clip_tokens.py` to reflect the changes in the `clip_tokens` function output.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Enhance Token Clipping Functionality for Better Readability</code></dd></summary>
<hr>
      
pr_agent/algo/utils.py

<li>Modified the <code>clip_tokens</code> function to append a newline before the <br>truncation indicator.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/848/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Simplify PR Statistics Calculation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/git_providers/github_provider.py

<li>Simplified the <code>calc_pr_statistics</code> method to return an empty <br>dictionary, removing previous logic.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/848/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+1/-19</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Conditional Review Labels Setting Based on Configuration</code>&nbsp; </dd></summary>
<hr>
      
pr_agent/tools/pr_reviewer.py

<li>Added a condition to check <code>publish_output</code> setting before setting <br>review labels.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/848/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+3/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_clip_tokens.py</strong><dd><code>Update Unit Test for Token Clipping Function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
tests/unittest/test_clip_tokens.py

<li>Updated unit test to match the new line addition before the truncation <br>indicator in <code>clip_tokens</code> output.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/848/files#diff-e0d2301f7471bdf0451bec140c772466252228f1c7c864064182073ab629c82d">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/848)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/8a5b01b4657d5522b6b4d44592f66cf3150f1836)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/848/files) Tab

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
## PR Custom Suggestions

No custom suggestions found to improve this PR.<hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `custom_suggestions` tool scans the PR code changes, and automatically generates custom suggestions for improving the PR code.

Unlike the `improve` tool, which offers more general suggestion according to a pre-configured set of rules, the `custom_suggestions` tool will only propose suggestion that follow specific guidelines defined by the prompt in: `pr_custom_suggestions.prompt` configuration.

The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on a PR.
When commenting, use the following template:

```
/custom_suggestions --pr_custom_suggestions.prompt="The suggestions should focus only on the following:\n-...\n-...\n-..."
```

With a https://pr-agent-docs.codium.ai/usage-guide/configuration_options/, use the following template:

```
[pr_custom_suggestions]
prompt="""\
The suggestions should focus only on the following:
-...
-...
-...
"""
```
Using a configuration file is recommended, since it allows to use multi-line instructions.

Don't forget - with this tool, you are the prompter. Be specific, clear, and concise in the instructions. Specify relevant aspects that you want the model to focus on. You might benefit from several trial-and-error iterations, until you get the correct prompt for your use case.


<table>

<tr><td><details> <summary><strong> Example usage</strong></summary><hr> 

Here is an example for a possible prompt:
```
[pr_custom_suggestions]
prompt="""\
The suggestions should focus only on the following:
- look for edge cases when implementing a new function
- make sure every variable has a meaningful name
- make sure the code is efficient
"""
```     

The instructions above are just an example. We want to emphasize that the prompt should be specific and clear, and be tailored to the needs of your project.

</details></td></tr>



<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://pr-agent-docs.codium.ai/tools/) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 


</details></td></tr>

</table>

See the [custom suggestions](https://pr-agent-docs.codium.ai/tools/custom_suggestions/) usage page for a more comprehensive guide on using this tool.


</details>

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
## PR Custom Suggestions

No custom suggestions found to improve this PR.<hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `custom_suggestions` tool scans the PR code changes, and automatically generates custom suggestions for improving the PR code.

Unlike the `improve` tool, which offers more general suggestion according to a pre-configured set of rules, the `custom_suggestions` tool will only propose suggestion that follow specific guidelines defined by the prompt in: `pr_custom_suggestions.prompt` configuration.

The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on a PR.
When commenting, use the following template:

```
/custom_suggestions --pr_custom_suggestions.prompt="The suggestions should focus only on the following:\n-...\n-...\n-..."
```

With a https://pr-agent-docs.codium.ai/usage-guide/configuration_options/, use the following template:

```
[pr_custom_suggestions]
prompt="""\
The suggestions should focus only on the following:
-...
-...
-...
"""
```
Using a configuration file is recommended, since it allows to use multi-line instructions.

Don't forget - with this tool, you are the prompter. Be specific, clear, and concise in the instructions. Specify relevant aspects that you want the model to focus on. You might benefit from several trial-and-error iterations, until you get the correct prompt for your use case.


<table>

<tr><td><details> <summary><strong> Example usage</strong></summary><hr> 

Here is an example for a possible prompt:
```
[pr_custom_suggestions]
prompt="""\
The suggestions should focus only on the following:
- look for edge cases when implementing a new function
- make sure every variable has a meaningful name
- make sure the code is efficient
"""
```     

The instructions above are just an example. We want to emphasize that the prompt should be specific and clear, and be tailored to the needs of your project.

</details></td></tr>



<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://pr-agent-docs.codium.ai/tools/) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 


</details></td></tr>

</table>

See the [custom suggestions](https://pr-agent-docs.codium.ai/tools/custom_suggestions/) usage page for a more comprehensive guide on using this tool.


</details>

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
## PR Custom Suggestions

<table><thead><tr><th></th><th>Suggestions&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Readability</strong></td><td><table><tr><td>

<details><summary>Improve string concatenation readability by using the <code>format</code> function.</summary>

___


  
  
**Consider using the <code>format</code> function to append the string. This can make the code more <br>readable and maintainable.**
    
[pr_agent/algo/utils.py [578]](https://github.com/Codium-ai/pr-agent/pull/848/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53R578-R578)

```diff
-clipped_text += "\n...(truncated)"
+clipped_text = "{}\n...(truncated)".format(clipped_text)
 
```
                   
</details></td></tr></table><tr><td><strong>Functionality</strong></td><td><table><tr><td>

<details><summary>Ensure the <code>calc_pr_statistics</code> function is correctly implemented.</summary>

___


  
  
**The <code>calc_pr_statistics</code> function is now returning an empty dictionary, which might not be <br>the intended behavior. If you want to return an empty dictionary as a placeholder, please <br>make sure to implement the actual logic later.**
    
[pr_agent/git_providers/github_provider.py [748]](https://github.com/Codium-ai/pr-agent/pull/848/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11R748-R748)

```diff
-return {}
+...
 
```
                   
</details></td></tr></table><tr><td><strong>Efficiency</strong></td><td><table><tr><td>

<details><summary>Good use of early return to avoid unnecessary computations.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</summary>

___


  
  
**The new condition <code>if not get_settings().config.publish_output:</code> seems to be checking if the <br>output should be published or not. If the output should not be published, the function <br>returns immediately. This is a good practice for avoiding unnecessary computations.**
    
[pr_agent/tools/pr_reviewer.py [360-361]](https://github.com/Codium-ai/pr-agent/pull/848/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dcR360-R361)

```diff
-if not get_settings().config.publish_output:\n    return
+...
 
```
                   
</details></td></tr></table></tr></tbody></table><hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `custom_suggestions` tool scans the PR code changes, and automatically generates custom suggestions for improving the PR code.

Unlike the `improve` tool, which offers more general suggestion according to a pre-configured set of rules, the `custom_suggestions` tool will only propose suggestion that follow specific guidelines defined by the prompt in: `pr_custom_suggestions.prompt` configuration.

The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on a PR.
When commenting, use the following template:

```
/custom_suggestions --pr_custom_suggestions.prompt="The suggestions should focus only on the following:\n-...\n-...\n-..."
```

With a https://pr-agent-docs.codium.ai/usage-guide/configuration_options/, use the following template:

```
[pr_custom_suggestions]
prompt="""\
The suggestions should focus only on the following:
-...
-...
-...
"""
```
Using a configuration file is recommended, since it allows to use multi-line instructions.

Don't forget - with this tool, you are the prompter. Be specific, clear, and concise in the instructions. Specify relevant aspects that you want the model to focus on. You might benefit from several trial-and-error iterations, until you get the correct prompt for your use case.


<table>

<tr><td><details> <summary><strong> Example usage</strong></summary><hr> 

Here is an example for a possible prompt:
```
[pr_custom_suggestions]
prompt="""\
The suggestions should focus only on the following:
- look for edge cases when implementing a new function
- make sure every variable has a meaningful name
- make sure the code is efficient
"""
```     

The instructions above are just an example. We want to emphasize that the prompt should be specific and clear, and be tailored to the needs of your project.

</details></td></tr>



<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://pr-agent-docs.codium.ai/tools/) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 


</details></td></tr>

</table>

See the [custom suggestions](https://pr-agent-docs.codium.ai/tools/custom_suggestions/) usage page for a more comprehensive guide on using this tool.


</details>

**Comment by hussam789** [comment]
/review
--pr_reviewer.inline_code_comments=true
--pr_reviewer.num_code_suggestions="4"
--pr_reviewer.extra_instructions="
In the code feedback section, emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
"
--pr_reviewer.require_score_review=true

**Comment by hussam789** [comment]
/improve
--pr_code_suggestions.summarize=false
--pr_code_suggestions.num_code_suggestions="2"
--pr_reviewer.extra_instructions="
In the code feedback section, emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
"

**Comment by hussam789** [comment]
/checks https://github.com/Codium-ai/codium-proxy/actions/runs/8649180619

**Comment by hussam789** [comment]
/checks "https://github.com/Codium-ai/codium-proxy/actions/runs/8649180619"

**Pull request merged**
