### PR TITLE
Introduce collapsible_file_list_threshold in the configuration file

### PR DESCRIPTION
**Pull request by KennyDizi**
## **User description**
- Configurable collapsible_file_list_threshold for pr description utility

___

## **Type**
enhancement, documentation

___

## **Description**
- Introduced a new configuration option `collapsible_file_list_threshold` to dynamically adjust the threshold for making the file list collapsible.
- Updated the PR description utility to use the new `collapsible_file_list_threshold` from the settings.
- Added documentation for the new configuration option in `DESCRIBE.md`.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_description.py</strong><dd><code>Enhance Collapsible File List Logic with Configurable Threshold</code></dd></summary>
<hr>
      
pr_agent/tools/pr_description.py

<li>Adapted the collapsible file list logic to use a configurable <br>threshold from the settings.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/706/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>DESCRIBE.md</strong><dd><code>Document `collapsible_file_list_threshold` Configuration Option</code></dd></summary>
<hr>
      
docs/DESCRIBE.md

<li>Added documentation for the new <code>collapsible_file_list_threshold</code> <br>configuration option.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/706/files#diff-f82a47dd7df3445231658d38d66bfd57c941dc155090c34d01669d5fc0f75bf9">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add New Configuration Option for Collapsible File List Threshold</code></dd></summary>
<hr>
      
pr_agent/settings/configuration.toml

<li>Introduced a new configuration option <code>collapsible_file_list_threshold</code> <br>with a default value of 8.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/706/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by KennyDizi** [comment]
So that you know, all code suggestions are not necessary.

**Comment by mrT23** [comment]
This PR is not necessary.
Every parameter can be turned into a config one, but it just creates too many config options, that people will never use.

8 is a reasonable number. It does not need to be a config one. The code could be improved a bit, turning the number into a constant, but I don't want it to be a config parameter.

**Comment by KennyDizi** [comment]
You're right; however, it is necessary, at least for me. Sometimes, we need more files than 8. Thus, it would be great if this PR could be merged because we added the 'collapsible_file_list_threshold` into `DESCRIBE.md` so users should not be confused.

**Comment by mrT23** [comment]
For your own use, you can have local docker, where you can do any code change you want.

I read the PR, considered it, and decided it does not appeal to enough people.

If you do want to merge something, do the change I wrote - change 8 to a constant.

sorry

**Comment by KennyDizi** [comment]
> For your own use, you can have local docker, where you can do any code change you want.
> 
> I read the PR, considered it, and decided it does not appeal to enough people.
> 
> If you do want to merge something, do the change I wrote - change 8 to a constant.
> 
> sorry

Sure, I'll change it to constant as you mentioned above, that's also fine 👍

**Comment by mrT23** [comment]
do it in a new PR. it should be a very short one

**Comment by KennyDizi** [comment]
@mrT23 here we go https://github.com/Codium-ai/pr-agent/pull/707

**Pull request closed without merging**
