### PR TITLE
Add support for new Claude models and update dependencies


### PR DESCRIPTION
**Pull request by KennyDizi**
### **PR Type**
Feature, Dependencies

___

### **Description**
- Added support for the `vertex_ai/claude-3-5-sonnet-v2@20241022` model.
- Added support for the `anthropic/claude-3-5-sonnet-20241022` model.
- Added support for the `bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0` model.
- Updated `anthropic` library to version `0.37.1` to support new models.
- Updated `litellm` library to version `1.50.2` to support new models.
- Updated `openai` library to version `1.52.1`.

___

### **Changes walkthrough** 
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Feature</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add support for new Claude models</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/__init__.py

<li>Added support for <code>vertex_ai/claude-3-5-sonnet-v2@20241022</code> model.<br> <li> Added support for <code>anthropic/claude-3-5-sonnet-20241022</code> model.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1302/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692b">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Update dependencies for model support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt

<li>Updated <code>anthropic</code> library to version <code>0.37.1</code>.<br> <li> Updated <code>litellm</code> library to version <code>1.50.2</code>.<br> <li> Updated <code>openai</code> library to version <code>1.52.1</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1302/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by KennyDizi** [comment]
💥 🌄 The **[PR description](https://github.com/Codium-ai/pr-agent/pull/1302)** has been updated to align with the latest commit (https://github.com/Codium-ai/pr-agent/commit/a95755426254389a3fca6d2e35e9223a7e6fc884).

**Comment by KennyDizi** [comment]
## PR Analysis 🌍

🌎 🌆 Here are some essential notes to support our PR review process:

<table>
<tr><td><br>⏰ &nbsp;<strong>Estimated effort to review</strong> 2, because the changes primarily involve adding new model support and updating dependencies, which are straightforward but require verification of compatibility and functionality.</td></tr><tr><td><br>🥇 &nbsp;<strong>Score</strong> 85, because the PR effectively introduces new model support and updates dependencies, but lacks accompanying tests or documentation updates to ensure seamless integration.</td></tr><tr><td><br>🧪 &nbsp;<strong>No relevant tests</strong></td></tr><tr><td><br>🔒 &nbsp;<strong>No security concerns identified</strong> </td></tr><tr><td><br>🥳&nbsp;<strong>Recommended focus areas for review</strong><br>

<a href='https://github.com/Codium-ai/pr-agent/pull/1302/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692bR37-R48'><strong>Dependency Array</strong></a><br>Ensure that the newly added models `'vertex_ai/claude-3-5-sonnet-v2@20241022'` and `'anthropic/claude-3-5-sonnet-20241022'` are correctly integrated and that their token limits are appropriate.

<a href='https://github.com/Codium-ai/pr-agent/pull/1302/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R2-R16'><strong>Dependency Update</strong></a><br>Verify that the updated dependencies (`anthropic`, `litellm`, and `openai`) are compatible with the existing codebase and do not introduce any breaking changes.

</td></tr></table>

**Comment by KennyDizi** [comment]
Tested on local, it works out.

**Comment by mrT23** [comment]
Thanks for the PR.

We had some issues in the past with upgrading litellm. It's not always a seamless process (the last upgrade broke vllm integration)

So, I want to test it for a day or two to be sure it's stable.

**Review by mrT23 — APPROVED** [review]

**Pull request merged**
