### PR TITLE
feat: enhance code review output with collapsible code snippets 

### PR DESCRIPTION
**Pull request by mrT23**
### **User description**
…ariable links

___

### **PR Type**
Enhancement

___

### **Description**
- Enhanced PR review output with collapsible code snippets using <details> tags
- Added clickable links to variables in issue content for better navigation
- Implemented file language detection and code snippet extraction functionality
- Refactored code by moving file language detection to a separate utility function
- Updated key issues description to focus on high-priority concerns

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Enhanced markdown output with code snippets and variable links</code></dd></summary>
<hr>

pr_agent/algo/utils.py

<li>Added collapsible code snippets in review output using <details> tags<br> <li> Added variable links in issue content with reference links<br> <li> Added new function <code>extract_relevant_lines_str()</code> to extract code <br>snippets<br> <li> Added <code>set_file_languages()</code> function to determine file languages<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1403/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+71/-13</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Refactored file language detection logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/github_provider.py

<li>Moved file language detection logic to utils.py<br> <li> Imported and used new <code>set_file_languages()</code> function<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1403/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+2/-13</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Added support for code snippets in PR review</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_reviewer.py

<li>Added files parameter to convert_to_markdown_v2 call to support code <br>snippets<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1403/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer_prompts.toml</strong><dd><code>Updated key issues description in reviewer prompts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_reviewer_prompts.toml

<li>Updated description for key_issues_to_review field to emphasize <br>high-priority issues<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1403/files#diff-2e1ca45d2d8635b5f9cde801d9d210f6516e7f15d45dd9b0be134ac91e7a2e63">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1403#issuecomment-2555517071)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/7e8361b5fde6ff7ef53ed4260ad03deaafbd2654

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1403#issuecomment-2555517071)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/7e8361b5fde6ff7ef53ed4260ad03deaafbd2654

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1403#issuecomment-2555517071)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/7e8361b5fde6ff7ef53ed4260ad03deaafbd2654

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1403#issuecomment-2555517071)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/7e8361b5fde6ff7ef53ed4260ad03deaafbd2654

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1403#issuecomment-2555517071)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/7e8361b5fde6ff7ef53ed4260ad03deaafbd2654

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1403#issuecomment-2555517071)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/989670b1598f1271e2d5603d84a86f7adc4d9ef0

**Comment by mrT23** [comment]
Preparing review...

**Review by hussam789 — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1403#issuecomment-2555517071)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/c2f1f2dba0cf6b8fd2fab7927032ba1d39cdcdc2

**Pull request merged**
