### PR TITLE
Fix base url not being passed through github_provider class correctly

### PR DESCRIPTION
**Pull request by squinn1**
### **User description**
- the base_url and base_url_html attributes were not being fully passed through the code 
- this pr fixes that and removes the hard coded github.com references throughout the code

all unit tests passing 

image

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Fixed issue where `base_url` and `base_url_html` attributes were not being correctly used throughout the `GitHubProvider` class.
- Refactored `_parse_pr_url` and `_parse_issue_url` methods from static to instance methods to access `self.base_url`.
- Updated `get_lines_link_original_file` method to use `self.base_url_html` instead of hardcoded 'github.com'.
- Removed hardcoded references to 'github.com' and 'api.github.com' throughout the code.
- These changes improve flexibility and allow the class to work with different GitHub instances or Enterprise GitHub setups.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Refactor GitHub provider to use instance-specific base URLs</code></dd></summary>
<hr>

pr_agent/git_providers/github_provider.py

<li>Replaced static methods with instance methods for <code>_parse_pr_url</code> and <br><code>_parse_issue_url</code><br> <li> Updated URL parsing to use <code>self.base_url</code> instead of hardcoded <br>'api.github.com'<br> <li> Modified <code>get_lines_link_original_file</code> to use <code>self.base_url_html</code> <br>instead of hardcoded 'github.com'<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1127/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+5/-7</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
thanks, i will review it later today

**Comment by mrT23** [comment]
@squinn1 
The changes seem solid.
Have you validated in your environment that you are getting the correct values ?

**Comment by squinn1** [comment]
Hi @mrT23, 
yeah I have spotted my error now, I needed to extract the domain correctly, I have added in this fix by parsing in the init. let me know if you would prefer this done within the methods etc 

Thanks

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
yes, this was the problem, the 'https'

**Pull request merged**
