### PR TITLE
Minor Typos Fix in Prompt Files

### PR DESCRIPTION
**Pull request by zmeir**
Type of PR:
**Bug fix**

___
PR Description:
**This PR addresses minor typographical errors in the prompts of two settings files. The changes are aimed at improving the clarity and correctness of the instructions provided in the prompts.**

___
PR Main Files Walkthrough:
- `pr_agent/settings/pr_code_suggestions_prompts.toml`: A repeated word 'provide' was removed from the prompt instructions.
- `pr_agent/settings/pr_reviewer_prompts.toml`: A repeated word 'provide' was removed from the prompt instructions.

### CODE REVIEW

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
👍

**Review by okotek — APPROVED** [review]

**Comment by okotek** [comment]
@zmeir check out the new describe command, it changed the title and description of this PR. 
/review

**Comment by zmeir** [comment]
> @zmeir check out the new describe command, it changed the title and description of this PR.

@okotek very cool! Although, the description for `pr_agent/settings/pr_reviewer_prompts.toml` is wrong... :(

**Pull request merged**
