### PR TITLE
Enhancements to Logging, Help Messages, and PR Descriptions and Reviews

### PR DESCRIPTION
**Pull request by mrT23**
## Type
Enhancement

___

## Description
- The logging level for certain messages in `git_provider.py` has been changed from debug to info.
- The help messages and usage guides for the different tools have been significantly expanded and improved in `help.py`.
- The PR description now includes a help text section if gfm_markdown is supported. This is controlled by the `enable_help_text` configuration setting in `pr_description.py`.
- The PR review now includes a help text section if gfm_markdown is supported. This is controlled by the `enable_help_text` configuration setting in `pr_reviewer.py`.
- Several typos and phrasing issues in the documentation files `DESCRIBE.md`, `IMPROVE.md`, and `REVIEW.md` have been fixed.
- A new configuration setting `enable_help_text` has been added to the `pr_description` section in `configuration.toml`.

___

## Changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Miscellaneous</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>git_provider.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/git_providers/git_provider.py<br><br>

**The logging level for certain messages has been changed from <br>debug to info. This includes messages related to the <br>extraction of user descriptions and the detection of <br>descriptions generated by the pr-agent.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/579/files#diff-52d45f12b836f77ed1aef86e972e65404634ea4e2a6083fb71a9b0f9bb9e062f"> +4/-4</a></td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>help.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/servers/help.py<br><br>

**The help messages and usage guides for the different tools <br>have been significantly expanded and improved. This includes <br>the addition of a new `HelpMessage` class with methods for <br>generating help text for general commands, review usage, and <br>describe usage.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/579/files#diff-aa5878a57c5e6e9436d73b8c8d1e78a443f2f09d829303040b463f7fba89f1d8"> +174/-8</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>DESCRIBE.md&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        docs/DESCRIBE.md<br><br>

**A typo in the custom labels example has been fixed. The <br>label `Main topic:performence` has been corrected to `Main <br>topic:performance`.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/579/files#diff-f82a47dd7df3445231658d38d66bfd57c941dc155090c34d01669d5fc0f75bf9"> +2/-2</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>IMPROVE.md&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        docs/IMPROVE.md<br><br>

**A typo in the extra instructions example has been fixed. The <br>phrase `Does the code logic covers relevant edge cases?` has <br>been corrected to `Does the code logic cover relevant edge <br>cases?`.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/579/files#diff-c5fc63e45a597a7f6a34800dfff364ab2a4052648308fe63e070f3e5befda275"> +1/-1</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>REVIEW.md&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        docs/REVIEW.md<br><br>

**Several typos and phrasing issues in the document have been <br>fixed. This includes corrections in the examples for extra <br>instructions and the descriptions for auto-labels and extra <br>instructions.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/579/files#diff-a4b80781c151b79bd3d7acfe9d62ba33f793740839dcf46a4c98d037ec7db24d"> +3/-3</a></td>

</tr>                    
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_description.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/tools/pr_description.py<br><br>

**The PR description now includes a help text section if <br>gfm_markdown is supported. This is controlled by the <br>`enable_help_text` configuration setting. The help text is <br>generated using the `get_describe_usage_guide` method from <br>the `HelpMessage` class.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/579/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb"> +9/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/tools/pr_reviewer.py<br><br>

**The PR review now includes a help text section if <br>gfm_markdown is supported. This is controlled by the <br>`enable_help_text` configuration setting. The help text is <br>generated using the `get_review_usage_guide` method from the <br>`HelpMessage` class.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/579/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc"> +3/-8</a></td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/settings/configuration.toml<br><br>

**A new configuration setting `enable_help_text` has been <br>added to the `pr_description` section. This setting controls <br>whether to include a help text section in the PR <br>description.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/579/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78"> +1/-0</a></td>

</tr>                    
</table></td></tr></tr></tbody></table><hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `describe` tool scans the PR code changes, and generates a description for the PR - title, type, summary, walkthrough and labels. The tool can be triggered [automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) every time a new PR is opened, or can be invoked manually by commenting on a PR.

When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L46) related to the describe tool (`pr_description` section), use the following template:
```
/describe --pr_description.some_config1=... --pr_description.some_config2=...
```
With a [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app), use the following template:
```
[pr_description]
some_config1=...
some_config2=...
```

<table><tr><td><details> <summary><strong> Enabling\disabling automation </strong></summary><hr>

- When you first install the app, the [default mode](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) for the describe tool is:
```
pr_commands = ["/describe --pr_description.add_original_user_description=true" 
                         "--pr_description.keep_original_user_title=true", ...]
```
meaning the `describe` tool will run automatically on every PR, will keep the original title, and will add the original user description above the generated description. 

- Markers are an alternative way to control the generated description, to give maximal control to the user. If you set:
```
pr_commands = ["/describe --pr_description.use_description_markers=true", ...]
```
the tool will replace every marker of the form `pr_agent:marker_name` in the PR description with the relevant content, where `marker_name` is one of the following:
  - `type`: the PR type.
  - `summary`: the PR summary.
  - `walkthrough`: the PR walkthrough.

Note that when markers are enabled, if the original PR description does not contain any markers, the tool will not alter the description at all.
        

</details></td></tr>

<tr><td><details> <summary><strong> Custom labels </strong></summary><hr>

The default labels of the `describe` tool are quite generic: [`Bug fix`, `Tests`, `Enhancement`, `Documentation`, `Other`].

If you specify [custom labels](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md#handle-custom-labels-from-the-repos-labels-page-gem) in the repo's labels page or via configuration file, you can get tailored labels for your use cases.
Examples for custom labels:
- `Main topic:performance` - pr_agent:The main topic of this PR is performance
- `New endpoint` - pr_agent:A new endpoint was added in this PR
- `SQL query` - pr_agent:A new SQL query was added in this PR
- `Dockerfile changes` - pr_agent:The PR contains changes in the Dockerfile
- ...

The list above is eclectic, and aims to give an idea of different possibilities. Define custom labels that are relevant for your repo and use cases.
Note that Labels are not mutually exclusive, so you can add multiple label categories.
Make sure to provide proper title, and a detailed and well-phrased description for each label, so the tool will know when to suggest it.        

</details></td></tr>

<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 

</details></td></tr>

</table>

See the [describe usage](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md) page for a comprehensive guide on using this tool.

</details>

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/579#issuecomment-1880115949)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/9cfb8ce4758798a9405f72294b3ec923c137498a

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/579)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/9cfb8ce4758798a9405f72294b3ec923c137498a)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/579)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/8bb2eb48af5408a3c942ddb16a6bd74a715afce6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/579)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/8bb2eb48af5408a3c942ddb16a6bd74a715afce6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/579)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/8bb2eb48af5408a3c942ddb16a6bd74a715afce6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/579)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/8bb2eb48af5408a3c942ddb16a6bd74a715afce6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/579)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/8bb2eb48af5408a3c942ddb16a6bd74a715afce6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/579)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/8bb2eb48af5408a3c942ddb16a6bd74a715afce6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/579)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/8bb2eb48af5408a3c942ddb16a6bd74a715afce6)

**Comment by mrT23** [comment]
Preparing PR description...

**Review by barnett-yuxiang — COMMENTED** [review]
LGTM

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
## PR Code Suggestions


💡 [best practice]

**Consider using a docstring for each method in the `HelpMessage` class to describe what each method does. This will improve the readability and maintainability of your code.**

 File: [pr_agent/servers/help.py (1-7)](https://github.com/Codium-ai/pr-agent/pull/579/files#diff-aa5878a57c5e6e9436d73b8c8d1e78a443f2f09d829303040b463f7fba89f1d8R1-R7)

<details> <summary> Example code:</summary>

___

Existing code:
```python
class HelpMessage:
    @staticmethod
    def get_general_commands_text():
        commands_text = "> - **/review**: Request a review of your Pull Request.   \n" \
                        "> - **/describe**: Update the PR title and description based on the contents of the PR.   \n" \
                        "> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   \n" \
                        "> - **/ask \\<QUESTION\\>**: Ask a question about the PR.   \n" \
        return commands_text
```
Improved code:
```python
class HelpMessage:
    @staticmethod
    def get_general_commands_text():
        """
        Returns a string containing the general commands text.
        """
        commands_text = "> - **/review**: Request a review of your Pull Request.   \n" \
                        "> - **/describe**: Update the PR title and description based on the contents of the PR.   \n" \
                        "> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   \n" \
                        "> - **/ask \\<QUESTION\\>**: Ask a question about the PR.   \n" \
        return commands_text
```
</details>

___


💡 [enhancement]

**Consider using a more descriptive logging message in the `get_user_description` method. This will make it easier to understand the context when reading the logs.**

 File: [pr_agent/git_providers/git_provider.py (78-78)](https://github.com/Codium-ai/pr-agent/pull/579/files#diff-52d45f12b836f77ed1aef86e972e65404634ea4e2a6083fb71a9b0f9bb9e062fR78-R78)

<details> <summary> Example code:</summary>

___

Existing code:
```python
get_logger().info(f"Existing description:\n{description_lowercase}")
```
Improved code:
```python
get_logger().info(f"Existing PR description:\n{description_lowercase}")
```
</details>

___


💡 [best practice]

**Consider removing the unused import `from pr_agent.servers.help import HelpMessage`. This will improve the readability and maintainability of your code.**

 File: [pr_agent/tools/pr_reviewer.py (20-20)](https://github.com/Codium-ai/pr-agent/pull/579/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dcR20-R20)

<details> <summary> Example code:</summary>

___

Existing code:
```python
from pr_agent.servers.help import HelpMessage
```
Improved code:
```python
# Removed unused import
```
</details>

___


💡 [best practice]

**Consider adding a space after the comma in the tuple assignment `pr_title, pr_body,  = self._prepare_pr_answer()`. This will improve the readability of your code.**

 File: [pr_agent/tools/pr_description.py (101-101)](https://github.com/Codium-ai/pr-agent/pull/579/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abbR101-R101)

<details> <summary> Example code:</summary>

___

Existing code:
```python
pr_title, pr_body,  = self._prepare_pr_answer()
```
Improved code:
```python
pr_title, pr_body = self._prepare_pr_answer()
```
</details>

___

**Comment by mrT23** [comment]
Preparing suggestions...

**Comment by mrT23** [comment]
## PR Code Suggestions


💡 [readability]

**Consider using a multi-line string for the `commands_text` in the `get_general_commands_text` method to improve readability.**

 File: [pr_agent/servers/help.py (4-7)](https://github.com/Codium-ai/pr-agent/pull/579/files#diff-aa5878a57c5e6e9436d73b8c8d1e78a443f2f09d829303040b463f7fba89f1d8R4-R7)

<details> <summary> Example code:</summary>

___

Existing code:
```python
commands_text = "> - **/review**: Request a review of your Pull Request.   \n" \
                "> - **/describe**: Update the PR title and description based on the contents of the PR.   \n" \
                "> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   \n" \
                "> - **/ask \\<QUESTION\\>**: Ask a question about the PR.   \n"
```
Improved code:
```python
commands_text = """
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \\<QUESTION\\>**: Ask a question about the PR.   
"""
```
</details>

___


💡 [best practice]

**Consider changing the log level from `info` to `debug` in the `get_user_description` method. This information seems more relevant for debugging purposes rather than regular operation information.**

 File: [pr_agent/git_providers/git_provider.py (78-112)](https://github.com/Codium-ai/pr-agent/pull/579/files#diff-52d45f12b836f77ed1aef86e972e65404634ea4e2a6083fb71a9b0f9bb9e062fR78-R112)

<details> <summary> Example code:</summary>

___

Existing code:
```python
get_logger().info(f"Existing description:\n{description_lowercase}")
...
get_logger().info(f"Existing description was not generated by the pr-agent")
...
get_logger().info(f"Existing description was generated by the pr-agent, but it doesn't contain a user description")
...
get_logger().info(f"Extracted user description from existing description:\n{original_user_description}")
```
Improved code:
```python
get_logger().debug(f"Existing description:\n{description_lowercase}")
...
get_logger().debug(f"Existing description was not generated by the pr-agent")
...
get_logger().debug(f"Existing description was generated by the pr-agent, but it doesn't contain a user description")
...
get_logger().debug(f"Extracted user description from existing description:\n{original_user_description}")
```
</details>

___


💡 [readability]

**Consider using a multi-line string for the `markdown_text` in the `_prepare_pr_review` method to improve readability.**

 File: [pr_agent/tools/pr_reviewer.py (255-257)](https://github.com/Codium-ai/pr-agent/pull/579/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dcR255-R257)

<details> <summary> Example code:</summary>

___

Existing code:
```python
markdown_text += "<hr>\n\n<details> <summary><strong>✨ Usage guide:</strong></summary><hr> \n\n"
markdown_text += HelpMessage.get_review_usage_guide()
markdown_text += "\n</details>\n"
```
Improved code:
```python
markdown_text += """
<hr>
<details>
  <summary><strong>✨ Usage guide:</strong></summary>
  <hr>
  {HelpMessage.get_review_usage_guide()}
</details>
"""
```
</details>

___


💡 [readability]

**Consider using a multi-line string for the `pr_body` in the `run` method to improve readability.**

 File: [pr_agent/tools/pr_description.py (105-107)](https://github.com/Codium-ai/pr-agent/pull/579/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abbR105-R107)

<details> <summary> Example code:</summary>

___

Existing code:
```python
pr_body += "<hr>\n\n<details> <summary><strong>✨ Usage guide:</strong></summary><hr> \n\n"
pr_body += HelpMessage.get_describe_usage_guide()
pr_body += "\n</details>\n"
```
Improved code:
```python
pr_body += """
<hr>
<details>
  <summary><strong>✨ Usage guide:</strong></summary>
  <hr>
  {HelpMessage.get_describe_usage_guide()}
</details>
"""
```
</details>

___

**Pull request merged**
