### PR TITLE
Centralize PR Review Title Definition

### PR DESCRIPTION
**Pull request by KennyDizi**
### **PR Type**
Enhancement, Tests

___

### **Description**
- Introduced `ReviewHeaderTitle` enum in `pr_agent/algo/utils.py` for centralized title definitions.
- Updated `convert_to_markdown` function to use `ReviewHeaderTitle` enum.
- Applied `ReviewHeaderTitle` enum in `pr_agent/git_providers/github_provider.py` for consistent header titles.
- Modified `pr_agent/tools/pr_reviewer.py` to use `ReviewHeaderTitle` enum for header titles.
- Updated unit tests in `tests/unittest/test_convert_to_markdown.py` to use `ReviewHeaderTitle` enum.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Centralize PR review header titles using `ReviewHeaderTitle` enum</code></dd></summary>
<hr>
      
pr_agent/algo/utils.py

<li>Added <code>ReviewHeaderTitle</code> enum for centralized title definitions.<br> <li> Updated <code>convert_to_markdown</code> function to use <code>ReviewHeaderTitle</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1005/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+6/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Use `ReviewHeaderTitle` enum in GitHub provider</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/git_providers/github_provider.py

<li>Imported <code>ReviewHeaderTitle</code> enum.<br> <li> Updated <code>get_previous_review</code> method to use <code>ReviewHeaderTitle</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1005/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Apply `ReviewHeaderTitle` enum in PR reviewer tool</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/tools/pr_reviewer.py

<li>Imported <code>ReviewHeaderTitle</code> enum.<br> <li> Updated <code>run</code> method to use <code>ReviewHeaderTitle</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1005/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_convert_to_markdown.py</strong><dd><code>Update tests to use `ReviewHeaderTitle` enum</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
tests/unittest/test_convert_to_markdown.py

<li>Imported <code>ReviewHeaderTitle</code> enum.<br> <li> Updated test cases to use <code>ReviewHeaderTitle</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1005/files#diff-48e28c70a7fa0ad268cc0cd35739816da980187199079f2c78eeffff330ce450">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by KennyDizi** [comment]
So far so good.

**Comment by dkangala** [comment]
Preparing review...

**Comment by KennyDizi** [comment]
> Preparing review...

@dkangala how's it going?

**Comment by mrT23** [comment]
@KennyDizi  looks good, and it is a good practice.

**Review by mrT23 — APPROVED** [review]

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Pull request merged**
