### PR TITLE
Tr/describe v2

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Improved patch generation logic, including better handling of large patches and token limits.
- Enhanced error handling and logging across multiple modules, particularly for patch generation and PR description generation.
- Added support for collapsible file lists in PR descriptions, with a configurable threshold.
- Improved diff handling by incorporating merge base commit logic for better accuracy.
- Updated configuration and prompts to align with new features and improvements.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_processing.py</strong><dd><code>Refine patch generation and logging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/pr_processing.py

<li>Improved logging for large patch handling.<br> <li> Fixed formatting issues in patch generation.<br> <li> Enhanced logic for handling large patches and token limits.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1423/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04e">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Improve diff handling and rate limit logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/git_providers/github_provider.py

<li>Added handling for merge base commit to improve diff accuracy.<br> <li> Improved rate limit handling and file content loading logic.<br> <li> Enhanced logic for counting added and removed lines in patches.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1423/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+50/-39</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>pr_description.py</strong><dd><code>Enhance PR description generation and file handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/tools/pr_description.py

<li>Added logic to handle collapsible file lists based on thresholds.<br> <li> Improved error handling and logging for PR description generation.<br> <li> Enhanced prediction extension for uncovered files.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1423/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb">+143/-67</a></td>

</tr>
</table></td></tr><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Enhance patch generation error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/utils.py

<li>Improved error handling and logging for patch generation.<br> <li> Simplified logic for empty file content scenarios.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1423/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+8/-15</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Update configuration for collapsible file lists</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/configuration.toml

<li>Added <code>collapsible_file_list_threshold</code> configuration.<br> <li> Removed <code>mention_extra_files</code> configuration.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1423/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_description_prompts.toml</strong><dd><code>Refine PR description prompts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/settings/pr_description_prompts.toml

<li>Adjusted prompts to include file paths and summaries.<br> <li> Improved instructions for YAML output generation.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1423/files#diff-a52546bc2f8a156d8ee786c403e44b1561a6e3f1d98fcfbe8a0120bcee59981b">+10/-16</a>&nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1423)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/e95920c58cc762b62a6b12bd35d064fbf4531dd6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/1423)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/e95920c58cc762b62a6b12bd35d064fbf4531dd6)

**Review by hussam789 — APPROVED** [review]

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
/help Hi everyone,
I’m encountering an issue with the PR Agent GitHub Action

Error Message:

Error during LLM inference: litellm.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model `gpt-4o-2024-11-20` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}


What I’ve Tried:
Updated the GitHub Actions Workflow:
env:
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_AGENT_MODEL: "gpt-4o-mini-2024-07-18"
  PR_AGENT_FALLBACK_MODELS: "gpt-3.5-turbo-16k"
  verbosity_level: "2"
  github_action_config.auto_review: "true"
  github_action_config.auto_describe: "true"
  github_action_config.auto_improve: "true"


I suspect the PR Agent is prioritizing a configuration file (e.g., .pr-agent.yaml or configuration.toml) over the environment variables, but I’m not sure how to confirm this.
I verified that my OpenAI API key works and has access to the models gpt-4o-mini-2024-07-18 and gpt-3.5-turbo-16k.

Any help or guidance would be greatly appreciated! Let me know if you need more details or additional logs.

**Pull request merged**
