### PR TITLE
Enhancement of Persistent Comments in PR Review

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Enhancement

___
## PR Description:
This PR introduces several enhancements to the persistent comments feature in PR reviews:
- The persistent comments now include a link to the latest commit and the comment URL.
- The comments are updated with the latest review message in persistent mode.
- The verbosity level of the AI response and prediction has been increased.
- The configuration documentation has been updated to reflect these changes.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `pr_agent/algo/pr_processing.py`: Added a check to ensure the filename exists before comparing it with the relevant file.
- `pr_agent/git_providers/bitbucket_provider.py`: Updated the publish_persistent_comment method to include the latest commit URL and comment URL.
- `pr_agent/git_providers/git_provider.py`: Reorganized the methods and added new methods for getting the latest commit URL and comment URL.
- `pr_agent/git_providers/github_provider.py`: Updated the publish_persistent_comment method to include the latest commit URL and comment URL.
- `pr_agent/git_providers/gitlab_provider.py`: Updated the publish_persistent_comment method to include the latest commit URL and comment URL.
- `pr_agent/tools/pr_description.py`: Increased the verbosity level of the AI response and prediction.
- `pr_agent/tools/pr_reviewer.py`: Updated the publish_persistent_comment method to include the latest commit URL and comment URL.
- `docs/REVIEW.md`: Updated the documentation to reflect the changes in the persistent comments feature.
</details>

## Examples
image

image

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/451#issuecomment-1811913639)** updated  to latest commit https://github.com/Codium-ai/pr-agent/commit/94cb6b9795df1ea2a5c95d7c3a21a145a8c0a557

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/451#issuecomment-1811913639)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/c4899a6c5403cfdac3589119bed227dba921e164

**Comment by mrT23** [comment]
Preparing review...

**Review by hussam789 — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Pull request merged**
