### PR TITLE
increase margins

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
enhancement

___

### **Description**
- Increased `OUTPUT_BUFFER_TOKENS_SOFT_THRESHOLD` from 1000 to 1500 to allow more tokens in the output buffer before soft limiting.
- Increased `OUTPUT_BUFFER_TOKENS_HARD_THRESHOLD` from 600 to 1000 to allow more tokens in the output buffer before hard limiting.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_processing.py</strong><dd><code>Increase token buffer thresholds for output processing</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/pr_processing.py

<li>Increased <code>OUTPUT_BUFFER_TOKENS_SOFT_THRESHOLD</code> from 1000 to 1500.<br> <li> Increased <code>OUTPUT_BUFFER_TOKENS_HARD_THRESHOLD</code> from 600 to 1000.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1021/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04e">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1021#issuecomment-2206899456)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/2235a1934521c40720eddb84fa3af1232b894145

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
