### PR TITLE
Add documentation portal

### PR DESCRIPTION
**Pull request by almog-lv**
## **User description**
- Added all documentation portal files to /docs
- Removed previous docs files
- Added docs-ci workflow after every push to main AND change in docs/** path
- Added GitHub pages settings to pr-agent project

___

## **Type**
enhancement, documentation

___

## **Description**
- Added a source map for the main CSS file to aid in debugging and development.
- Implemented a custom footer for the documentation site, including social media links and a responsive design.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>main.7e359304.min.css.map</strong><dd><code>Add Source Map for Main CSS File</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
docs/site/assets/stylesheets/main.7e359304.min.css.map

<li>Added a source map for the main CSS file, improving developer tools' <br>ability to map the minified CSS back to its source files.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/750/files#diff-1127bfc5ba3d57b16a515a0e58e94e721b5844d153bd1488ddb3154db5ff91c5">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>footer.html</strong><dd><code>Implement Custom Footer with Social Links for Documentation Site</code></dd></summary>
<hr>
      
docs/overrides/partials/footer.html

<li>Introduced a new custom footer for the documentation site.<br> <li> Added social media links (GitHub, Discord, YouTube, LinkedIn, Twitter, <br>Instagram) with respective icons.<br> <li> Styled the footer with a dark theme and responsive design.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/750/files#diff-5f1cf3f3c2addb68e4ef5a900b7c6f3257d3d9dc4009bf7b2291237d6978aa7c">+100/-0</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by 971800718** [comment]
@CodiumAI-Agent /review

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/750#issuecomment-1982622256)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/750#issuecomment-1982622256)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/750#issuecomment-1982622256)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/750#issuecomment-1982622256)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/750/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/750/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/750/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/750/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/750/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

- [ ] Copy walkthrough table to ["Files Changed"](https://github.com/Codium-ai/pr-agent/pull/750/files) Tab

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/750)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/05b0c4ff70e546527a58ba877e8062890e8302a6)

**Comment by hussam789** [comment]
@CodiumAI-Agent /describe

**Comment by hussam789** [comment]
/checks
"https://github.com/Codium-ai/pr-agent/actions/runs/10468139000/job/28988359407"

**Pull request closed without merging**
