### PR TITLE
Qodo Merge rename

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
Documentation

___

### **Description**
- Rebranded PR-Agent to Qodo Merge throughout the documentation
- Updated all instances of 'PR-Agent Pro' to 'Qodo Merge Pro'
- Changed documentation URLs from 'pr-agent-docs.codium.ai' to 'qodo-merge-docs.qodo.ai'
- Updated references to the Chrome extension name
- Revised content in various documentation files to reflect the new branding
- Maintained functionality descriptions while updating the product name
- Ensured consistency in the new branding across all affected files

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><details><summary>15 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Update documentation portal URL</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/README.md

<li>Updated the URL for the documentation portal from <br>'pr-agent-docs.codium.ai' to 'qodo Merge-docs.codium.ai'<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>data_privacy.md</strong><dd><code>Rename PR-Agent Pro to Qodo Merge Pro</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/chrome-extension/data_privacy.md

- Changed 'PR-Agent Pro' to 'Qodo Merge Pro'

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-f3146908ad857dd01c19d21f970fe45d188111f4dc7bc3e4c00385c9e241f572">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>features.md</strong><dd><code>Rebrand PR-Agent to Qodo Merge in features documentation</code>&nbsp; </dd></summary>
<hr>

docs/docs/chrome-extension/features.md

<li>Replaced all instances of 'PR-Agent' with 'Qodo Merge'<br> <li> Updated references to documentation URLs<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-97f38891a224130906b208e402f9d9ae64991e8bd3923a96b42eeeaea2fd8f35">+8/-8</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Rebrand Chrome extension to Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/chrome-extension/index.md

<li>Updated Chrome extension name from 'PR-Agent' to 'Qodo Merge'<br> <li> Changed 'PR-Agent Pro' to 'Qodo Merge Pro'<br> <li> Updated documentation URLs<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-052310646b198613231d84e8cccef3d7d104ea83b60bd385f6f1ec82e0170708">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>dynamic_context.md</strong><dd><code>Update dynamic context documentation for Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/core-abilities/dynamic_context.md

- Replaced 'PR-Agent' with 'Qodo Merge' throughout the document

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-6571f9a3afc69f232a408e2f8296113f3a7fd7597836972a775645c64c1ab195">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>impact_evaluation.md</strong><dd><code>Rebrand impact evaluation documentation to Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/core-abilities/impact_evaluation.md

<li>Replaced all instances of 'PR-Agent' with 'Qodo Merge'<br> <li> Updated references to documentation URLs<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-a52038ee4f8dcd8d555059d7ac6c8359c976bb03ff5f0cb489c9dae6631db6bd">+13/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Update core abilities index for Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/core-abilities/index.md

<li>Changed 'PR-Agent' to 'Qodo Merge' in the introduction<br> <li> Updated all documentation URLs to use 'qodo-merge-docs.qodo.ai' domain<br> <br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-a227d8509d77d7fbf58c4223c4eb3dc609cc4598877d4f2361960128bb00172c">+10/-10</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>metadata.md</strong><dd><code>Rebrand metadata documentation to Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/core-abilities/metadata.md

<li>Replaced all instances of 'PR-Agent' with 'Qodo Merge'<br> <li> Updated documentation URLs to use 'qodo-merge-docs.qodo.ai' domain<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-62d5b6af5c6e9edd3f7d8658a41acbd1d54267e7cd5e2e253f096cfc6831e264">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>self_reflection.md</strong><dd><code>Update self-reflection documentation for Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/core-abilities/self_reflection.md

- Changed 'PR-Agent' to 'Qodo Merge' throughout the document

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-79cc970179190440b665fa49f76dd84a39aaed44ba4ae15db2f585871b958a74">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>static_code_analysis.md</strong><dd><code>Rebrand static code analysis documentation to Qodo Merge</code>&nbsp; </dd></summary>
<hr>

docs/docs/core-abilities/static_code_analysis.md

<li>Replaced 'PR-Agent' with 'Qodo Merge' in the overview section<br> <li> Updated documentation URLs to use 'qodo-merge-docs.qodo.ai' domain<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-6c7f441b10a6bdc5ca009d6705d944a68d9ade94a82a762afa2538c59c245876">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Update FAQ for Qodo Merge rebranding</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/faq/index.md

<li>Updated all instances of 'PR-Agent' to 'Qodo Merge'<br> <li> Changed 'PR-Agent Pro' to 'Qodo Merge Pro'<br> <li> Updated documentation URLs to use 'qodo-merge-docs.qodo.ai' domain<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-3da72c80c0b0818b033e74a8b107fd4b017ccfa2d8b498a32652bcbdd41837ae">+11/-11</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Rebrand fine-tuning benchmark to Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/finetuning_benchmark/index.md

<li>Changed 'PR-Agent' to 'Qodo Merge' in the title and throughout the <br>document<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-5e714a5152aaf543d6e3300ab3e408d86232f3c813742e2bd3d2ea2ce81e8741">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.md</strong><dd><code>Update main documentation index for Qodo Merge rebranding</code></dd></summary>
<hr>

docs/docs/index.md

<li>Replaced all instances of 'PR-Agent' with 'Qodo Merge'<br> <li> Updated 'PR-Agent Pro' to 'Qodo Merge Pro'<br> <li> Changed documentation URLs to use 'qodo-merge-docs.qodo.ai' domain<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-7dd3ba15306fb8ca0c3fa4a2e10b4d3b708c3a338bc2c4a028b4e1d0e565dc88">+14/-14</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>azure.md</strong><dd><code>Update Azure DevOps installation guide for Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/installation/azure.md

<li>Changed 'PR Agent' to 'Qodo Merge' in the pipeline display name<br> <li> Updated image alt text to 'Qodo Merge Pro'<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-8b88870a27016c805466301c6a2fac12c560147538f7bec211eb479b05c46b53">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>bitbucket.md</strong><dd><code>Update BitBucket installation guide for Qodo Merge</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/docs/installation/bitbucket.md

<li>Replaced 'PR-Agent' with 'Qodo Merge' throughout the document<br> <li> Updated 'PR-Agent pro' to 'Qodo Merge Pro'<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1261/files#diff-bb2c864cbe3b39ef39e1470309b83d1bc04b341d83c3d08bab96953c82e5a671">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by hussam789 — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1261#issuecomment-2381375281)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/6c4aa468a9dcd7ccbc06ec805497607a51187e4d

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1261#issuecomment-2381375281)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/6c4aa468a9dcd7ccbc06ec805497607a51187e4d

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1261#issuecomment-2381375281)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/6c4aa468a9dcd7ccbc06ec805497607a51187e4d

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1261#issuecomment-2381375281)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/6c4aa468a9dcd7ccbc06ec805497607a51187e4d

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/1261#issuecomment-2381375281)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/6c4aa468a9dcd7ccbc06ec805497607a51187e4d

**Pull request merged**
