### PR TITLE
update litellm library

### PR DESCRIPTION
**Pull request by R-Mathis**
### **User description**
Update litellm lib to get better support for vertex ai mistral models : https://github.com/BerriAI/litellm/pull/4925

___

### **PR Type**
Enhancement

___

### **Description**
- Upgraded litellm library from version 1.40.17 to 1.43.9 to improve support for Vertex AI Mistral models.
- Added Pydantic version 2.8.2 as a new dependency, which may enhance data validation and settings management.
- These updates aim to improve the project's compatibility and functionality with newer library versions.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Update dependencies and add Pydantic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt

<li>Updated litellm library from version 1.40.17 to 1.43.9<br> <li> Added pydantic version 2.8.2 as a new dependency<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1126/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Why did you add Pydantic to the requirement.text ?

**Comment by R-Mathis** [comment]
> Why did you add Pydantic to the requirement.txt ?

https://pypi.org/project/litellm/

LiteLLM v1.40.14+ now requires pydantic>=2.0.0.

**Comment by hussam789** [comment]
@CodiumAI-Agent /improve

**Comment by hussam789** [comment]
@CodiumAI-Agent /review

**Comment by MarkRx** [comment]
Could you bump up to the latest to get https://github.com/BerriAI/litellm/issues/5179 for #1145

**Comment by R-Mathis** [comment]
@CodiumAI-Agent /review

**Review by mrT23 — APPROVED** [review]

**Pull request merged**
