### PR TITLE
Add Claude 3.5 Haiku Model Support and Update Dependencies

### PR DESCRIPTION
**Pull request by KennyDizi**
### **PR Type**
Dependencies, Enhancement

___

### **Description**
- Added support for the new Claude 3.5 Haiku model across different providers
- Updated multiple project dependencies to their latest versions
- Expanded model token configurations for improved compatibility

___

### **Changes walkthrough** 
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Add Claude 3.5 Haiku Model Token Configurations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/__init__.py

<li>Added support for new Claude 3.5 Haiku model with token limit of <br>100,000<br> <li> Included new model variants for Vertex AI and Anthropic providers<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1345/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692b">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Update Project Dependencies to Latest Versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt

<li>Upgraded Anthropic library from version 0.37.1 to 0.39.0<br> <li> Updated LiteLLM from version 1.50.2 to 1.52.0<br> <li> Updated OpenAI library from version 1.52.1 to 1.54.1<br> <li> Updated Tiktoken from version 0.7.0 to 0.8.0<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1345/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by KennyDizi** [comment]
🌴 🎆 I have synchronized the **[PR description](https://github.com/Codium-ai/pr-agent/pull/1345)** with the latest commit (https://github.com/Codium-ai/pr-agent/commit/c5ed2f040a086c16bf34fc6997dbe24592819ccb).

**Comment by KennyDizi** [comment]
👑 🌔 The **[PR description](https://github.com/Codium-ai/pr-agent/pull/1345)** has been modified to accurately represent the latest commit (https://github.com/Codium-ai/pr-agent/commit/04496f9b0eb2a246ef86ebcb43c228a2525c7524).

**Comment by KennyDizi** [comment]
## PR Analysis 🌗

🌖 🌓 Here are some essential notes to support our PR review process:

<table>
<tr><td><br>⏰ &nbsp;<strong>Estimated effort to review</strong> 2, because the changes primarily involve adding new model support and updating dependencies, which are straightforward but require verification of compatibility and testing.</td></tr><tr><td><br>🥇 &nbsp;<strong>Score</strong> 85, because the PR effectively adds new model support and updates dependencies, but it lacks accompanying tests to ensure the new configurations work as expected.</td></tr><tr><td><br>🧪 &nbsp;<strong>No relevant tests</strong></td></tr><tr><td><br>🔒 &nbsp;<strong>No security concerns identified</strong> </td></tr><tr><td><br>🌆&nbsp;<strong>Recommended focus areas for review</strong><br>

<a href='https://github.com/Codium-ai/pr-agent/pull/1345/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692bR34-R34'><strong>Dependency Array</strong></a><br>Ensure that the new model 'vertex_ai/claude-3-5-haiku@20241022' is correctly integrated and compatible with existing configurations.

<a href='https://github.com/Codium-ai/pr-agent/pull/1345/files#diff-5923c546f24ec7308a0e43fc84bb6fe40de7bfe2ac6ee842da9578e5dc2c692bR52-R52'><strong>Dependency Array</strong></a><br>Verify the addition of 'anthropic/claude-3-5-haiku-20241022' for compatibility and correctness.

<a href='https://github.com/Codium-ai/pr-agent/pull/1345/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R2-R2'><strong>Dependency Update</strong></a><br>Confirm that the updated dependencies do not introduce any breaking changes or compatibility issues.

</td></tr></table>

**Comment by KennyDizi** [comment]
I tested it locally several times, and it works as expected.

**Review by mrT23 — APPROVED** [review]

**Pull request merged**
