### PR TITLE
Make models available not in ./pr_agent/algo/__init__.py

### PR DESCRIPTION
**Pull request by dceoy**
### **PR Type**
enhancement

___

### **Description**
- Enhanced the `get_max_tokens` function in `pr_agent/algo/utils.py` to check `settings.config.max_model_tokens` before raising an exception.
- Updated the exception message to indicate that `MAX_TOKENS` can be set in settings as well.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.py</strong><dd><code>Enhance `get_max_tokens` function to include settings check</code></dd></summary>
<hr>

pr_agent/algo/utils.py

<li>Modified the <code>get_max_tokens</code> function to check <br><code>settings.config.max_model_tokens</code> before raising an exception.<br> <li> Updated the exception message to include settings as a possible source <br>for <code>MAX_TOKENS</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1054/files#diff-6b9df72d53c6f0d89fb142c210238a276c0782305e0024d16fbfcaf72c2e2b53">+3/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by KennyDizi** [comment]
This will break the rule, I guess.

**Comment by mrT23** [comment]
@dceoy 
I understand it might work in some cases, but I am not a fan of this PR as-is

1) `max_model_tokens` has a default value in the config file. So a user will just state a new model (l'mistral_123B ...'), without stating the max_tokens, and the run might crush for him due to lack of tokens. And he won't understand why.

2) some models require extra parameters, keys, .. (see for example watson models in https://github.com/Codium-ai/pr-agent/pull/1047). Again, not taking care of it in the code might results in a crush.

Hence, I am hesitant to approve this PR.

**Comment by dceoy** [comment]
@mrT23 Thank you for the response.

Users always want to use the latest models, but pr-agent only supports models on the internal list.
For example, in the current version, Groq's llama-3.1-405b-reasoning is unavailable.
I am submitting this pull request to enable the use of the latest models as soon as possible without changing the source code.

> max_model_tokens has a default value in the config file. So a user will just state a new model (l'mistral_123B ...'), without stating the max_tokens, and the run might crush for him due to lack of tokens. And he won't understand why. (max_model_tokens serves a different purpose - enforce further restrictions on the models' context - to increase quality and prevent expensive calls)

This change allows the use of a model only if it is on the internal list or if the user specifies max_model_tokens, so the max tokens will be set.

> some models require extra parameters, keys, .. (see for example watson models in https://github.com/Codium-ai/pr-agent/pull/1047). Again, not taking care of it in the code might results in a crush.

That is true, but I think that models from completely new platforms should be validated and blocked at an earlier stage.

**Comment by mrT23** [comment]
@dceoy 
This PR won't be approved as is.

The needed changes:
1) define a new configuration param `config.max_external_model_tokens`, with a default of -1
2) when a model without tokens set for him is used, will be checked if `config.max_external_model_tokens` was defined to a positive value. Only then, will we raise error
3) clear and comprehensive documentation update, describing how to use the new mode. This is a must-have for a new configuration file or option

**Comment by dceoy** [comment]
@mrT23 I understand your suggestion.
However, I do not intend to make this change larger, so I will withdraw this pull request.

**Comment by mrT23** [comment]
@dceoy 
ok.
i will implement it myself, since I think it has value to the community

**Pull request closed without merging**
