### PR TITLE
Add Review Labels for Security and Effort Estimation

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Enhancement

___
## PR Description:
This PR introduces the following enhancements:
- Adds a new feature to set review labels based on the predicted review effort and security concerns.
- Adds new configuration options to enable or disable these review labels.
- Updates the prompts for effort estimation and security concerns to guide the user to provide the expected format of responses.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `pr_agent/tools/pr_reviewer.py`: Added a new method 'set_review_labels' to set review labels based on the review prediction data. The labels are set for review effort and security concerns if enabled in the settings.
- `.pr_agent.toml`: Added a new configuration option 'enable_review_labels_effort' under 'pr_reviewer' section.
- `pr_agent/settings/configuration.toml`: Added new configuration options 'enable_review_labels_security' and 'enable_review_labels_effort' under 'pr_reviewer' section.
- `pr_agent/settings/pr_reviewer_prompts.toml`: Updated the prompts for 'Estimated effort to review' and 'Security concerns' to guide the user to provide the expected format of responses.
</details>

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/452#issuecomment-1812422067)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/7a342d33123866bede7bf8f4f9c57ce47ddeb9c7

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/452#issuecomment-1812422067)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/762a6981e17125c9cfadd3cc239d8d351c708183

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
