### PR TITLE
Remove old 'enable_file_walkthrough' mode

### PR DESCRIPTION
**Pull request by mrT23**
## Type
Enhancement

___

## Description
This PR includes several enhancements and configuration changes:
- The 'enable_file_walkthrough' setting was removed from the PR agent configuration.
- The '_prepare_pr_answer_with_markers' function in 'pr_agent/tools/pr_description.py' was updated to handle PR changes walkthrough instead of file walkthrough.
- The 'label' is now fetched using the 'get' method to avoid KeyErrors.
- The 'FileWalkthrough' class was removed from 'pr_agent/settings/pr_description_prompts.toml'.

___

## Changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_description.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/tools/pr_description.py<br><br>

**The 'enable_file_walkthrough' setting was removed from the <br>PR agent configuration. The <br>'_prepare_pr_answer_with_markers' function was updated to <br>handle PR changes walkthrough instead of file walkthrough. <br>The 'label' is now fetched using the 'get' method to avoid <br>KeyErrors.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/565/files#diff-66130451adce278a098a5770e2db52b12050205fcd4d80c13f813615d4449abb"> +10/-12</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>configuration.toml&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/settings/configuration.toml<br><br>

**The 'enable_file_walkthrough' setting was removed from the <br>configuration file.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/565/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78"> +0/-1</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_description_prompts.toml&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/settings/pr_description_prompts.toml<br><br>

**The 'FileWalkthrough' class was removed from the file.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/565/files#diff-a52546bc2f8a156d8ee786c403e44b1561a6e3f1d98fcfbe8a0120bcee59981b"> +0/-6</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

---
Note that this PR also covers
https://github.com/Codium-ai/pr-agent/pull/562

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/3c2ed8bbf125b75f459f4cdb78e23aa492713356)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/3c2ed8bbf125b75f459f4cdb78e23aa492713356)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/3c2ed8bbf125b75f459f4cdb78e23aa492713356)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/4204d78d7e342ad65bf9befe86bf589e6e3cac9c)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/4204d78d7e342ad65bf9befe86bf589e6e3cac9c)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/4204d78d7e342ad65bf9befe86bf589e6e3cac9c)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/4204d78d7e342ad65bf9befe86bf589e6e3cac9c)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/4204d78d7e342ad65bf9befe86bf589e6e3cac9c)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/565)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/4204d78d7e342ad65bf9befe86bf589e6e3cac9c)

**Review by okotek — APPROVED** [review]

**Pull request merged**
