### PR TITLE
Add 'final_update_message' option to control publishing of update messages

### PR DESCRIPTION
**Pull request by mrT23**
## **Type**
enhancement

___

## **Description**
- Introduced a new `final_update_message` parameter across Git providers (Bitbucket, GitHub, GitLab) to control the publishing of final update messages in persistent comments.
- Updated the abstract `publish_persistent_comment` method in `git_provider.py` to include the `final_update_message` parameter.
- Integrated the `final_update_message` setting into the PR reviewer tool, allowing it to be configured via settings.
- Updated documentation and usage examples to reflect the addition of the `final_update_message` parameter.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>bitbucket_provider.py</strong><dd><code>Add Final Update Message Control to Bitbucket Provider</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/git_providers/bitbucket_provider.py

<li>Added <code>final_update_message</code> parameter to <code>publish_persistent_comment</code> <br>method to control publishing of update messages.<br> <li> Conditionally publish a final update message based on the <br><code>final_update_message</code> flag.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/744/files#diff-3f47323db85f534fa282b2d48c6cf542f00a5e791b62379253ef3d3e8c6bb3b2">+8/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>github_provider.py</strong><dd><code>Implement Final Update Message Option in GitHub Provider</code>&nbsp; </dd></summary>
<hr>
      
pr_agent/git_providers/github_provider.py

<li>Introduced <code>final_update_message</code> parameter in <br><code>publish_persistent_comment</code> to manage final update messages.<br> <li> Update messages are now conditional based on the <code>final_update_message</code> <br>flag.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/744/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11">+8/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>gitlab_provider.py</strong><dd><code>Add Final Update Message Feature to GitLab Provider</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/git_providers/gitlab_provider.py

<li>Added a new parameter <code>final_update_message</code> to <br><code>publish_persistent_comment</code> for final message control.<br> <li> Final update message publication is now conditional, depending on the <br><code>final_update_message</code> parameter.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/744/files#diff-35acba7a2829983fcf3c3c6a69b135988227e503ccdfa94366d1b48fcbbb0a31">+8/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>git_provider.py</strong><dd><code>Abstract Method Update for Final Update Message</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/git_providers/git_provider.py

<li>Added <code>final_update_message</code> parameter to abstract method <br><code>publish_persistent_comment</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/744/files#diff-52d45f12b836f77ed1aef86e972e65404634ea4e2a6083fb71a9b0f9bb9e062f">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pr_reviewer.py</strong><dd><code>Integrate Final Update Message Setting in Reviewer Tool</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/tools/pr_reviewer.py

<li>Integrated <code>final_update_message</code> setting into the review publishing <br>process.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/744/files#diff-8e265068e189a06852605cc694b03e92b523b4f8162077a2f3455ced4cdad8dc">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Usage.md</strong><dd><code>Documentation Update for Final Update Message Parameter</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
Usage.md

<li>Updated documentation to include <code>final_update_message</code> parameter in <br>example commands.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/744/files#diff-98bbb2166f184dd69bb689271547bf3414ce37f682b1f51bd0efdb8b565ce99d">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>REVIEW.md</strong><dd><code>Document Final Update Message Configuration in Review Settings</code></dd></summary>
<hr>
      
docs/REVIEW.md

<li>Documented the <code>final_update_message</code> configuration option in the review <br>tool settings.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/744/files#diff-a4b80781c151b79bd3d7acfe9d62ba33f793740839dcf46a4c98d037ec7db24d">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml</strong><dd><code>Add Final Update Message Configuration Option</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/settings/configuration.toml

<li>Added <code>final_update_message</code> configuration option with a default value <br>of true.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/744/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/744#issuecomment-1979039382)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/359a15c84e6d4449bc39efad3c34c3af5ec9de0f

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by ajdioka** [comment]
Preparing review...

**Comment by ajdioka** [comment]
Preparing PR description...

**Comment by ajdioka** [comment]
Preparing review...

**Comment by ajdioka** [comment]
Preparing review...

**Comment by ajdioka** [comment]
Preparing review...

**Comment by ajdioka** [comment]
Preparing review...

**Comment by ajdioka** [comment]
Preparing review...

**Comment by ajdioka** [comment]
Preparing review...

**Pull request merged**
