### PR TITLE
Ok/gitlab fix

### PR DESCRIPTION
**Pull request by okotek**
### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Refactored the `gitlab_webhook` function to improve async processing and logging.
- Moved the app setup outside of the `start` function for better initialization.
- Enhanced request validation and error handling to ensure secure processing.
- Added detailed logging for request processing time to aid in debugging and monitoring.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>gitlab_webhook.py</strong><dd><code>Refactor GitLab webhook handling and initialization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/servers/gitlab_webhook.py

<li>Refactored <code>gitlab_webhook</code> function to improve async processing and <br>logging.<br> <li> Moved app setup outside of the <code>start</code> function.<br> <li> Enhanced request validation and error handling.<br> <li> Added detailed logging for request processing time.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/941/files#diff-c3ea1ba460930c6e6e6a2c36a7dc729d79730a96e872d40ffb246f80bc7c0880">+67/-57</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by mrT23 — APPROVED** [review]

**Comment by hussam789** [comment]
/improve
--pr_code_suggestions.persistent_comment=true

**Comment by hussam789** [comment]
/improve
--pr_code_suggestions.persistent_comment=true

**Comment by hussam789** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Pull request merged**
