### PR TITLE
Specify Cache Directory in Azure DevOps in Lambda Function Setup

### LINKED ISSUE #443: Getting permission denied in lambda deployment
I have deployed codium agent using a lambda function using this [guide](https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#deploy-as-a-lambda-function).
Branch used: main
I am getting this errror:
```
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/pr_agent/servers/serverless.py", line 7, in <module>
    from pr_agent.servers.github_app import router
  File "/var/task/pr_agent/servers/github_app.py", line 12, in <module>
    from pr_agent.agent.pr_agent import PRAgent
  File "/var/task/pr_agent/agent/pr_agent.py", line 5, in <module>
    from pr_agent.git_providers.utils import apply_repo_settings
  File "/var/task/pr_agent/git_providers/__init__.py", line 7, in <module>
    from pr_agent.git_providers.azuredevops_provider import AzureDevopsProvider
  File "/var/task/pr_agent/git_providers/azuredevops_provider.py", line 12, in <module>
    from azure.devops.connection import Connection
  File "/var/lang/lib/python3.10/site-packages/azure/devops/connection.py", line 9, in <module>
    from ._file_cache import RESOURCE_CACHE as RESOURCE_FILE_CACHE
  File "/var/lang/lib/python3.10/site-packages/azure/devops/_file_cache.py", line 128, in <module>
    DEFAULT_CACHE_DIR = get_cache_dir()
  File "/var/lang/lib/python3.10/site-packages/azure/devops/_file_cache.py", line 118, in get_cache_dir
    os.makedirs(azure_devops_cache_dir)
  File "/var/lang/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)

```
Please help me in resolving this issue.

### PR DESCRIPTION
**Pull request by koid**
## PR Type:
Documentation

___
## PR Description:
This PR updates the documentation to include an additional step in the Lambda function setup process. The new step instructs users to specify the `AZURE_DEVOPS_CACHE_DIR` environment variable in the Lambda function to a writable location such as /tmp. This change is in response to issue #443.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `INSTALL.md`: Added a new step in the Lambda function setup process instructing users to specify the `AZURE_DEVOPS_CACHE_DIR` environment variable to a writable location. The step numbering was also updated accordingly.
</details>

### CODE REVIEW

**Review by barnett-yuxiang — COMMENTED** [review]
May I ask, in general programming habits, the constant string is written in index or defined externally, how to make decisions?

**Comment by koid** [comment]
Thank you for the question.

I also believe that it should be defined externally.
On the other hand, I am uncertain whether it is appropriate to define this issue in configuration.toml as a global application setting, considering that it is a serverless-specific problem.

I think there are other ways as well:
- Add instructions to the Installation Guide to set AWS Lambda environment variables (without modifying the code.)
- Define it in `Dockerfile.lambda` as an ARG with default values (allowing override with build args).

Which method would be appropriate?

**Comment by barnett-yuxiang** [comment]
> Thank you for the question.
> 
> I also believe that it should be defined externally. On the other hand, I am uncertain whether it is appropriate to define this issue in configuration.toml as a global application setting, considering that it is a serverless-specific problem.
> 
> I think there are other ways as well:
> 
> * Add instructions to the Installation Guide to set AWS Lambda environment variables (without modifying the code.)
> * Define it in `Dockerfile.lambda` as an ARG with default values (allowing override with build args).
> 
> Which method would be appropriate?

Personally, I agree with the first one, but you can also listen to the owner. Does pr-agent have a division of owner CR?

**Comment by koid** [comment]
Thank you, I'll limit the updates to the Installation Guide for now.

**Comment by barnett-yuxiang** [comment]
@mrT23 Excuse me, may I ask how your Git Action above triggers PR Analysis work?

🌹

**Comment by mrT23** [comment]
> @mrT23 Excuse me, may I ask how your Git Action above triggers PR Analysis work?
> 
> 🌹

https://github.com/Codium-ai/pr-agent/blob/main/INSTALL.md#run-as-a-github-action
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-action


if you are referring to the labels 'Review effort', see 
https://github.com/Codium-ai/pr-agent/blob/main/.pr_agent.toml#L2

**Comment by mrT23** [comment]
@koid 
i dont understand this PR.
how 'AZURE_DEVOPS_CACHE_DIR` is related to lambda function deployed on AWS ?

**Comment by mrT23** [comment]
@koid is this PR alive, or should I close it ?

i repeat my question - how 'AZURE_DEVOPS_CACHE_DIR` is related to lambda function deployed on AWS ?

**Comment by koid** [comment]
I'm sorry, I noticed the mention late.


In [azure-devops](https://github.com/Codium-ai/pr-agent/blob/ea56910a2f29b4d52e41a7f8c4bb8abf31353b3b/requirements.txt#L20), if the cache directory is not explicitly specified, it will be created [under the home directory](https://github.com/microsoft/azure-devops-python-api/blob/7.1.0b3/azure-devops/azure/devops/_file_cache.py#L114-L115) of the executing user.

In the case of AWS Lambda, the executing user does not have write permissions for the home directory, leading to [a failure in creating the cache directory](https://github.com/Codium-ai/pr-agent/issues/443).

To address this issue, instructions on specifying a path where the executing user has write permissions as the cache directory are added to the README.

**Comment by mrT23** [comment]
@koid 
I still dont understand this PR.
How **AZURE_DEVOPS_CACHE_DIR**  is related to **AWS** lambda  ?

Maybe it is a very specific use case, but it is not a general instruction for any **AWS lambda** .

Share a more logical and coherent instruction in order for it to be merged

**Comment by koid** [comment]
This is not a specific use case but a common limitation in Lambda.

https://docs.aws.amazon.com/lambda/latest/dg/images-create.html#images-reqs

> The container image must be able to run on a read-only file system. Your function code can access a writable /tmp directory with between 512 MB and 10,240 MB, in 1-MB increments, of storage.

As a prerequisite, in AWS Lambda, writable directories are restricted to those under /tmp. (Directories other than /tmp are treated as read-only.)



The pr-agent supports Azure DevOps as a git provider, but the Azure DevOps library requires write permissions to local storage for caching purposes.

When importing azure.devops.connection.Connection, the `Connection` class attempts to create a Cache directory. If the Cache directory is not in a writable area, an [issue](https://github.com/Codium-ai/pr-agent/issues/443) error will occur.

https://github.com/microsoft/azure-devops-python-api/blob/7.1.0b3/azure-devops/azure/devops/connection.py#L9
https://github.com/microsoft/azure-devops-python-api/blob/7.1.0b3/azure-devops/azure/devops/_file_cache.py#L114-L115

If the import of the `Connection` is done within the AzureDevopsProvider class, it is possible to avoid errors when not using the Azure DevOps provider. However, since the import is done outside the AzureDevopsProvider class, errors will still occur even if the Azure DevOps provider is not being used.

https://github.com/Codium-ai/pr-agent/blob/fe796245a3c43a042d70efc86e8f53c8a0137247/pr_agent/git_providers/azuredevops_provider.py#L12
https://github.com/Codium-ai/pr-agent/blob/fe796245a3c43a042d70efc86e8f53c8a0137247/pr_agent/git_providers/__init__.py#L8



To avoid this, you need to specify AZURE_DEVOPS_CACHE_DIR to a writable directory (or you can specify it to /tmp, which is a writable directory under HOME) as a workaround.

--

Perhaps, in terms of chronology, Lambda support was added first (#92), followed by the Azure DevOps Provider support (#265), which might explain why the Lambda specifications were not taken into consideration during #265.

**Comment by mrT23** [comment]
@koid 
thanks for the detailed explanation

i will add a link to that explanation in the readme, since without it, it won't be clear how the things are connected

**Review by mrT23 — APPROVED** [review]

**Pull request merged**
