### PR TITLE
update github_actions_runner file for multi commands

### PR DESCRIPTION
**Pull request by sarbjitsinghgrewal**
Here is Pull request for Trigger multiple PR-Agent command on GitHub Actions pull request event. In this PR, I update script to support multiple PR-Agent command on GitHub Actions. I reuse logic from github_app.py file. I also add [github_workflow] section in configuration.toml file to handle github_actions_runner file. Now This script running fine and handle multi-commands. Here is screenshot for example:
image

### CODE REVIEW

**Comment by sarbjitsinghgrewal** [comment]
This PR solves #309

**Comment by mrT23** [comment]
This was already addressed:
https://github.com/Codium-ai/pr-agent/commit/a6e65e867fb5b0c93d13203301204edf1a6ebb39
https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-action

In addition, I don't see how the proposed solution would work. 'pr_commands' is a complicated list-like object, not a string.
How can you give it as an environment variable ?

**Comment by sarbjitsinghgrewal** [comment]
@mrT23 
yes, this functionality has already been implemented using GitHub Actions. However, previously, only the review command was executed for every pull request. Recently, there was a request to trigger multiple commands using GitHub Actions. As a result, I have updated the code to accommodate multiple commands. To achieve this, I have switched from using a single string to using a list. Now, GitHub Actions will run two commands: /describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true and /auto_review. Please review and provide feedback.

**Comment by mrT23** [comment]
@sarbjitsinghgrewal 
The change in https://github.com/Codium-ai/pr-agent/pull/329 enables the user to automatically run any tool he want, with github action. The default option is to run only the 'review' tool, and I want it to remain this way for now. Users can easily change the default option, to suit their needs.

You suggest here a completely different mechanism, ignoring the previous mechanism, without any reason.
In addition, i don't think your mechanism works, because GitHub action enables giving only plain strings as environment variables, and 'pr_command' is a list, not a string. Have you checked that your mechanism works ?


This PR will not be merged, due to the reasons above. We will think in the future about some refactoring and unification of the auto-command syntax, and may use your PR as reference.

**Comment by R3KTARD** [comment]
Merge

**Comment by R3KTARD** [comment]
Invalid

**Comment by UjjawalKRoy** [comment]
Preparing review...

**Comment by UjjawalKRoy** [comment]
Preparing review...

**Comment by UjjawalKRoy** [comment]
Preparing review...

**Comment by UjjawalKRoy** [comment]
Preparing review...

**Comment by UjjawalKRoy** [comment]
Preparing review...

**Comment by UjjawalKRoy** [comment]
Preparing review...

**Comment by UjjawalKRoy** [comment]
Preparing review...

**Comment by UjjawalKRoy** [comment]
Preparing review...

**Pull request closed without merging**
