### PR TITLE
Ok/identity provider

### PR DESCRIPTION
**Pull request by okotek**
## **Type**
enhancement

___

## **Description**
- Introduced an identity provider mechanism to determine eligibility for processing PRs based on the sender's identity.
- Added a default identity provider implementation that marks all requests as eligible.
- Integrated identity verification into GitHub and Bitbucket webhook handlers to conditionally process events.
- Enhanced logging with build number information for better traceability in GitHub app.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Implement Identity Provider Selection Mechanism</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/identity_providers/__init__.py

<li>Introduced <code>get_identity_provider</code> function to fetch identity provider <br>based on configuration.<br> <li> Added a dictionary <code>_IDENTITY_PROVIDERS</code> mapping string identifiers to <br>identity provider classes.<br> <li> Implemented logic to select and instantiate the appropriate identity <br>provider based on settings.<br>

</details>
    

  </td>
  <td><a href="https:/Codium-ai/pr-agent/pull/719/files#diff-7902b84cc8f977f2051b8c5b6950478beececd29e4b252af8a0c72c9157dd663">+13/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>default_identity_provider.py</strong><dd><code>Add Default Identity Provider Implementation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/identity_providers/default_identity_provider.py

<li>Defined <code>DefaultIdentityProvider</code> class inheriting from <br><code>IdentityProvider</code>.<br> <li> Implemented <code>verify_eligibility</code> method returning <code>Eligibility.ELIGIBLE</code> <br>for all cases.<br> <li> Added a placeholder <code>inc_invocation_count</code> method.<br>

</details>
    

  </td>
  <td><a href="https:/Codium-ai/pr-agent/pull/719/files#diff-c20ae1c859d8e4896c60b3d9645ce3d696b104fa69cc5ea9d633036433ccbbaf">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>identity_provider.py</strong><dd><code>Define Identity Provider Interface and Eligibility Enum</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
pr_agent/identity_providers/identity_provider.py

<li>Introduced <code>Eligibility</code> enum with values NOT_ELIGIBLE, ELIGIBLE, and <br>TRIAL.<br> <li> Defined abstract base class <code>IdentityProvider</code> with abstract methods <br><code>verify_eligibility</code> and <code>inc_invocation_count</code>.<br>

</details>
    

  </td>
  <td><a href="https:/Codium-ai/pr-agent/pull/719/files#diff-b3f3fa90de9f8ee7e7113a37e7f072c2092c400d74778efc46eccee3cb6e4f57">+18/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>bitbucket_app.py</strong><dd><code>Integrate Identity Provider in Bitbucket Webhook Handling</code></dd></summary>
<hr>
      
pr_agent/servers/bitbucket_app.py

<li>Imported <code>get_identity_provider</code> and <code>Eligibility</code> to handle identity <br>verification.<br> <li> Added logic to skip processing if the actor is not a user or if the <br>identity is not eligible.<br> <li> Enhanced error handling and logging for missing actor type and owner <br>information.<br>

</details>
    

  </td>
  <td><a href="https:/Codium-ai/pr-agent/pull/719/files#diff-963a9de391ff22ad3083c3a28c1d5736d68a6e1e40b0bedb52d4bfd124325bad">+36/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>github_app.py</strong><dd><code>Enhance GitHub App with Identity Verification and Build Info</code></dd></summary>
<hr>
      
pr_agent/servers/github_app.py

<li>Integrated identity provider checks to skip processing for ineligible <br>identities.<br> <li> Added build number reading and logging for better traceability.<br> <li> Refactored imports and added sender ID to context for identity <br>verification.<br>

</details>
    

  </td>
  <td><a href="https:/Codium-ai/pr-agent/pull/719/files#diff-3fb3f174152732d1b69953c8bd81b8a0a30f0e42100dc626d932da8371851608">+28/-13</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by mrT23 — APPROVED** [review]

**Comment by hussam789** [comment]
## Finding similar code for 'inner'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'handle_push_trigger_for_new_commits'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'find a function that adds the eyes emoji to a github comment?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'how tree-sitter grammar gets initialized ?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'how tree-sitter grammar gets initialized ?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'how tree-sitter grammar gets initialized ?'


Work in progress ...<br>

**Comment by hussam789** [comment]
## Finding similar code for 'how tree-sitter grammar gets initialized ?'


Work in progress ...<br>

**Pull request merged**
