### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
dependencies

___

### **Description**
- Updated `fastapi` from version 0.99.0 to 0.111.0
- Updated `litellm` from version 1.34.42 to 1.40.17
- Updated `openai` from version 1.13.3 to 1.35.1

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Update dependencies in requirements.txt file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
requirements.txt

<li>Updated <code>fastapi</code> from version 0.99.0 to 0.111.0<br> <li> Updated <code>litellm</code> from version 1.34.42 to 1.40.17<br> <li> Updated <code>openai</code> from version 1.13.3 to 1.35.1<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/989/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/989)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/b12554ee84e263060c4bf70590d2cd93274d30de)

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/989)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/b12554ee84e263060c4bf70590d2cd93274d30de)

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
