### PR TITLE
Enhancement: Apply Repository Settings on Every 'Synchronize' Event

### PR DESCRIPTION
**Pull request by mrT23**
## Type
Enhancement

___
## Description
This PR modifies the handling of the 'pull_request' event with 'synchronize' action in the 'github_app.py' file. The main changes include:
- The application of repository settings is now triggered on every 'synchronize' event, not only when the 'handle_push_trigger' setting is enabled.
- The 'handle_push_trigger' setting is now checked after applying the repository settings, and if it's not enabled, the function returns without further processing.

___
## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>github_app.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/servers/github_app.py<br><br>
        <strong>The 'handle_request' function has been updated to apply <br>repository settings on every 'synchronize' event. The check <br>for the 'handle_push_trigger' setting is now performed after <br>applying the repository settings.</strong>
      </ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/511/files#diff-3fb3f174152732d1b69953c8bd81b8a0a30f0e42100dc626d932da8371851608"> +5/-1</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
**[PR Description](https://github.com/Codium-ai/pr-agent/pull/511)** updated to latest commit (https://github.com/Codium-ai/pr-agent/commit/a043eb939b853cf792c4a089dec93d55fadef33d)

**Comment by zmeir** [comment]
LGTM. I can't think of a cleaner way to handle this. The only other option I can think of is to just explicitly state in the README that this feature can only be enabled/disables via the global settings. But then what's the point of having it anyway?

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/511#issuecomment-1844767270)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/a043eb939b853cf792c4a089dec93d55fadef33d

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/511#issuecomment-1844767270)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/a043eb939b853cf792c4a089dec93d55fadef33d

**Pull request merged**
