### PR TITLE
LanceDB Integration

### PR DESCRIPTION
**Pull request by PrashantDixit0**
## Type
Enhancement

___

## Description
This PR introduces LanceDB integration into the `pr_agent` tool. The most significant changes include:
- The `pr_agent/tools/pr_similar_issue.py` file has been updated to support both Pinecone and LanceDB as vector databases. This is controlled by the `pr_similar_issue.vectordb` setting.
- New methods `_update_table_with_issues` for indexing issues in LanceDB have been added.
- The `run` method has been updated to support querying from both Pinecone and LanceDB.
- The documentation file `docs/SIMILAR_ISSUE.md` has been updated to include information about the new LanceDB integration.
- The configuration file `pr_agent/settings/configuration.toml` has been updated to include a new setting `vectordb` under `pr_similar_issue` and a new section for `lancedb` settings.
- The `requirements.txt` file has been updated to include the `lancedb` package.

___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>pr_similar_issue.py&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/tools/pr_similar_issue.py<br><br>

**The file `pr_agent/tools/pr_similar_issue.py` has been <br>significantly updated to support LanceDB integration. The <br>changes include:
- Added `import lancedb` at the top of the <br>file.
- Modified the `PRSimilarIssue` class to support both <br>Pinecone and LanceDB as vector databases. This is controlled <br>by the `pr_similar_issue.vectordb` setting.
- Added new <br>methods `_update_table_with_issues` for indexing issues in <br>LanceDB.
- Updated the `run` method to support querying from <br>both Pinecone and LanceDB.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/548/files#diff-593201e09c7e1e2cc484fdb85fa7f047eef067a6e51d168778efe637e9e0d74e"> +271/-86</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>SIMILAR_ISSUE.md&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        docs/SIMILAR_ISSUE.md<br><br>

**The documentation file `docs/SIMILAR_ISSUE.md` has been <br>updated to include information about the new LanceDB <br>integration.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/548/files#diff-5379519cfe03f2c93212b33fe87245bca09cc35f005210a5fe104be0aef06f79"> +9/-1</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>configuration.toml&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pr_agent/settings/configuration.toml<br><br>

**The configuration file <br>`pr_agent/settings/configuration.toml` has been updated to <br>include a new setting `vectordb` under `pr_similar_issue` <br>and a new section for `lancedb` settings.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/548/files#diff-66cfda5143e484ee53ecf7aa0df7dca8ad0b181256f4b0675905db35bcbbae78"> +3/-0</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Dependencies</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        requirements.txt<br><br>

**The `requirements.txt` file has been updated to include the <br>`lancedb` package.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/548/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552"> +1/-0</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by mrT23** [comment]
Hi @PrashantDixit0 
Thanks for the contribution

i started reviewing the PR.  One thing I noticed is that you must set the baste folder to the root folder.
When I tried running it from `./pr_agent/,` I got an error. i hope this won't create problems during deployement

**Comment by mrT23** [comment]
3) when there is no new issues, lancdb uses the old index 👍 

4) I opened a new issue, to see how the db is updated. this is what I got:
image
is this the expected output ?
why there is a line:` Table codium-ai-pr-agent-issues doesn't exists!` ?

**Comment by PrashantDixit0** [comment]
LanceDB saves everything locally

**Comment by PrashantDixit0** [comment]
I'll check to update new issues in Table

**Comment by mrT23** [comment]
locally is ok for CLI, but when working the github app or github action, a local database is not possible.

please state in the readme that lanceDB is a local database, so more suited for CLI.
due to that, i want the default to remain pinecone, since it is more suitable for an application.

but other than that, the PR looks very good. its very nice to work with lanceDB, without needing any key or stuff like that.
the readme can also state that for local CLI testing, lancedb is easier.

**Comment by PrashantDixit0** [comment]
Thank you @mrT23 , I'll state about LanceDB in README. LanceDB is working on bringing a high-speed, scalable, and serverless cloud-based system, we can integrate it once it is released.

Btw, when can we merge this PR for local testing

**Comment by mrT23** [comment]
@PrashantDixit0 change back the default to pinecone (so the app would still work), and I think we can merge.
If you want to continue to improve it after that, you are welcome

**Comment by PrashantDixit0** [comment]
Sure @mrT23, I change default to pinecone and I am really interested in continue improving the amazing PR-agent

**Comment by PrashantDixit0** [comment]
Done

**Review by mrT23 — APPROVED** [review]

**Pull request merged**
