### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by mrT23**
## **Type**
enhancement

___

## **Description**
- Added a debug print statement to `setup.py` to enhance visibility during the setup process.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>setup.py</strong><dd><code>Add Debug Print Statement to Setup Script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
setup.py

<li>Added a print statement to output "setup !!!!!!! " when the setup <br>script is run.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/680/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by nagkumar** [comment]
@CodiumAI-Agent /review

**Comment by nagkumar** [comment]
@CodiumAI-Agent /IMPROVE

**Comment by AnasAyyad** [comment]
@CodiumAI-Agent /improve

**Pull request closed without merging**
