### PR TITLE
Enhancement of Inline Comment Publishing in Bitbucket Provider and Logging Addition

### PR DESCRIPTION
**Pull request by mrT23**
## type:
Enhancement

___
## description:
This PR primarily focuses on enhancing the inline comment publishing feature in the Bitbucket provider and adding logging for cases where no suggestions are found in the `pr_code_suggestions.py` file. The key changes include:
- In the `bitbucket_provider.py` file, the `publish_inline_comments` method has been updated to handle different types of comments, including multi-line and single-line comments. It also logs an error if it cannot publish an inline comment.
- In the `pr_code_suggestions.py` file, a logging statement has been added to inform when no suggestions are found to improve a PR.

___
## main_files_walkthrough:
<details> <summary>files:</summary>

- `pr_agent/git_providers/bitbucket_provider.py`: The `publish_inline_comments` method has been updated to handle different types of comments. It now checks if the comment is a multi-line comment, a single-line comment, or if it has a position. If none of these conditions are met, it logs an error message.
- `pr_agent/tools/pr_code_suggestions.py`: A logging statement has been added to the `push_inline_code_suggestions` method to inform when no suggestions are found to improve a PR.
</details>

## Tested:
tested on https://bitbucket.org/codiumai/pr-agent/pull-requests/7:
 'improve' and 'review --pr_reviewer.inline_code_comments=true'

### CODE REVIEW

**Review by okotek — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/485#issuecomment-1830252380)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/51e1278cd73b8396daf7e2d44a5191d5236aec58

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/485#issuecomment-1830252380)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/51e1278cd73b8396daf7e2d44a5191d5236aec58

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/485#issuecomment-1830252380)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/51e1278cd73b8396daf7e2d44a5191d5236aec58

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/485#issuecomment-1830252380)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/51e1278cd73b8396daf7e2d44a5191d5236aec58

**Pull request merged**
