### PR TITLE
Improved Error Handling for Bearer Token Retrieval

### PR DESCRIPTION
**Pull request by NxPKG**
### **User description**
class definition for BitbucketProvider, which integrates with Bitbucket Cloud to manage pull requests (PRs), issues, and comments. Here are a few potential issues in the code:

Error Handling for Bearer Token Retrieval:

The code tries to retrieve the bearer token from the context first and falls back to the settings if it fails. This approach can hide issues with retrieving the token from the context.

2. Missing Type Hint for publish_code_suggestions Method:

The method publish_code_suggestions is missing a return type hint. Incorrect Parsing of PR URL:

The method _parse_pr_url is used to parse the PR URL but is not checking the URL format strictly, which might lead to incorrect parsing. Use of Static Headers:

The Authorization header is set once during initialization and is not updated, which might cause issues if the token expires or changes. Method _get_pr_file_content Returns Empty String:

The method _get_pr_file_content is currently a placeholder returning an empty string. This needs to be implemented to fetch actual file contents. Missing Implementation for get_commit_messages:

The method get_commit_messages returns an empty string, indicating it's not yet implemented. Method get_issue_comments Raises NotImplementedError:

The method get_issue_comments raises NotImplementedError, which is acceptable but may need to be implemented based on project requirements. Potential Issue in get_issue_numbers_from_list Method:

This method might return only the first issue number in the list due to the return statement inside the loop. It should return a list of issue numbers instead. Potentially Redundant Imports:

Ensure that all imported modules and functions are used within the code to avoid unnecessary imports. Handling JSON Responses:

The methods like parse_issue_url_and_get_comments use requests to make API calls and handle JSON responses. Proper error handling should be added to handle cases where the response is not JSON or contains errors.

Issue #400

___

### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Refactored the initialization process to separate the authorization header setup into a new method `set_authorization_header`.
- Implemented the `get_commit_messages` method to fetch and return commit messages from the pull request.
- Added several new methods for handling issues and comments, including `get_issue`, `get_issue_url`, `get_issue_body`, `get_issue_comment_body`, `parse_issue_url_and_get_comments`, and more.
- Improved the `publish_code_suggestions` method with better logging and error handling for edge cases.
- Simplified the `is_supported` method to return a boolean directly.
- Enhanced the `_parse_pr_url` method to include better error handling and validation.
- Removed redundant methods and streamlined the existing ones for better performance and readability.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>bitbucket_provider.py</strong><dd><code>Refactor and enhance BitbucketProvider class with improved error </code><br><code>handling and new methods.</code></dd></summary>
<hr>
      
pr_agent/git_providers/bitbucket_provider.py

<li>Refactored error handling for bearer token retrieval into a separate <br>method <code>set_authorization_header</code>.<br> <li> Implemented the <code>get_commit_messages</code> method to fetch commit messages.<br> <li> Added new methods for handling issues and comments, such as <code>get_issue</code>, <br><code>get_issue_url</code>, <code>get_issue_body</code>, <code>get_issue_comment_body</code>, and more.<br> <li> Improved the <code>publish_code_suggestions</code> method with better logging and <br>error handling.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/924/files#diff-3f47323db85f534fa282b2d48c6cf542f00a5e791b62379253ef3d3e8c6bb3b2">+141/-248</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by mrT23** [comment]
@NxPKG thanks for the contribution.

walk me a bit along this PR. it contains a lot of changes, but i guess that most of them are cosmetic (or not ?)
`+141 −248`

where are the core changes ? have you validate that bitbucket works well with this PR ? what improvement should we get from it ?

**Comment by mrT23** [comment]
## PR Code Suggestions ✨

No code suggestions found for PR.

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by mrT23** [comment]
## PR Code Suggestions ✨

No code suggestions found for PR.

**Comment by mrT23** [comment]
## PR Code Suggestions ✨

No code suggestions found for PR.

**Comment by huangchen007** [comment]
Preparing review...

**Comment by huangchen007** [comment]
Preparing review...

**Comment by huangchen007** [comment]
Preparing review...

**Comment by huangchen007** [comment]
Preparing review...

**Comment by huangchen007** [comment]
Preparing review...

**Comment by huangchen007** [comment]
Preparing review...

**Comment by huangchen007** [comment]
Preparing review...

**Comment by mrT23** [comment]
@NxPKG 
warning - i feel the is an auto-generated PR.
If not, respond within 24 hours to my questions, or I will close it

**Pull request closed without merging**
