### PR TITLE
Tr/code cov

### PR DESCRIPTION
**Pull request by mrT23**
### **PR Type**
enhancement, tests

___

### **Description**
- Added a new GitHub Actions workflow to automate code coverage reporting.
- Configured Docker within the workflow to build and test the application.
- Integrated Codecov to upload and manage code coverage reports.
- Updated `requirements.txt` to include `pytest-cov` for coverage reporting.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>code_coverage.yaml</strong><dd><code>Add GitHub Actions workflow for code coverage with Docker and Codecov</code></dd></summary>
<hr>

.github/workflows/code_coverage.yaml

<li>Added a new GitHub Actions workflow for code coverage.<br> <li> Configured Docker to build and test the application.<br> <li> Integrated Codecov for uploading coverage reports.<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1095/files#diff-57eac9ce2a305f1965ecf46aafb672a916133709dfb666a242ac4c287784ca76">+47/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Add pytest-cov to requirements for code coverage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt

- Added `pytest-cov` dependency for code coverage reporting.

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1095/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by coditamar** [comment]
@mrT23 , is codecov the only solution?

**Comment by mrT23** [comment]
> codecov

it depends on what you mean by "codcov".

1) after each PR/push/whatever we run

`pytest tests/unittest --cov=pr_agent --cov-report term --cov-report xml:coverage.xml`

to generate a **coverage file**, in a know format (corbatura). This operation is generic, and the big advantage is that the same file will be generated also in other languages and testing frameworks.


2) We then upload the file with a GitHub app called `codecov`. They will provide us a summary table, and they also build like a SaaS coverage database and dashboard

image
image

This is optional. Maybe we want to replace\complement them...

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
