### PR TITLE
Enhancement of Patch Handling and PR Processing

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Enhancement

___
## PR Description:
This PR introduces several enhancements to the PR processing and patch handling:
- Added handling for different types of file edits (added, deleted, modified, renamed) in both GitHub and Bitbucket providers.
- Enhanced the filtering of ignored files to handle cases where the filename is None.
- Improved the handling of patch deletions to consider the type of edit.
- Modified the PR processing to differentiate between added files and modified files when the token limit is reached.
- Updated the Bitbucket provider to handle cases where updating the PR description fails.
- Minor changes to the logging and error handling.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `pr_agent/algo/file_filter.py`: Updated the filtering of ignored files to handle cases where the filename is None.
- `pr_agent/algo/git_patch_processing.py`: Enhanced the handling of patch deletions to consider the type of edit.
- `pr_agent/algo/pr_processing.py`: Modified the PR processing to differentiate between added files and modified files when the token limit is reached.
- `pr_agent/git_providers/bitbucket_provider.py`: Added handling for different types of file edits (added, deleted, modified, renamed) and improved error handling when updating the PR description fails.
- `pr_agent/git_providers/git_provider.py`: Added an UNKNOWN type to the EDIT_TYPE enum and set it as the default edit type for FilePatchInfo.
- `pr_agent/git_providers/github_provider.py`: Added handling for different types of file edits (added, deleted, modified, renamed).
- `pr_agent/settings/pr_reviewer_prompts.toml`: Minor formatting changes to the PR reviewer prompts.
</details>

### CODE REVIEW

**Review by hussam789 — APPROVED** [review]

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
## Incremental PR Review

-  **⏮️ Review for commits since previous PR-Agent review:** Starting from commit https://github.com/Codium-ai/pr-agent/pull/439/commits/c5bc4b44ff24858382fd98754868ac4fc9561128  
_(fix added files)_
## PR Analysis

- 🎯 **Main theme:** Enhancement of Patch Handling and PR Processing
- 📝 **PR summary:** This PR introduces several enhancements to the PR Agent, including the addition of an `EDIT_TYPE` enum to distinguish between different types of file edits, updates to various functions to handle added files separately from modified files, and adjustments to token clipping in the `get_pr_description` method.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No

**Comment by mrT23** [comment]
## Incremental PR Review

-  **⏮️ Review for commits since previous PR-Agent review:** Starting from commit https://github.com/Codium-ai/pr-agent/pull/439/commits/None
## PR Analysis

- 🎯 **Main theme:** Enhancement of Patch Handling and PR Processing
- 📝 **PR summary:** This PR introduces several enhancements to the PR Agent, including the addition of an `EDIT_TYPE` enum to distinguish between different types of file edits, updates to the `handle_patch_deletions` function to consider the `EDIT_TYPE` of the file, and modifications to the `get_pr_diff` and `pr_generate_compressed_diff` functions to handle added files separately from modified files. It also updates the `get_diff_files` method to assign the `EDIT_TYPE` to the `FilePatchInfo` object and adjusts the token clipping in the `get_pr_description` method.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 4, due to the multiple changes across different files and the introduction of new logic related to handling different types of file edits.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** The PR introduces a significant enhancement to the PR Agent by handling different types of file edits separately. This is a good practice as it allows for more granular control and better handling of different scenarios. However, it would be beneficial to ensure that all possible edge cases are handled correctly, especially when dealing with different types of file edits. It would also be helpful to add tests to verify the new functionality and ensure that it works as expected.


- **<details><summary> 🤖 Code feedback:**</summary>


  - **relevant file:** ``pr_agent/algo/git_patch_processing.py``
   **suggestion:** Consider handling the case where `edit_type` is `EDIT_TYPE.UNKNOWN`. Currently, if `edit_type` is `EDIT_TYPE.UNKNOWN`, the code behaves as if the file was not deleted, which might not be the correct behavior. [important]
   **relevant line:** [if not new_file_content_str and edit_type != EDIT_TYPE.ADDED:](https://github.com/Codium-ai/pr-agent/pull/439/files#diff-c5a7f9db4adbcf394c7855f6da656c073d5a6bcc18bd6dede44a8207893174b8R136)


  - **relevant file:** ``pr_agent/algo/pr_processing.py``
   **suggestion:** It seems like the `pr_generate_compressed_diff` function now returns an additional value `added_file_names`. Ensure that all calls to this function are updated to handle this additional return value. [important]
   **relevant line:** [patches_compressed, modified_file_names, deleted_file_names, added_file_names = \](https://github.com/Codium-ai/pr-agent/pull/439/files#diff-c2d64de584ef3cb05c9007d72137f6c7ce04c9bc23ce1931760af3a568edb04eR73)


  - **relevant file:** ``pr_agent/git_providers/bitbucket_provider.py``
   **suggestion:** The `get_diff_files` method now assigns the `EDIT_TYPE` to the `FilePatchInfo` object based on the status of the diff. It would be good to handle the case where the status of the diff is not one of the expected values. [medium]
   **relevant line:** [if diff.data['status'] == 'added':](https://github.com/Codium-ai/pr-agent/pull/439/files#diff-3f47323db85f534fa282b2d48c6cf542f00a5e791b62379253ef3d3e8c6bb3b2R142)


  - **relevant file:** ``pr_agent/git_providers/github_provider.py``
   **suggestion:** Similar to the previous suggestion, ensure that all possible statuses are handled in the `get_diff_files` method. [medium]
   **relevant line:** [if file.status == 'added':](https://github.com/Codium-ai/pr-agent/pull/439/files#diff-28979ec713529d6f619bcba0b9e6a3002d1164d47c70ccfea7f15306618a1a11R132)

</details>

**Comment by mrT23** [comment]
Preparing PR description...

**Review by barnett-yuxiang — COMMENTED** [review]
good

**Comment by mrT23** [comment]
Preparing PR description...

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
Preparing review...

**Pull request merged**
