### PR TITLE
GFM mode for 'review' instructions

### PR DESCRIPTION
**Pull request by mrT23**
## PR Type:
Enhancement

___
## PR Description:
This PR introduces several updates to the PR agent's instructions and commands:
- The instructions in `pr_agent/servers/help.py` have been updated for clarity and additional commands have been added.
- A link to the tools guide and the configuration file has been added for easy reference.
- The PR review preparation process in `pr_agent/tools/pr_reviewer.py` has been updated to include the new commands.
- The `INSTALL.md` file has been updated to include the new `generate_labels` command in the CLI examples.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `pr_agent/servers/help.py`: Updated the commands text for clarity and added two new commands, `/add_docs` and `/generate_labels`. Also added links to the tools guide and the configuration file.
- `pr_agent/tools/pr_reviewer.py`: Updated the PR review preparation process to include the new commands. If the git provider supports 'gfm_markdown', the instructions are wrapped in a 'details' HTML tag for better readability.
- `INSTALL.md`: Added the new `generate_labels` command to the CLI examples.
</details>

## Examples:

image

image

### CODE REVIEW

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/460#issuecomment-1817793178)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/eb977b4c244de15f429162892600b1f0bc609cae

**Comment by mrT23** [comment]
Preparing review...

**Comment by mrT23** [comment]
**[Persistent review](https://github.com/Codium-ai/pr-agent/pull/460#issuecomment-1817793178)** updated to latest commit https://github.com/Codium-ai/pr-agent/commit/eb977b4c244de15f429162892600b1f0bc609cae

**Review by hussam789 — APPROVED** [review]

**Pull request merged**
